// French A1 + A2 lemma list. Dos bloques, cada uno con su fuente.
//
// BLOQUE 1: FRENCH_A1_A2_ORIGINAL (818 cadenas, el de siempre).
// Fuente declarada al crearlo: DELF A1/A2 + Routledge frequency dictionary
// French top-1500, curado a mano. Sin trazabilidad por palabra.
//
// BLOQUE 2: FRENCH_A1_A2_LEXIQUE (2026-09-13, sustituye al bloque FLELex del
// mismo día, retirado por licencia no comercial: ver el commit anterior).
// Fuente EXTERNA: Lexique383 (lexique.org / openlexicon), base de datos
// lexical del francés de Boris New, Christophe Pallier y colaboradores
// (Université de Savoie / CNRS). ~140.000 formas con frecuencia lematizada
// en dos corpus (subtítulos de película y libros).
//   http://www.lexique.org  ·  http://openlexicon.fr/datasets-info/Lexique382/
//   New, B., Pallier, C., Brysbaert, M. & Ferrand, L. (2004). Lexique 2: a
//   new French lexical database. Behavior Research Methods 36(3), 516-524.
//   Licencia: CC BY-SA 4.0 (verificada en openlexicon.fr, permite uso
//   comercial con atribución y misma licencia en derivados).
//
// Lexique NO trae nivel MCER por palabra (a diferencia de FLELex); es una
// lista de FRECUENCIA. El corte que sustituye al nivel MCER se calibró así,
// contra una vara externa al catálogo (feedback_level_measured_externally):
//   1. Para cada lema: frecuencia = promedio de freqlemfilms2 y freqlemlivres
//      (subtítulos + libros, por millón de palabras).
//   2. Se ordena todo Lexique por esa frecuencia, excluyendo nombres propios,
//      onomatopeyas, símbolos, abreviaturas y números (cgram NAM/ONO/SYM/
//      ABR/NUM), palabras con dígitos o guion bajo, y una lista corta de
//      soeces/insultos que la frecuencia de subtítulos sube alto sin que eso
//      diga nada de su nivel (register, no nivel; ya tienen su propia
//      exención en validateGeneratedStory y no necesitan estar aquí también).
//   3. CORTE: las 6000 más frecuentes tras ese filtro. Calibrado con dos
//      referencias:
//      - Los 816 lemas del bloque 1 (curado a mano, se asume A1/A2 real):
//        793 de ellos existen como lema suelto en Lexique (23 son locuciones
//        de varias palabras o formas reflexivas que Lexique no lematiza
//        igual, p. ej. "salle de bain", "se réveiller"); de esos 793, el
//        corte de 6000 cubre 763 (96,2%). El 3,8% que queda fuera del corte
//        sigue en la lista igual, porque el bloque 1 se conserva completo
//        y sin condición.
//      - Una muestra de 16 palabras claramente B2/C1 (épistémologie,
//        consubstantiel, idiosyncrasie, paradigme, dialectique, ontologie,
//        hégémonie, syncrétisme, anthropomorphisme, exégèse, solipsisme,
//        phénoménologie, herméneutique, dichotomie, antinomie, sophistique):
//        la más frecuente de las 16 (dialectique) ocupa el puesto 13.650,
//        más del doble del corte. Ninguna entra.
//   Motivadoras del encargo original (souvenir, blague, habitude, discours,
//   accent) caen en los puestos 321-2036: entran con margen.
// LÍMITE reconocido: frecuencia pura no es lo mismo que nivel MCER (por eso
// existe FLELex, que combina frecuencia con el juicio experto de Beacco).
// Palabras frecuentes pero conceptualmente B1/B2 (p. ej. "revendication",
// puesto 9454) SÍ pueden colarse dentro del corte igual que quedaron fuera
// aquí por casualidad; el corte separa "claramente básico" de "claramente
// avanzado", no A2 de B1 con precisión de experto. No se corrige más porque
// no hay más señal barata sin volver a una fuente NC.
// NO se añade nada porque un journey lo necesite: el corte es el mismo para
// cualquier journey francés, elegido antes de mirar ninguna historia.

const FRENCH_A1_A2_ORIGINAL: readonly string[] = [
  // Function words
  "le","la","les","un","une","des","du","de","au","aux","ce","cette","ces","mon","ton","son",
  "notre","votre","leur","mes","tes","ses","nos","vos","leurs",
  "je","tu","il","elle","on","nous","vous","ils","elles","me","te","se","lui","leur","y","en",
  "et","ou","mais","car","donc","puis","alors","ensuite","parce que","pour","afin","si",
  "quand","lorsque","pendant","avant","après","depuis","jusqu","entre","parmi","contre",
  "à","de","en","dans","sur","sous","derrière","devant","près","loin","avec","sans","pour",
  "ne","pas","plus","jamais","rien","personne","aucun","oui","non","peut-être","sûrement",
  "ici","là","là-bas","dehors","dedans","haut","bas","ailleurs","partout",
  "très","beaucoup","peu","trop","assez","aussi","encore","déjà","tout","tous","toute","toutes",
  "même","autre","chaque","quelque","plusieurs","tel",

  // Time
  "jour","nuit","matin","après-midi","soir","heure","minute","seconde","semaine","mois",
  "année","an","temps","moment","instant","week-end","vacances","fête",
  "lundi","mardi","mercredi","jeudi","vendredi","samedi","dimanche",
  "janvier","février","mars","avril","mai","juin","juillet","août","septembre","octobre",
  "novembre","décembre","printemps","été","automne","hiver",
  "aujourd'hui","demain","hier","maintenant","bientôt","tôt","tard","souvent","toujours",
  "jamais","parfois","quelquefois",

  // Family / people
  "famille","père","papa","mère","maman","fils","fille","frère","sœur","grand-père","grand-mère",
  "oncle","tante","cousin","cousine","mari","femme","époux","épouse","enfant","bébé",
  "garçon","fille","homme","femme","personne","gens","ami","amie","copain","copine","voisin",
  "collègue","monsieur","madame","mademoiselle",

  // Body
  "corps","tête","visage","figure","œil","oreille","nez","bouche","dent","langue","lèvre",
  "cou","épaule","bras","main","doigt","ongle","poitrine","dos","ventre","jambe","genou","pied",
  "cheveu","peau","sang","os","cœur","estomac",

  // Clothes
  "vêtement","chemise","tee-shirt","pantalon","jupe","robe","manteau","veste","pull","pyjama",
  "chaussure","botte","sandale","chaussette","chapeau","casquette","écharpe","gant","ceinture",
  "cravate","lunettes","bague","montre","sac","mochila","portefeuille","porte-monnaie",

  // Home
  "maison","appartement","chambre","salon","cuisine","salle de bain","toilettes","couloir",
  "escalier","ascenseur","porte","fenêtre","mur","sol","plafond","toit","jardin","balcon",
  "terrasse","table","chaise","canapé","fauteuil","lit","matelas","armoire","étagère","tiroir",
  "lampe","lumière","miroir","tableau","tapis","rideau","oreiller","couverture","drap","serviette",
  "savon","brosse","dentifrice","bougie","allumette","balai","aspirateur","seau","éponge",
  "casserole","poêle","assiette","verre","tasse","mug","cuillère","fourchette","couteau",
  "serviette","nappe","plateau","bol","carafe","bouteille","bocal","boîte","sac",

  // Food / drink
  "nourriture","petit-déjeuner","déjeuner","dîner","goûter","repas","plat","menu",
  "pain","beurre","confiture","fromage","jambon","œuf","œufs","lait","yaourt","crème",
  "café","thé","eau","jus","limonade","bière","vin","soda","boisson",
  "pomme","poire","orange","banane","raisin","fraise","citron","melon","ananas",
  "tomate","pomme de terre","oignon","ail","carotte","salade","laitue","concombre","courgette",
  "champignon","maïs","viande","poulet","bœuf","porc","poisson","thon","crevette","saumon",
  "riz","pâtes","spaghetti","soupe","bouillon","sauce","sel","poivre","huile","vinaigre",
  "sucre","miel","chocolat","biscuit","gâteau","tarte","glace",

  // City / places
  "ville","village","rue","avenue","place","parc","marché","magasin","boutique","supermarché",
  "boulangerie","boucherie","pharmacie","librairie","banque","poste","bibliothèque","musée",
  "théâtre","cinéma","restaurant","café","bar","hôtel","hôpital","école","collège","lycée",
  "université","bureau","usine","gare","aéroport","port","plage","montagne","fleuve","rivière",
  "lac","mer","forêt","bois","champ","ferme","église","cathédrale","château","tour","pont",
  "bâtiment","immeuble","quartier",

  // Transport
  "voiture","auto","vélo","bicyclette","moto","bus","autobus","train","métro","tramway","taxi",
  "camion","bateau","avion","hélicoptère","voyage","billet","valise","sac à dos","passeport",
  "carte","plan","arrêt","station","gare","route","autoroute","feu","carrefour",

  // Nature / weather
  "soleil","lune","étoile","ciel","nuage","pluie","neige","vent","glace","orage","tonnerre",
  "chaleur","froid","température","temps","climat","arbre","fleur","plante","feuille","branche",
  "herbe","sable","pierre","roche","terre","animal","chien","chat","oiseau","cheval","vache",
  "cochon","mouton","poule","poisson","souris","mouche","papillon","abeille","araignée",

  // School / work
  "école","classe","cours","leçon","prof","enseignant","élève","étudiant","livre","cahier",
  "stylo","crayon","gomme","règle","tableau","craie","papier","devoir","examen","note","question",
  "réponse","mot","phrase","lettre","chiffre","langue","matière",
  "travail","boulot","bureau","entreprise","patron","collègue","salaire","horaire","réunion",
  "rapport","ordinateur","portable","téléphone","mobile","écran","clavier","imprimante",

  // Verbs (top frequency)
  "être","avoir","aller","faire","venir","voir","entendre","dire","parler","savoir","pouvoir",
  "vouloir","devoir","croire","penser","comprendre","connaître","sembler","paraître",
  "vivre","mourir","naître","grandir","arriver","partir","entrer","sortir","monter","descendre",
  "rester","retourner","quitter",
  "manger","boire","prendre","cuisiner","préparer","servir","acheter","vendre","payer","coûter",
  "ouvrir","fermer","commencer","finir","terminer","travailler","étudier","apprendre","enseigner",
  "lire","écrire","écouter","demander","répondre","raconter","expliquer","aider","chercher",
  "trouver","perdre","gagner","porter","apporter","emporter","mettre","poser","placer","ranger",
  "déplacer","bouger","pousser","tirer","tenir","lâcher","laisser","donner","prendre","recevoir",
  "envoyer","appeler","téléphoner","éteindre","allumer","brancher","débrancher","charger",
  "laver","nettoyer","essuyer","sécher","mouiller","couper","mélanger","chauffer","refroidir",
  "marcher","courir","sauter","nager","danser","chanter","jouer","gagner","perdre","attendre",
  "voyager","visiter","saluer","inviter","accepter","refuser","essayer","réussir","choisir",
  "préférer","décider","oublier","se souvenir","rappeler","aimer","adorer","détester","haïr",
  "vouloir","souhaiter","espérer","sentir","ressentir","respirer","dormir","se réveiller",
  "se lever","s'asseoir","se coucher","s'habiller","se déshabiller","se laver","se doucher",

  // Adjectives
  "bon","mauvais","grand","petit","haut","bas","long","court","large","étroit","gros","mince",
  "neuf","nouveau","vieux","jeune","cher","bon marché","facile","difficile","rapide","lent",
  "fort","faible","dur","mou","propre","sale","plein","vide","ouvert","fermé","chaud","froid",
  "tiède","sec","mouillé","humide","clair","sombre","brillant","heureux","content","triste",
  "fatigué","calme","tranquille","nerveux","gentil","sympathique","poli","timide","courageux",
  "intelligent","bête","beau","joli","laid","moche","riche","pauvre","maigre","gras",
  "rouge","bleu","vert","jaune","blanc","noir","gris","marron","brun","rose","orange","violet",
  "premier","deuxième","troisième","dernier","prochain","suivant",

  // Numbers
  "zéro","un","deux","trois","quatre","cinq","six","sept","huit","neuf","dix","onze","douze",
  "treize","quatorze","quinze","seize","dix-sept","dix-huit","dix-neuf","vingt","trente",
  "quarante","cinquante","soixante","soixante-dix","quatre-vingt","quatre-vingt-dix","cent","mille",

  // Abstract common
  "vie","mort","amour","amitié","bonheur","tristesse","peur","joie","problème","solution","idée",
  "question","réponse","histoire","conte","vérité","mensonge","rêve","plan","voyage","fête",
  "anniversaire","mariage","rendez-vous","appel","santé","maladie","douleur","médecine","sport",
  "musique","art","film","livre","journal","nouvelle","couleur","forme","taille",
];

// Bloque 2, generado desde Lexique383.tsv (ver cabecera). 5245 lemas.
const FRENCH_A1_A2_LEXIQUE: readonly string[] = [
  "abaisser","abandon","abandonné","abandonner","abattre","abbé","abîme","abîmer","abolir",
  "abominable","abord","aborder","aboutir","aboyer","abri","abriter","abruti","absence","absent",
  "absolu","absolument","absorber","abstenir","abstrait","absurde","abus","abuser","académie",
  "accabler","accéder","accélérer","accent","accentuer","accès","accident","accommoder",
  "accompagner","accompli","accomplir","accord","accorder","accoucher","accouder","accourir",
  "accrocher","accroître","accroupir","accueil","accueillir","accumuler","accusation","accusé",
  "accuser","acharner","achat","achever","acide","acier","acquérir","acquiescer","acte","acteur",
  "actif","action","activer","activité","actuel","actuellement","adapter","addition","adieu",
  "adjoint","adjudant","admettre","administratif","administration","admirable","admiration",
  "admirer","adolescence","adolescent","adopter","adorable","adosser","adoucir","adresse",
  "adresser","adulte","advenir","adversaire","aérien","affaiblir","affaire","affairer","affaisser",
  "affaler","affecter","affection","affectueux","affiche","afficher","affirmer","affolé","affoler",
  "affranchir","affreux","affronter","affût","afin de","afin que","africain","agacer","âge","âgé",
  "agence","agenouiller","agent","aggraver","agir","agitation","agité","agiter","agneau","agonie",
  "agrandir","agréable","agresser","agressif","agression","agripper","aide","aïeul","aigle","aigu",
  "aiguille","aile","aimable","aimé","aîné","ainsi","air","aisance","aise","aisément","ajouter",
  "ajuster","alarme","album","alcool","alentour","alerte","alerter","algue","alibi","aligner",
  "alimenter","allée","allégresse","allemand","alliance","allié","allier","allongé","allonger",
  "allumé","allure","allusion","alourdir","altesse","altitude","amant","amateur","ambassade",
  "ambassadeur","ambiance","ambition","ambulance","âme","améliorer","amen","aménager","amende",
  "amener","amer","américain","amertume","amical","amiral","amorcer","amoureux","ample","ampoule",
  "amusant","amuser","analyse","analyser","ancêtre","ancien","andouille","âne","anéantir",
  "anecdote","ange","anglais","angle","angoisse","animé","animer","anneau","annonce","annoncer",
  "annuler","anonyme","anormal","antenne","antérieur","antique","anxiété","anxieux","apaiser",
  "apercevoir","apéritif","aplatir","apparaître","appareil","apparemment","apparence","apparent",
  "apparition","appart","appartenir","appétit","applaudir","applaudissement","application",
  "appliquer","apprécier","apprenti","apprentissage","apprêter","apprivoiser","approbation",
  "approche","approcher","approuver","appui","appuyer","après-demain","arabe","arbitre","arc",
  "arcade","architecte","architecture","archive","ardent","ardeur","ardoise","are","arête","argent",
  "argenté","argile","argument","arme","armé","armée","armement","armer","armistice","armure",
  "arracher","arrangement","arranger","arrestation","arrêté","arrêter","arrière","arrivé","arrivée",
  "arrondir","arroser","artère","article","articuler","artifice","artificiel","artillerie",
  "artisan","artiste","artistique","as","asile","aspect","aspirer","aspirine","assaillir",
  "assassin","assassinat","assassiner","assaut","assemblée","asseoir","assis","assise","assistance",
  "assistant","assister","association","associé","associer","assombrir","assommer","assoupir",
  "assumer","assurance","assuré","assurément","assurer","astiquer","astre","atelier","atmosphère",
  "atomique","atroce","attaché","attachement","attacher","attaque","attaquer","attarder",
  "atteindre","attendrir","attentat","attente","attentif","attention","attentivement","atténuer",
  "atterrir","attirer","attitude","attraction","attraper","attribuer","au-dehors","au-delà",
  "au-dessous","au-dessus","aubain","aube","auberge","aucune","audace","audience","audition",
  "augmenter","auparavant","auprès","auquel","aura","aurore","aussitôt","austère","autant","autel",
  "auteur","authentique","automatique","automobile","autopsie","autorisation","autoriser",
  "autorité","autour","autrefois","autrement","autres","autrichien","autrui","auxquelles",
  "auxquels","avaler","avance","avancé","avancer","avant-bras","avant-hier","avantage","avenir",
  "aventure","aventurer","avérer","averse","avertir","avertissement","aveu","aveugle","aveugler",
  "aviation","avide","avis","aviser","avocat","avouer","axe","azur","baby","bac","bâche","bagage",
  "bagarre","bagnole","baguette","baie","baigner","baignoire","bail","bâiller","bain","baisse",
  "baisser","bal","balade","balader","balance","balancer","balayer","balbutier","baleine","balle",
  "ballet","ballon","banal","banc","bande","bander","bandit","banlieue","banquette","banquier",
  "baptême","baptiser","baraque","barbare","barbe","barbier","barman","baron","barque","barrage",
  "barre","barreau","barrer","barrière","basculer","base","baser","basket","basque","bassin",
  "bataille","bataillon","bâtir","bâton","battant","battement","batterie","battre","battu","bavard",
  "bavardage","bavarder","baver","bazar","beau-frère","beau-père","beauté","bec","bel","ben",
  "bénédiction","bénéfice","bénéficier","bénir","berceau","bercer","béret","berge","berger",
  "besogne","besoin","bétail","bêtement","bêtise","béton","biais","biberon","bible","biche","bide",
  "bidon","bien","bien-aimé","bien-être","bienvenu","bienvenue","bijou","bijoux","bilan","billard",
  "bille","bise","bisou","bistrot","bizarre","bizarrement","blague","blaguer","blâmer","blanche",
  "blancheur","blanchir","blé","bled","blême","blessé","blesser","blessure","blindé","bloc","blond",
  "bloquer","blottir","blouse","blouson","blues","boche","boeuf","boiter","bombardement",
  "bombarder","bombe","bonbon","bond","bondir","bonhomme","bonjour","bonne","bonnet","bonsoir",
  "bonté","bord","border","bordure","borne","borner","boss","bosse","bosser","botter","bouc",
  "bouchée","boucher","bouchon","boucle","boucler","bouclier","bouder","boue","boueux","bouffe",
  "bouffée","bouffer","bouge","bougre","bouillant","bouillie","bouillir","boulanger","boule",
  "boulevard","bouleverser","bouquet","bouquin","bourdonnement","bourg","bourgeois","bourgeoisie",
  "bourreau","bourrer","bourse","bousculer","bousiller","bout","bouton","boxe","boxeur","boy",
  "boyau","bracelet","brailler","braise","brandir","braquer","brave","bravo","brebis","brèche",
  "bredouiller","bref","bretelle","bribe","brigade","brigadier","briller","brin","brique","briquet",
  "brise","brisé","briser","britannique","broder","broncher","bronze","brosser","brouhaha",
  "brouillard","brouiller","broyer","bruit","brûlant","brûlé","brûler","brûlure","brume","brune",
  "brusque","brusquement","brut","brutal","brutalement","brutalité","brute","bruyant","bûche",
  "bûcher","budget","buée","buffet","buisson","bulle","bulletin","bungalow","business","buste",
  "but","buter","by","c'est-à-dire","ça","çà","cabane","cabine","cabinet","câble","caché","cacher",
  "cachet","cachette","cadavre","cadeau","cadence","cadet","cadre","cafard","cage","caillou",
  "caisse","calcul","calculer","caleçon","calendrier","caler","calibre","calmement","calmer",
  "camarade","came","caméra","camionnette","camp","campagne","camper","canal","canard","cancer",
  "candidat","canne","canon","canot","cantine","caoutchouc","cap","capable","capacité","cape",
  "capitaine","capital","capitale","caporal","capote","caprice","capter","capturer","carabine",
  "caractère","caravane","carcasse","cardiaque","caresse","caresser","cargo","carnaval","carnet",
  "carré","carreau","carrelage","carrément","carrière","cartable","carton","cartouche","cas",
  "cascade","case","caser","caserne","casier","casino","casque","casse","cassé","casser","cassette",
  "catastrophe","catégorie","catholique","cauchemar","cause","causer","caution","cavalerie",
  "cavalier","cave","caverne","ceci","céder","cela","célèbre","célébrer","céleste","célibataire",
  "celle","celle-ci","celle-là","celles","celles-ci","cellule","celui","celui-ci","celui-là",
  "cendre","cendrier","censé","centaine","centime","centimètre","central","centrale","centre",
  "cents","cependant","cercle","cercueil","cérébral","cérémonie","cerf","cerise","cerner","certain",
  "certainement","certaines","certains","certes","certificat","certitude","cerveau","cervelle",
  "cesse","cesser","cet","ceux","ceux-ci","ceux-là","chacun","chacune","chagrin","chaîne","chair",
  "châle","chalet","chaleureux","chameau","champagne","champion","chance","chanceux","chandail",
  "chandelle","change","changement","changer","chanoine","chanson","chant","chantage","chanteur",
  "chantier","chantonner","chaos","chapelet","chapelle","chapitre","char","charbon","charge",
  "chargé","chargement","chariot","charité","charmant","charme","charmer","charnel","charrette",
  "charrier","chasse","chasser","chasseur","châtiment","chatouiller","chauffeur","chaussée",
  "chausser","chauve","chef","chef-d'oeuvre","chemin","cheminée","chêne","chèque","chéri","chérir",
  "chevalier","chevaucher","chevelure","chevet","cheville","chèvre","chez","chialer","chic",
  "chiffon","chignon","chimique","chinois","chiotte","chirurgie","chirurgien","choc","choeur",
  "choisi","choix","chômage","choper","choquer","chose","chou","chouette","chrétien","chuchoter",
  "chute","ci","cible","cicatrice","cierge","cieux","cigare","cigarette","cil","ciment","cimetière",
  "ciné","cinglé","cingler","cinquième","circonstance","circuit","circulation","circuler","cire",
  "cirer","cirque","ciseau","citation","cité","citer","citoyen","civil","civilisation","clairement",
  "clairière","clan","clandestin","claque","claquement","claquer","clarté","classer","classique",
  "clé","clef","cliché","client","clientèle","cligner","clin","clinique","clochard","cloche",
  "clocher","cloison","clope","clore","clos","clôture","clou","clouer","club","coca","cocktail",
  "coco","code","coeur","coffre","cognac","cogner","coiffer","coiffeur","coiffure","coin","coincer",
  "coïncidence","coke","col","colère","colis","collaborateur","collaboration","collaborer","colle",
  "collectif","collection","coller","collier","colline","colombe","colonel","colonial","colonie",
  "colonne","com","coma","combat","combattant","combattre","combien","combinaison","combine",
  "comble","combler","comédie","comédien","comique","comité","commandant","commande","commandement",
  "commander","commando","comme","commencement","comment","commentaire","commenter","commerçant",
  "commerce","commercial","commettre","commis","commissaire","commissariat","commission","commode",
  "commun","communauté","commune","communication","communion","communiqué","communiquer",
  "communisme","communiste","compagnie","compagnon","comparaison","comparer","compartiment",
  "compassion","compatriote","compenser","compétition","complaisance","complet","complètement",
  "compléter","complexe","complication","complice","complicité","compliment","compliqué",
  "compliquer","complot","comportement","comporter","composer","composition","compréhension",
  "compris","compromettre","compte","compter","comptoir","comte","comté","concentration",
  "concentrer","conception","concernant","concerner","concert","concession","concevoir","concierge",
  "conclure","conclusion","concours","condamnation","condamné","condamner","condition",
  "condoléance","conducteur","conduire","conduite","conférence","conférer","confesser","confession",
  "confiance","confiant","confidence","confidentiel","confier","confirmer","conflit","confondre",
  "conforme","confort","confortable","confrère","confronter","confus","confusion","congé","congrès",
  "conjugal","conjurer","connaissance","connu","conquérir","conquête","consacrer","conscience",
  "conscient","conseil","conseiller","consentir","conséquence","conséquent","conserve","conserver",
  "considérable","considération","considérer","consigne","consister","consolation","consoler",
  "consommation","consommer","constamment","constant","constater","constituer","constitution",
  "construction","construire","consul","consultation","consulter","consumer","contact","contacter",
  "contaminer","contempler","contenir","contenter","contenu","conter","contester","continent",
  "continu","continue","continuer","contour","contourner","contracter","contradiction",
  "contraindre","contraire","contrairement","contrarier","contraste","contrat","contredire",
  "contrer","contribuer","contrôle","contrôler","contrôleur","convaincre","convaincu","convenable",
  "convenir","convention","conversation","convertir","conviction","convoi","convoquer","cool",
  "coopération","coopérer","copie","copier","coq","coque","coquillage","coquille","corbeau",
  "corbeille","corde","cordon","corne","correct","correctement","correction","correspondance",
  "correspondre","corridor","corriger","corsage","cortège","corvée","costaud","costume","cote",
  "côte","côté","coton","couche","couché","coucher","coucou","coude","coudre","couler","coulisse",
  "coup","coupable","coupe","coupé","couple","coupure","cour","courage","courant","courbe",
  "courber","coureur","couronne","couronner","courrier","course","courtoisie","coussin","coutume",
  "couture","couturier","couvent","couver","couvercle","couvert","couvrir","crabe","cracher",
  "craindre","crainte","cramponner","cran","crâne","crapaud","craquement","craquer","crasse",
  "crasseux","créateur","création","créature","crèche","crédit","créer","crêpe","crépuscule",
  "crête","crétin","creuser","creux","crever","cri","crier","crime","criminel","crinière","crise",
  "crisper","crisser","cristal","critique","critiquer","crochet","crocodile","croisé","croiser",
  "croissant","croître","croix","croquer","crosse","crotte","croupe","croûte","croyance","cru",
  "cruauté","cruel","cube","cueillir","cuiller","cuir","cuire","cuisinier","cuisse","cuit","cuivre",
  "culot","culotte","culpabilité","culte","cultiver","culture","culturel","cure","curé",
  "curieusement","curieux","curiosité","cuvette","cycle","cygne","d'","d'abord","d'autres",
  "daigner","dalle","dame","damer","damoiseau","danger","dangereux","danse","danseur","date",
  "dater","dauphin","davantage","dé","dealer","débarquement","débarquer","débarrasser","débat",
  "débattre","débauche","débile","débiter","déborder","déboucher","debout","débris","débrouiller",
  "début","débuter","déceler","déception","décès","décevoir","déchaîner","décharge","décharger",
  "déchet","déchiffrer","déchiré","déchirer","décidé","décidément","décisif","décision",
  "déclaration","déclarer","déclencher","décliner","décoller","déconner","décor","décoration",
  "décorer","découper","décourager","découvert","découverte","découvrir","décret","décréter",
  "décrire","décrocher","déçu","dédaigner","dédier","déduire","déesse","défaire","défaite","défaut",
  "défendre","défense","déferler","défi","défier","défilé","défiler","définir","définitif",
  "définition","définitivement","défoncer","déformer","défunt","dégager","dégât","dégoût",
  "dégoûtant","dégoûter","degré","dégringoler","dégueulasse","déguiser","déguster","delà","délai",
  "délégation","délégué","délicat","délicatesse","délice","délicieux","délire","délirer","délit",
  "délivrer","demande","démarche","démarrer","déménager","demeure","demeurer","demi","demi-heure",
  "demi-tour","démission","démissionner","démocratie","démolir","démon","démonstration","démonter",
  "démontrer","dénicher","dénoncer","dénouer","dense","dentelle","dentiste","départ","département",
  "dépasser","dépêche","dépêcher","dépendre","dépense","dépenser","dépit","déplacement","déplaire",
  "déplier","déployer","déposer","déposition","dépôt","dépouiller","dépourvoir","dépression",
  "déprimer","député","déranger","déraper","dérisoire","dériver","dernièrement","dérober",
  "dérouler","dès","désagréable","désarmer","désarroi","désastre","descente","description","désert",
  "déserter","désespéré","désespérément","désespérer","désespoir","déshabiller","déshonorer",
  "désigner","désir","désirer","désolé","désoler","désordre","désormais","dessécher","dessein",
  "desserrer","dessert","dessin","dessiner","dessous","dessus","destin","destination","destinée",
  "destiner","destruction","détaché","détachement","détacher","détail","détailler","détecter",
  "détective","détendre","détenir","détente","détenu","déterminer","détour","détourner","détresse",
  "détruire","dette","deuil","dévaler","développement","développer","devenir","déverser","deviner",
  "dévisager","devise","dévoiler","dévorer","dévouement","diable","diabolique","dialogue","diamant",
  "dicter","dictionnaire","dieu","différemment","différence","différent","différer","difficilement",
  "difficulté","diffuser","digérer","digne","dignité","dimension","diminuer","dinde","dingue",
  "diplomate","diplomatique","diplôme","direct","directement","directeur","direction","dirigeant",
  "diriger","discerner","disciple","discipline","discours","discret","discrètement","discrétion",
  "discussion","discuter","disparaître","disparition","disparu","dispenser","disperser",
  "disponible","disposer","disposition","dispute","disputer","disque","dissimuler","dissiper",
  "dissoudre","distance","distinction","distingué","distinguer","distraction","distraire",
  "distrait","distraitement","distribuer","distribution","dit","divan","divers","divin","diviser",
  "division","divorce","divorcer","dizaine","do","docteur","document","dollar","domaine",
  "domestique","domicile","dominer","dommage","don","donne","donné","donnée","donneur","dont",
  "doré","dorénavant","dorer","dortoir","dose","dossier","doter","douane","double","doubler",
  "doucement","douceur","douche","doué","douer","douloureux","doute","douter","douteux","doux",
  "douzaine","dragon","draguer","dramatique","drame","drapeau","dressé","dresser","drifter",
  "drogue","droguer","droit","droite","drôle","drôlement","duc","duel","dune","duquel","durant",
  "durcir","durée","durement","durer","dureté","éblouir","éblouissant","ébranler","écaille","écart",
  "écarté","écarter","échange","échanger","échantillon","échapper","échec","échelle","écho",
  "échouer","éclair","éclairage","éclaircir","éclairé","éclairer","éclat","éclatant","éclater",
  "éclipser","écolier","économie","économique","économiser","écorce","écouler","écoute","écrasé",
  "écraser","écrier","écrit","écriture","écrivain","écrouler","écume","écureuil","écurie","édifice",
  "édifier","éditeur","édition","éducation","effacer","effectivement","effectuer","effet",
  "efficace","effleurer","effondrer","efforcer","effort","effrayant","effrayé","effrayer","effroi",
  "effroyable","égal","également","égalité","égard","égaré","égarer","égoïste","égorger","égout",
  "égyptien","élan","élancer","élargir","élection","électricité","électrique","élégance","élégant",
  "élément","élémentaire","éléphant","élevé","élever","éliminer","élire","élite","elle-même",
  "elles-mêmes","éloigné","éloigner","émaner","emballer","embarquer","embarras","embarrasser",
  "embaucher","embêter","embrasser","embrouille","embrouiller","émerger","émerveiller","émettre",
  "émeute","émission","emménager","emmener","émotion","émouvant","émouvoir","emparer","empêcher",
  "empereur","empiler","empire","empirer","emplacement","emplir","emploi","employé","employer",
  "empoigner","empoisonner","empreinte","empresser","emprisonner","emprunter","ému","encadrer",
  "encaisser","enceinte","encercler","enchaîner","enchanté","enchanter","encombrer","encourager",
  "encre","endormi","endormir","endroit","endurer","énergie","énerver","enfance","enfantin","enfer",
  "enfermer","enfiler","enfin","enflammer","enfler","enfoiré","enfoncer","enfouir","enfuir",
  "engagement","engager","engendrer","engin","engloutir","engouffrer","engueuler","énigme",
  "enjamber","enlacer","enlèvement","enlever","ennemi","ennui","ennuyer","ennuyeux","énorme",
  "énormément","enquête","enquêter","enrager","enregistrement","enregistrer","enrichir","enrouler",
  "enseigne","enseignement","ensemble","entamer","entasser","entendu","entente","enterrement",
  "enterrer","enthousiasme","entier","entièrement","entourage","entourer","entrailles",
  "entraînement","entraîner","entraîneur","entraver","entrée","entrepôt","entreprendre",
  "entretenir","entretien","entrevoir","entrevue","entrouvrir","envahir","enveloppe","envelopper",
  "envers","envie","envier","environ","environnement","envisager","envoler","épais","épaisseur",
  "épanouir","épargner","éparpiller","épatant","épater","épave","épée","épicerie","épicier",
  "épidémie","épier","épine","épingle","épisode","éplucher","époque","épouser","épouvantable",
  "épreuve","éprouver","épuisé","épuiser","équilibre","équipage","équipe","équipement","équiper",
  "ère","érotique","errant","errer","erreur","escadron","escalader","escargot","esclavage",
  "esclave","escorte","escorter","escroc","espace","espagnol","espèce","espérance","espion",
  "espionner","espoir","esprit","esquisser","esquiver","essai","essence","essentiel","est",
  "est-ce que","estime","estimer","estrade","étable","établir","établissement","étage","étalage",
  "étaler","étang","étape","état","état-major","etc","éteint","étendre","étendue","éternel",
  "éternellement","éternité","étincelant","étincelle","étiquette","étirer","étoffe","étonnant",
  "étonné","étonnement","étonner","étouffer","étrange","étrangement","étranger","étrangler",
  "étreindre","étreinte","étroitement","étude","européen","eux","eux-mêmes","évacuer","évader",
  "évaluer","évanouir","évasion","ève","éveiller","événement","éventail","éventuel","évêque",
  "évidemment","évidence","évident","évier","éviter","évoluer","évolution","évoquer","exact",
  "exactement","exagérer","exaltation","exalter","examiner","exaspérer","excellence","excellent",
  "exception","exceptionnel","excès","excessif","excitant","excitation","excité","exciter",
  "exclamation","exclamer","exclure","exclusivement","excuse","excuser","exécuter","exécution",
  "exemplaire","exemple","exercer","exercice","exhiber","exigence","exiger","exil","existence",
  "exister","exotique","expédier","expédition","expérience","expert","explication","exploit",
  "exploiter","explorer","exploser","explosif","explosion","exposer","exposition","exprès",
  "expression","exprimer","expulser","exquis","extase","extérieur","extraire","extraordinaire",
  "extrême","extrêmement","extrémité","fable","fabrique","fabriquer","fabuleux","fac","façade",
  "face","fâché","fâcher","fâcheux","facilement","facilité","faciliter","façon","facteur","facture",
  "faculté","fade","faiblement","faiblesse","faille","faillir","faillite","faim","fait","faîte",
  "falaise","falloir","fameux","familial","familier","fan","fantaisie","fantasme","fantastique",
  "fantôme","farce","farcir","fardeau","farine","farouche","fascinant","fasciner","fatal",
  "fatigant","fatigue","fatiguer","faubourg","faucher","faufiler","faute","fauve","faux","faveur",
  "favorable","favori","favoriser","fédéral","fée","feindre","félicitation","féliciter","femelle",
  "féminin","fendre","fente","fer","fermement","fermeté","fermeture","fermier","féroce","ferraille",
  "ferveur","fesse","festival","fêter","feuillage","feuilleter","feutre","fiançailles","fiancé",
  "fiancer","fibre","ficelle","fiche","ficher","fichier","fichu","fidèle","fidélité","fier",
  "fierté","fièvre","fiévreux","figé","figer","figurer","fil","file","filer","filet","fillette",
  "filmer","filtrer","fin","final","finalement","finance","financer","financier","fini","fiston",
  "fixe","fixer","flacon","flairer","flamber","flamme","flanc","flanquer","flaque","flash",
  "flatter","flèche","fleurir","fleuriste","flic","flingue","flinguer","flipper","flot","flottant",
  "flotte","flotter","flou","flûte","foi","foie","foin","foire","foirer","fois","folie","foncé",
  "foncer","fonction","fonctionnaire","fonctionner","fond","fondamental","fondation","fonder",
  "fondre","fonds","fontaine","foot","football","for","force","forcé","forcément","forcer","forger",
  "formalité","formation","formel","former","formidable","formule","formuler","fortement",
  "forteresse","fortune","fosse","fossé","fou","foudre","fouet","fouetter","fouille","fouiller",
  "foulard","foule","fouler","four","fourgon","fourmi","fourneau","fournir","fourré","fourrer",
  "fourrure","foutu","foyer","fracas","fraction","fragile","fragment","fraîcheur","frais","franc",
  "français","franchement","franchir","franchise","frange","frangin","frappe","frapper","fraternel",
  "frayer","frein","freiner","frêle","frémir","fréquence","fréquent","fréquenter","fric","frigo",
  "fringue","frisé","frisson","frissonner","frite","froc","froisser","frôler","froncer","front",
  "frontière","frotter","fruit","führer","fuir","fuite","fumant","fumé","fumée","fumer","fumier",
  "funèbre","funérailles","fur et à mesure","fureur","furieux","furtif","fusée","fusil","fusillade",
  "fusiller","fusion","fût","futur","gâcher","gaffe","gage","gagnant","gai","gaiement","gaieté",
  "gaillard","galaxie","galer","galerie","galet","galon","galop","galoper","gamelle","gamin","gang",
  "gangster","garage","garantie","garantir","garde","garder","gardien","garer","garnir","garnison",
  "gars","gaspiller","gâter","gauche","gaver","gay","gaz","géant","geler","gémir","gémissement",
  "gênant","gendarme","gendarmerie","gendre","gêne","gêné","gêner","général","généralement",
  "génération","généreux","générosité","génial","génie","genre","gentillesse","gentiment",
  "gentleman","gérant","gerbe","gerber","gérer","gésir","geste","gibier","gifle","gifler",
  "gigantesque","gilet","girl","gitan","glacé","glacer","glacial","glaçon","glisser","globe",
  "gloire","glorieux","gluant","go","golf","gonflé","gonfler","gonzesse","gorge","gorgée","gosse",
  "gouffre","gourmand","goût","goutte","gouttière","gouvernement","gouverner","gouverneur","grâce",
  "gracieux","grade","grain","graine","graisse","grand-chose","grandeur","grandiose",
  "grands-parents","grange","grappe","gratitude","gratter","gratuit","grave","gravement","graver",
  "gravier","gravir","gravité","gré","grec","grenade","grenier","grenouille","grève","griffe",
  "griffer","grignoter","grillage","grille","griller","grimace","grimacer","grimper","grincer",
  "grippe","grisâtre","grogner","grommeler","grondement","gronder","grossier","grossir","grotesque",
  "grotte","grouiller","groupe","grouper","guère","guérir","guerre","guerrier","guetter","gueule",
  "gueuler","guichet","guide","guider","guise","guitare","gymnastique","ha","habile","habileté",
  "habillé","habiller","habit","habitant","habiter","habitude","habitué","habituel","habituer",
  "hache","hagard","haie","haine","haleine","haleter","hall","hallucination","halte","hanche",
  "hangar","hanter","harceler","hardi","harem","haricot","harmonie","hasard","hâte","hâter",
  "hausser","hauteur","héberger","hémorragie","hérétique","hérisser","héritage","hériter",
  "héritier","héroïque","héros","hésitant","hésitation","hésiter","heureusement","heurter","hideux",
  "hiérarchie","hippo","hisser","historique","hocher","homicide","hommage","honnête","honnêtement",
  "honnêteté","honneur","honorable","honorer","honte","honteux","horizon","horloge","horreur",
  "horrible","hors","hostile","hostilité","hôte","hôtesse","humain","humanité","humble","humeur",
  "humidité","humiliation","humilier","humilité","humour","hurlement","hurler","hymne","hypothèse",
  "idéal","identifier","identique","identité","idiot","idole","ignoble","ignorance","ignorer","île",
  "illégal","illuminer","illusion","illustre","illustrer","image","imaginaire","imagination",
  "imaginer","imbécile","imiter","immédiat","immédiatement","immense","imminent","immobile",
  "immobiliser","immobilité","immortel","impasse","impassible","impatience","impatient",
  "impatienter","impeccable","imperceptible","impérial","impérieux","imperméable","impitoyable",
  "implacable","impliquer","implorer","importance","important","importer","imposer","impossible",
  "impôt","imprégner","impression","impressionnant","impressionner","imprévisible","imprimer",
  "improviser","impuissance","impuissant","impulsion","in","inaccessible","inattendu","incapable",
  "incarner","incendie","incertain","incertitude","incessant","incident","inciter","incliner",
  "incompréhensible","inconnu","inconscient","inconvénient","incroyable","incruster","indécis",
  "indéfiniment","indépendance","indépendant","index","indication","indice","indien","indifférence",
  "indifférent","indignation","indigne","indigner","indiquer","indiscret","indispensable",
  "individu","indulgence","industrie","industriel","inerte","inévitable","infâme","infanterie",
  "infecter","infection","inférieur","infernal","infiltrer","infime","infini","infiniment",
  "infirmerie","infirmier","infliger","influence","influencer","info","information","informer",
  "ingénieur","ingrat","inhabituel","inhumain","initiative","initier","injure","injuste",
  "injustice","innocence","innocent","innombrable","inoffensif","inonder","inoubliable","inouï",
  "inquiet","inquiétant","inquiéter","inquiétude","inscription","inscrire","insecte","insensé",
  "insensible","insignifiant","insinuer","insistance","insister","insolence","insolent","insolite",
  "inspecter","inspecteur","inspection","inspiration","inspirer","installation","installer",
  "instinct","instituteur","institution","instruction","instruire","instrument","insu","insulte",
  "insulter","insupportable","intact","intégrer","intellectuel","intelligence","intense",
  "intensité","intention","interdire","interdit","intéressant","intéressé","intéresser","intérêt",
  "intérieur","interlocuteur","interminable","international","interne","interpeller",
  "interprétation","interprète","interpréter","interrogatoire","interroger","interrompre",
  "intervalle","intervenir","intervention","intime","intimider","intimité","intituler",
  "intolérable","intrigue","intriguer","introduire","intuition","inutile","invasion","inventer",
  "invention","inverse","inverser","investir","invisible","invitation","invité","invoquer","ironie",
  "ironique","irréel","irrésistible","irriter","irruption","isolé","isolement","isoler","issu",
  "issue","italien","itinéraire","ivre","ivresse","ivrogne","jadis","jaillir","jalousie","jaloux",
  "japonais","jardinier","jazz","jean","jet","jeter","jeton","jeu","jeunesse","job","joindre",
  "joint","joue","jouet","joueur","jouir","jouissance","journaliste","journée","joyeux",
  "judiciaire","juge","jugement","juger","juif","jumeau","jumelle","jument","jungle","juré","jurer",
  "jury","jusque","jusque-là","juste","justement","justice","justifier","képi","kid","kidnapper",
  "kilo","kilomètre","kiosque","l'","l'un","l'une","la plupart","la plupart des","la plupart du",
  "là-dedans","là-dessus","là-haut","labeur","labo","laboratoire","labyrinthe","lacet","lâche",
  "lâcheté","lacs","lady","laine","laisse","lambeau","lame","lamentable","lance","lancer","lande",
  "langage","lanterne","lapin","laquelle","lard","largement","largeur","larguer","larme","las",
  "lasser","lassitude","latin","lavabo","leader","lécher","lecteur","lecture","légal","légende",
  "léger","légèrement","légèreté","légion","légitime","légume","lendemain","lentement","lenteur",
  "lentille","lequel","lesquelles","lesquels","lessive","levé","lever","lézard","liaison","liasse",
  "libération","libéré","libérer","liberté","libre","librement","licence","lien","lier","lieu",
  "lieue","lieutenant","ligne","limite","limiter","limpide","linge","lion","liquide","liquider",
  "lis","lisière","lisse","lisser","liste","litre","littéraire","littéralement","littérature",
  "livraison","livrer","local","localiser","locataire","locomotive","loge","logement","loger",
  "logique","logis","loi","lointain","loisir","longer","longtemps","longue","longuement","longueur",
  "look","lors","lot","louche","louer","loulou","loup","louper","lourd","lourdement","lover",
  "loyal","loyauté","loyer","lucide","lucidité","lueur","lugubre","lui-même","luire","luisant",
  "lumineux","lunette","lustre","lutte","lutter","luxe","lycéen","ma","mâcher","machin",
  "machinalement","machine","mâchoire","mafia","magazine","magicien","magie","magique","magnifique",
  "maigrir","maillot","maintenir","maintes","maintien","maire","mairie","maître","maîtresse",
  "maîtriser","majesté","majestueux","majeur","major","majorité","mal","malade","maladroit",
  "malaise","mâle","malédiction","malentendu","malgré","malheur","malheureusement","malheureux",
  "malice","malin","malle","mallette","malsain","mamie","man","manche","mandat","manège","manie",
  "manier","manière","manifestation","manifestement","manifester","manipuler","manivelle",
  "mannequin","manoeuvre","manoeuvrer","manoir","manque","manquer","manuel","manuscrit","maquereau",
  "maquillage","maquiller","maquis","marais","marbre","marchand","marchandise","marche","mare",
  "maréchal","marée","marge","marié","marier","marin","marine","mark","marmite","marmonner",
  "marque","marquer","marquis","marrant","marre","marrer","marteau","martial","martyr","masculin",
  "masque","masquer","massacre","massacrer","massage","masse","masser","massif","mat","match",
  "matelot","mater","matériel","maternel","maths","matinal","matinée","maudire","maudit","mauve",
  "maximum","mec","mécanicien","mécanique","mécanisme","méchanceté","méchant","mèche","mécontent",
  "médaille","médecin","médical","médicament","médiocre","méditation","méditer","méfiance",
  "méfiant","méfier","mégot","meilleur","mélancolie","mélancolique","mélange","mêler","membre",
  "mémé","mêmes","mémoire","menaçant","menace","menacer","ménage","ménager","mendiant","mener",
  "menotte","mental","menteur","menthe","mentionner","mentir","menton","mépris","mépriser","merci",
  "merder","mérite","mériter","merveille","merveilleux","message","messager","messe","mesure",
  "mesurer","métal","métallique","métamorphose","méthode","métier","mètre","mets","metteur",
  "meuble","meurtre","meurtrier","mi","mi-voix","micro","midi","mien","mienne","miennes","miens",
  "miette","mieux","mignon","migraine","mijoter","milieu","militaire","militant","milliard",
  "millier","million","minable","mine","miner","minéral","minet","mineur","miniature","minimum",
  "ministère","ministre","minuit","minuscule","miracle","miraculeux","mis","mise","miser",
  "misérable","misère","miséricorde","miss","missile","mission","mitraillette","mitrailleur","mlle",
  "mme","mobiliser","mode","modèle","moderne","modeste","modestie","modifier","moeurs","moi",
  "moi-même","moindre","moine","moineau","moins","moite","moitié","mollet","môme","monastère",
  "mondain","monde","mondial","monnaie","monotone","monseigneur","monstre","monstrueux","mont",
  "montant","monté","montée","montrer","monture","monument","monumental","moquer","moquette",
  "moral","morale","morceau","mordre","morgue","morne","morsure","mortel","moteur","motif",
  "mouchoir","moue","mouette","moule","moulin","mourant","mousse","mousson","moustache","moustique",
  "mouvant","mouvement","mouvoir","moyen","moyenne","muet","mule","multicolore","multiple",
  "multiplier","municipal","munir","munition","mûr","muraille","murmure","murmurer","muscle",
  "museau","musette","musical","musicien","musulman","mystère","mystérieux","mystique","mythe",
  "naguère","naïf","nain","naissance","nan","nana","narine","natal","nation","national","nature",
  "naturel","naturellement","naufrage","nausée","naval","navette","naviguer","navire","navré",
  "navrer","nazi","néanmoins","néant","nécessaire","nécessité","négatif","négliger","négociation",
  "négocier","nègre","néon","nerf","net","nettement","nettoyage","neutre","neveu","ni","nichon",
  "nid","nièce","nier","niveau","noble","noblesse","noce","nocturne","noeud","noircir","noix","nom",
  "nombre","nombreux","nommer","nonne","nord","normal","normalement","nostalgie","notaire",
  "notamment","noter","notion","nôtre","nôtres","nouer","nourrice","nourrir","nous-mêmes",
  "nouveauté","nouvel","noyau","noyer","nu","nuance","nucléaire","nudité","nuire","nul","nulle",
  "nullement","numéro","nuque","obéir","objectif","objection","objet","obligation","obligatoire",
  "obligé","obliger","oblique","obscène","obscur","obscurité","obséder","observation","observer",
  "obsession","obstacle","obstination","obstiner","obtenir","obus","occasion","occidental",
  "occupant","occupation","occupé","occuper","océan","odeur","odieux","oeil","oeuf","oeuvre",
  "offenser","offensive","office","officiel","officiellement","officier","offre","offrir","oh",
  "oie","ok","olive","olivier","ombre","omelette","onde","onduler","opaque","opéra","opération",
  "opérer","opinion","opportunité","opposé","opposer","opposition","option","or","orbite",
  "orchestre","ordinaire","ordonnance","ordonner","ordre","ordure","organe","organisation",
  "organisé","organiser","organisme","orgueil","oriental","orienter","original","origine","orner",
  "orphelin","orteil","osciller","oser","osier","otage","ôter","où","ouais","oubli","oublie",
  "oublié","ouest","ours","outil","outre","ouverture","ouvrage","ouvrier","ovale","oxygène","pacha",
  "pacte","page","paille","paire","paisible","paix","palace","palais","pâle","palier","pâlir",
  "palmier","palper","pan","pancarte","panier","panique","paniquer","panne","panneau","pansement",
  "pape","paquet","par","par-ci","par-dessus","parade","paradis","parallèle","paralyser","parapet",
  "parapluie","parasite","parcelle","parcourir","parcours","pardon","pardonner","pareil","parent",
  "parer","paresse","paresseux","parfaire","parfait","parfaitement","parfum","parfumé","pari",
  "parier","parisien","parking","paroi","paroisse","parole","parquet","parrain","pars","part",
  "partage","partager","partenaire","parti","participer","particulier","particulièrement","partie",
  "partisan","parvenir","pascal","passage","passager","passant","passe","passé","passer",
  "passerelle","passion","passionnant","passionné","passionner","pasteur","patate","pâte","pâté",
  "paternel","pathétique","patiemment","patience","patient","patienter","pâtisserie","patrie",
  "patrouille","patte","paume","paumer","paupière","pause","pauvreté","pavé","pavillon","paye",
  "payé","pays","paysage","paysan","péché","pêche","pécher","pêcher","pécheur","pêcheur","pédal",
  "peigne","peignoir","peinard","peindre","peine","peiner","peint","peintre","peinture","pèlerin",
  "pelle","pellicule","peloton","pelouse","penché","pencher","pendre","pendule","pénétrer",
  "pénible","pénombre","pensée","pension","pensionnaire","pente","pépé","percer","percevoir",
  "perche","percher","perdu","perfection","péril","période","périr","perle","permanence",
  "permanent","permettre","permis","permission","perpétuel","perplexe","perron","perroquet",
  "perruque","persister","personnage","personnalité","personnel","personnellement","perspective",
  "persuader","perte","perturber","pesant","peser","peste","pétard","péter","petit-fils","pétrin",
  "pétrir","pétrole","peuple","peupler","phare","phase","phénomène","philosophe","philosophie",
  "photo","photographe","photographie","photographier","physique","physiquement","piano","piaule",
  "pic","pièce","piège","piéger","piétiner","pieux","pige","pigeon","piger","pignon","pile",
  "pilier","piller","pilote","piloter","pilule","pin","pince","pinceau","pincer","pionnier","pipe",
  "piper","pipi","pique","piquer","piquet","piqûre","pirate","pire","pis","piscine","pisser",
  "piste","pistolet","pitié","pitoyable","pizza","placard","placé","plaider","plaie","plaindre",
  "plaine","plainte","plaire","plaisant","plaisanter","plaisanterie","plaisir","planche","plancher",
  "planer","planète","planque","planquer","planter","plaque","plaquer","plastique","platane",
  "plate-forme","plâtre","pleur","pleurer","pleuvoir","pli","plier","plisser","plomb","plongée",
  "plonger","plume","plutôt","pneu","poche","poème","poésie","poète","pogne","pognon","poids",
  "poignard","poignarder","poignée","poignet","poil","poilu","poing","point","pointe","pointer",
  "pointu","pois","poison","poker","police","policier","poliment","polir","politesse","politique",
  "polonais","pommette","pompe","pompier","pondre","populaire","population","porcelaine","porche",
  "portail","portant","portée","porteur","portier","portrait","pose","posé","positif","position",
  "posséder","possession","possibilité","possible","postal","poster","pot","pote","poteau","potion",
  "pou","poubelle","pouce","poudre","pouls","poumon","poupée","pourboire","pourquoi","pourri",
  "pourrir","poursuite","poursuivre","pourtant","pourvoir","pousse","poussée","poussière",
  "poussiéreux","poutre","prairie","pratique","pratiquement","pratiquer","pré","précaution",
  "précédemment","précédent","précéder","prêcher","précieux","précipiter","précis","précisément",
  "préciser","précision","prédire","préférable","préféré","préférence","préfet","préjugé","prénom",
  "préoccupation","préoccuper","préparation","près de","prescrire","présence","présent",
  "présentation","présenter","préserver","président","présider","presque","presse","pressé",
  "pressentiment","pressentir","presser","pression","prestige","présumer","prêt","prétendre",
  "prétention","prêter","prétexte","prêtre","preuve","prévenir","prévoir","prier","prière","prime",
  "primitif","prince","principal","principe","priorité","pris","prise","prison","prisonnier",
  "privé","priver","privilège","prix","pro","probable","probablement","procédé","procéder",
  "procédure","procès","procession","processus","proche","proclamer","procurer","procureur",
  "prodige","prodigieux","prodiguer","producteur","production","produire","produit","professeur",
  "profession","professionnel","profil","profit","profiter","profond","profondément","profondeur",
  "programme","progrès","progresser","proie","projecteur","projet","projeter","prolonger",
  "promenade","promener","promesse","promettre","promis","promotion","prononcer","propagande",
  "propager","prophète","propice","proportion","propos","proposer","proposition","proprement",
  "propriétaire","propriété","prostitué","protecteur","protection","protéger","protestation",
  "protester","prouver","provenir","province","provision","provisoire","provocation","provoquer",
  "proximité","prudemment","prudence","prudent","prunelle","psy","psychiatre","psychiatrique",
  "psychologie","psychologique","puant","puanteur","pub","public","publicité","publier","puce",
  "pudeur","puer","puéril","puiser","puisque","puissance","puissant","puits","punir","punition",
  "pur","purement","pureté","purifier","puzzle","pyramide","qu","quai","qualifier","qualité",
  "quant","quantité","quarantaine","quart","quasi","quasiment","quatrième","que","quel",
  "quelconque","quelle","quelles","quelqu'un","quelques","quelques-uns","quels","querelle",
  "questionner","quête","queue","qui","quiconque","quinzaine","quitte","quoi","quoique","quotidien",
  "rabattre","rabbin","raccompagner","raccrocher","race","racheter","racine","racler","radar",
  "rade","radical","radieux","radio","rafale","rafraîchir","rage","raide","raidir","raie","rail",
  "raison","raisonnable","raisonnement","raisonner","rajeunir","rajouter","ralenti","ralentir",
  "râler","rallier","rallumer","ramasser","rame","ramener","rampe","ramper","rançon","rancune",
  "rang","rangée","rapidement","rapidité","rappel","rapporter","rapprocher","rare","rarement","ras",
  "raser","rasoir","rassemblement","rassembler","rasseoir","rassurant","rassurer","rat","raté",
  "rater","rattacher","rattraper","rauque","ravager","ravi","ravin","ravir","ravissant",
  "ravitaillement","rayer","rayon","rayonner","réaction","réagir","réalisateur","réaliser",
  "réaliste","réalité","réapparaître","rebelle","rebondir","rebord","récemment","récent",
  "réception","recette","réchauffer","recherche","rechercher","récit","réciter","réclamer","recoin",
  "récolte","récolter","recommandation","recommander","recommencer","récompense","récompenser",
  "réconcilier","reconduire","réconforter","reconnaissance","reconnaissant","reconnaître",
  "reconstituer","reconstruire","record","recours","recouvrir","récréation","recroqueviller",
  "recruter","rectangle","rectifier","reçu","recueillir","recul","reculer","récupérer","rédaction",
  "redescendre","redevenir","rédiger","redire","redonner","redoubler","redoutable","redouter",
  "redresser","réduire","réduit","réel","réellement","refaire","référence","refermer","refiler",
  "réfléchi","réfléchir","reflet","refléter","réflexe","réflexion","réforme","refrain","refuge",
  "réfugié","réfugier","refus","regagner","régaler","regard","regarder","régime","régiment",
  "région","registre","règlement","régler","règne","régner","regret","regretter","régulier",
  "régulièrement","rein","reine","rejeter","rejoindre","réjouir","relâcher","relais","relancer",
  "relatif","relation","relativement","relevé","relever","relief","relier","religieux","religion",
  "relire","remarquable","remarque","remarquer","rembourser","remède","remercier","remettre",
  "remise","remonter","remords","remous","rempart","remplacer","rempli","remplir","remporter",
  "remuer","renaissance","renaître","renard","rencard","rencontre","rencontrer","rendormir",
  "rendre","rendu","renforcer","renfort","renier","renifler","renoncer","renouveler",
  "renseignement","renseigner","rentrée","rentrer","renverser","renvoyer","répandre","reparaître",
  "réparation","réparer","reparler","repartir","répartir","repasser","repenser","repentir","repère",
  "repérer","répéter","répétition","répit","replier","réplique","répliquer","replonger","reportage",
  "reporter","repos","reposer","repousser","reprendre","représentant","représentation",
  "représenter","réprimer","reprise","reproche","reprocher","reproduction","reproduire",
  "républicain","république","répugnant","répugner","réputation","requérir","requin","réseau",
  "réserve","réserver","réservoir","résidence","résigner","résistance","résister","résolu",
  "résolution","résonner","résoudre","respect","respectable","respecter","respectueux",
  "respiration","responsabilité","responsable","ressaisir","ressemblance","ressembler","resserrer",
  "ressort","ressortir","ressource","ressusciter","restaurer","reste","résultat","résumer",
  "résurrection","rétablir","retard","retarder","retenir","retentir","retirer","retomber","retour",
  "retrait","retraite","retrouver","réunir","réussi","réussite","revanche","réveil","réveiller",
  "révélation","révéler","revendre","revenir","revenu","rêver","rêverie","revers","revêtir",
  "rêveur","revivre","revoir","révolte","révolter","révolution","révolutionnaire","revolver",
  "revue","rez-de-chaussée","rhabiller","rhum","rhume","ricaner","richesse","ride","ridicule",
  "rigide","rigoler","rigueur","rincer","rire","risque","risquer","rite","rituel","rivage","rival",
  "rive","river","robinet","robot","robuste","roc","rocher","rock","rôder","roi","rôle","romain",
  "roman","romancier","romantique","rompre","ronce","rond","ronde","ronfler","ronger","roseau",
  "rosée","roue","rougir","rouiller","roulant","rouleau","roulement","rouler","roulette","rouquin",
  "routine","rouvrir","roux","royal","royaume","ruban","rude","rudement","ruelle","ruer","ruine",
  "ruiner","ruisseau","ruisseler","rumeur","rupture","ruse","russe","rythme","s'","sa","sabot",
  "sabre","sacré","sacrer","sacrifice","sacrifier","sage","sagesse","saigner","sain","saint",
  "saisir","saison","salé","saler","saleté","salir","salive","salle","saloperie","salut",
  "sang-froid","sanglant","sanglier","sanglot","sangloter","sanguin","saoul","saouler","sapin",
  "sardine","satellite","satisfaction","satisfaire","satisfait","saucisse","sauf","saurer","saut",
  "saute","sauvage","sauver","savant","saveur","savourer","scandale","scandaleux","sceller",
  "scénario","scène","scie","science","scientifique","scier","scintiller","scolaire","scotch",
  "scrupule","scruter","sculpter","sculpture","séance","sécheresse","second","secondaire","secouer",
  "secours","secousse","secret","secrétaire","secrètement","secteur","section","sécurité","séduire",
  "séduisant","seigneur","sein","séjour","selle","selon","semblable","semblant","semelle","semer",
  "sénateur","sens","sensation","sensé","sensibilité","sensible","sensuel","sentence","senteur",
  "sentier","sentiment","sentimental","sentinelle","séparation","séparé","séparer","séquence",
  "sérail","serein","sérénité","sergent","série","sérieusement","sérieux","serment","sermon",
  "serpent","serré","serrer","serrure","servant","serveur","service","serviteur","seuil","seul",
  "seulement","sévère","sexe","sexuel","sexy","shérif","short","siècle","siège","sien","sienne",
  "siennes","siens","sieste","sieur","sifflement","siffler","sifflet","signal","signaler",
  "signature","signe","signer","signification","signifier","silence","silencieusement","silencieux",
  "silhouette","sillage","sillon","simple","simplement","simplicité","sincère","sincèrement",
  "sincérité","singe","singulier","sinistre","sinon","sir","sirène","sirop","site","sitôt",
  "situation","situer","ski","slip","social","socialiste","société","soeur","soi","soi-disant",
  "soi-même","soie","soif","soigner","soigneusement","soin","soirée","soit","solaire","soldat",
  "solde","solennel","solide","solitaire","solitude","solliciter","sombrer","somme","sommeil",
  "sommet","somptueux","songe","songer","sonner","sonnerie","sonnette","sonore","sorcier","sordide",
  "sort","sorte","sortie","sot","sottise","sou","souche","souci","soucier","soucieux","soucoupe",
  "soudain","soudainement","souffle","souffler","souffrance","souffrir","souhait","souiller","soûl",
  "soulagement","soulager","soulever","soulier","souligner","soumettre","soumission","soupçon",
  "soupçonner","souper","soupir","soupirer","souple","source","sourcil","sourd","souriant",
  "sourire","sournois","sous-marin","sous-sol","sous-titrage","sous-titre","soutenir","souterrain",
  "soutien","soutien-gorge","souvenir","souverain","soviétique","soyeux","spatial","spécial",
  "spécialement","spécialiste","spécialité","spectacle","spectateur","sperme","sphère","spirituel",
  "splendeur","splendide","sportif","square","squelette","stable","stade","star","statue","steak",
  "steppe","stérile","stock","stop","stopper","stratégie","stratégique","strict","strictement",
  "structure","studio","stupéfait","stupeur","stupide","style","subir","subit","subitement",
  "sublime","submerger","subsister","substance","subtil","succéder","succès","successif",
  "succession","successivement","succomber","sucer","sucré","sud","suer","sueur","suffire",
  "suffisamment","suffisant","suffoquer","suggérer","suggestion","suicide","suicider","suisse",
  "suite","suivre","sujet","super","superbe","supérieur","supplémentaire","supplice","supplier",
  "supporter","supposer","supprimer","suprême","sûr","sur-le-champ","surcroît","sûreté","surface",
  "surgir","surmonter","surnom","surplus","surprenant","surprendre","surpris","surprise","sursaut",
  "sursauter","surtout","surveillance","surveiller","survenir","survie","survivant","survivre",
  "susceptible","susciter","suspect","suspendre","suspendu","syllabe","symbole","sympa","sympathie",
  "symptôme","syndicat","système","t'","ta","tabac","tabasser","tablette","tablier","tabouret",
  "tache","tâche","tacher","tâcher","tailler","tailleur","taillis","taire","talent","talon","talus",
  "tambour","tampon","tandis que","tank","tant","tantôt","taper","tapir","tapisserie","tapoter",
  "tarder","tardif","taré","tartine","tas","tasser","tâter","tatouage","taule","taureau","taux",
  "team","technique","technologie","teint","teinte","télé","télégramme","téléphonique","télévision",
  "telle","tellement","telles","tels","témoignage","témoigner","témoin","tempe","tempérament",
  "tempête","temple","tenace","tendance","tendre","tendrement","tendresse","tendu","ténèbres",
  "tennis","tension","tentation","tentative","tente","tenter","tenu","tenue","terme","terne",
  "terrain","terrestre","terreur","terrible","terriblement","terrifiant","terrifier","territoire",
  "terroriser","terroriste","test","testament","tester","têtu","texte","thème","théorie","thérapie",
  "thèse","thomas","tic","ticket","tien","tienne","tiens","tiers","tige","tigre","tilleul","timbre",
  "timidité","tinter","tir","tire","tiré","tireur","tisser","tissu","titre","tituber","to","toast",
  "toi","toi-même","toile","toilette","tôle","tolérer","tombe","tombé","tombeau","tombée","tomber",
  "tonne","tonneau","tonton","top","torche","torchon","tordre","tordu","torpeur","torrent","torse",
  "tort","torture","torturer","total","totalement","totalité","toubib","touchant","touche","touché",
  "toucher","touffe","tourbillon","touriste","tourment","tourmenter","tournage","tournant",
  "tournée","tourner","tournoyer","tousser","toutefois","toux","trac","tracasser","trace","tracer",
  "tract","tradition","traditionnel","traduction","traduire","trafic","tragédie","tragique",
  "trahir","trahison","traînée","traîner","trait","traité","traitement","traiter","traître",
  "trajectoire","trajet","tranche","tranchée","trancher","tranquillement","tranquillité",
  "transférer","transfert","transformer","transition","transmettre","transmission","transparence",
  "transparent","transpercer","transpirer","transport","transporter","traquer","travailleur",
  "travers","traversée","traverser","trébucher","tremblant","tremblement","trembler","trempé",
  "tremper","trentaine","trente-cinq","trésor","tressaillir","trêve","triangle","tribu","tribunal",
  "tricher","tricot","tricoter","trinquer","triomphant","triomphe","triompher","tripe","triple",
  "tripoter","tristement","tromper","trompette","tronc","tronche","trône","trotter","trottoir",
  "trou","trouble","troubler","trouer","trouille","troupe","troupeau","trousse","truand","truc",
  "tsar","tube","tué","tuer","tueur","tuile","tumulte","tunnel","turc","tutoyer","tuyau","type",
  "typique","tyran","ultime","unes","uni","uniforme","union","unique","uniquement","unir","unité",
  "univers","universel","uns","urgence","urgent","urine","usage","usé","user","utile","utiliser",
  "vacance","vacarme","vachement","vaciller","vague","vaguement","vaillant","vain","vaincre",
  "vainement","vainqueur","vaisseau","vaisselle","valable","valet","valeur","vallée","valoir",
  "valse","vampire","vanité","vanter","vapeur","variété","vase","vaste","vaurien","vautrer","veau",
  "vedette","véhicule","veille","veiller","veine","velours","vendeur","vengeance","venger","vente",
  "venu","venue","ver","verdict","verger","vérifier","véritable","vermine","vernis","verrou",
  "verrouiller","vers","verser","version","vertical","vertige","vertu","vestiaire","vestibule",
  "veston","vêtir","vêtu","veuf","vexer","vibration","vibrer","vice","vicieux","victime","victoire",
  "victorieux","vidéo","vider","vieil","vieillard","vieillesse","vieillir","vierge","vif","vigne",
  "vigoureux","vigueur","vilain","villa","vingt-cinq","vingt-quatre","vingtaine","viol",
  "violemment","violence","violent","violer","violon","virage","virer","virginie","viril","virus",
  "vis","vis-à-vis","viser","visible","visiblement","vision","visite","visiteur","vital","vite",
  "vitesse","vitre","vitré","vitrine","vivant","vive","vivement","vocabulaire","vocation","vodka",
  "voeu","voici","voie","voilà","voile","voiler","voire","voisinage","voix","vol","volant","volé",
  "volée","voler","volet","voleur","volontaire","volontairement","volonté","volontiers","volume",
  "volupté","vomir","vote","voter","vôtre","vôtres","vouer","voulu","vous-même","voûte","voûté",
  "voyageur","voyant","voyou","vrai","vraiment","vu","vue","vulgaire","vulnérable","wagon","whisky",
  "ya","zèle","zinc","zingaro","zone","zoo",
];

const normalizeOe = (s: string) => s.replace(/œ/g, "oe").replace(/æ/g, "ae");

export const FRENCH_A1_A2_LEMMAS: ReadonlySet<string> = new Set(
  [...FRENCH_A1_A2_ORIGINAL, ...FRENCH_A1_A2_LEXIQUE].map(normalizeOe),
);

export function isFrenchA1A2(word: string): boolean {
  const lemma = normalizeOe(word.toLowerCase().trim()).replace(/’/g, "'");
  if (FRENCH_A1_A2_LEMMAS.has(lemma)) return true;
  // Strip article
  const stripped = lemma.replace(/^(le|la|les|un|une|des|du)\s+/, "").replace(/^l['']/, "");
  if (FRENCH_A1_A2_LEMMAS.has(stripped)) return true;
  // Plural (-s) → singular
  if (lemma.endsWith("s") && FRENCH_A1_A2_LEMMAS.has(lemma.slice(0, -1))) return true;
  return false;
}
