// Spanish B1 lemma list — words that become available at B1 (not
// in A1/A2 but legitimate for intermediate learners). Combined with
// A1+A2 to form the full B1 vocabulary universe via
// `isSpanishUpToLevel(word, "b1")`.

export const SPANISH_B1_LEMMAS: ReadonlySet<string> = new Set([
  // Trabajo / profesiones
  "ingeniero","ingeniera","abogado","abogada","médico","médica","enfermero","enfermera",
  "contador","contadora","arquitecto","arquitecta","periodista","fotógrafo","fotógrafa",
  "diseñador","diseñadora","programador","programadora","empresario","empresaria",
  "vendedor","vendedora","cajero","cajera","mecánico","mecánica","electricista","plomero",
  "carpintero","albañil","jardinero","jardinera","chef","cocinero","cocinera","camarero",
  "camarera","mesero","mesera","recepcionista","secretario","secretaria","gerente",
  "director","directora","jefe","jefa","supervisor","supervisora","asistente","ayudante",
  "becario","becaria","practicante","aprendiz","trabajador","trabajadora",
  "profesión","carrera","puesto","cargo","puesto de trabajo","empleo","ocupación",

  // Emociones / actitudes B1
  "frustración","indignación","melancolía","nostalgia","decepción","desilusión",
  "esperanza","entusiasmo","orgullo","vergüenza","culpa","celos","envidia",
  "compasión","empatía","simpatía","ternura","afecto","admiración","desprecio",
  "irritado","decepcionado","emocionado","ilusionado","frustrado","ofendido","herido",
  "agradecido","arrepentido","avergonzado","celoso","envidioso","resentido",
  "molesto","fastidiado","harto","desesperado","resignado","conforme","inseguro",

  // Opiniones / discurso
  "opinión","perspectiva","punto de vista","argumento","razonamiento","conclusión",
  "debate","discusión","polémica","controversia","acuerdo","desacuerdo","compromiso",
  "ventaja","desventaja","pro","contra","beneficio","perjuicio","riesgo","oportunidad",
  "razón","motivo","causa","consecuencia","resultado","efecto","impacto","influencia",
  "ejemplo","caso","situación","circunstancia","contexto","escenario","entorno",
  "evidencia","prueba","dato","información","estadística","cifra","porcentaje",
  "opinar","argumentar","defender","sostener","afirmar","negar","reconocer","admitir",
  "criticar","cuestionar","dudar","sospechar","confiar","desconfiar","convencer",
  "persuadir","explicar","aclarar","detallar","resumir","concluir","deducir","inferir",

  // Acciones / verbos B1
  "lograr","conseguir","alcanzar","cumplir","realizar","ejecutar","desarrollar",
  "fracasar","fallar","equivocarse","arrepentirse","disculparse","perdonar","aceptar",
  "rechazar","negarse","oponerse","apoyar","colaborar","cooperar","competir",
  "intentar","esforzarse","mejorar","superarse","crecer","progresar","avanzar",
  "retroceder","detenerse","continuar","seguir","persistir","insistir","abandonar",
  "renunciar","ceder","resistir","aguantar","soportar","sobrellevar","enfrentar",
  "afrontar","evitar","esquivar","ignorar","reconocer","identificar","distinguir",
  "comparar","contrastar","relacionar","conectar","unir","separar","dividir","combinar",
  "organizar","planificar","programar","gestionar","administrar","controlar","supervisar",
  "dirigir","liderar","seguir","obedecer","mandar","ordenar","sugerir","recomendar",
  "aconsejar","advertir","prevenir","alertar","informar","comunicar","transmitir",

  // Tecnología
  "tecnología","internet","red","conexión","wifi","datos","archivo","carpeta",
  "documento","programa","aplicación","software","sistema","plataforma","sitio web",
  "página","enlace","contraseña","clave","usuario","cuenta","perfil","mensaje",
  "correo","email","chat","videollamada","reunión virtual","descarga","actualización",
  "instalar","descargar","subir","compartir","publicar","enviar","reenviar","responder",
  "navegar","buscar","encontrar","verificar","confirmar","registrarse","iniciar sesión",
  "cerrar sesión","sincronizar","respaldar","copiar","pegar","borrar","eliminar",
  "tableta","portátil","ratón","teclado","pantalla","auricular","altavoz","micrófono",

  // Conectores / discurso
  "sin embargo","no obstante","aunque","a pesar de","pese a","mientras que","en cambio",
  "por otro lado","por una parte","además","asimismo","también","tampoco","incluso",
  "es decir","o sea","por ejemplo","en concreto","específicamente","en particular",
  "en general","por lo general","habitualmente","normalmente","generalmente","usualmente",
  "por lo tanto","por consiguiente","de modo que","así que","entonces","así pues",
  "en consecuencia","como resultado","dado que","puesto que","ya que","debido a",
  "gracias a","a causa de","por culpa de","en lugar de","en vez de","más bien",
  "en realidad","de hecho","en efecto","ciertamente","desde luego","por supuesto",
  "quizás","probablemente","posiblemente","seguramente","aparentemente","supuestamente",

  // Salud B1
  "tratamiento","diagnóstico","síntoma","prescripción","receta","análisis","examen",
  "cirugía","operación","intervención","terapia","rehabilitación","fisioterapia",
  "consulta","cita","visita médica","emergencia","urgencia","ambulancia","camilla",
  "vendaje","tirita","yeso","muletas","silla de ruedas","prótesis","implante",
  "vacuna","inyección","pastilla","jarabe","crema","pomada","antibiótico","analgésico",
  "presión","colesterol","azúcar en sangre","alergia","intolerancia","contagio",
  "infección","virus","bacteria","epidemia","pandemia",

  // Educación B1
  "asignatura","materia","disciplina","especialidad","carrera","grado","posgrado",
  "máster","maestría","doctorado","tesis","investigación","estudio","análisis",
  "matrícula","beca","préstamo","crédito","título","diploma","certificado",
  "conferencia","seminario","taller","práctica","prácticas","pasantía","intercambio",

  // Sociedad / política básica B1
  "sociedad","comunidad","ciudadano","ciudadanía","derecho","obligación","deber",
  "ley","norma","regla","regulación","legalidad","ilegalidad","justicia","injusticia",
  "votar","votación","elección","candidato","político","partido","gobierno","oposición",
  "presidente","ministro","alcalde","alcaldesa","concejal","diputado","senador",
  "impuesto","contribución","servicio público","educación pública","sanidad","seguridad",
  "policía","bombero","militar","ejército","guerra","paz","conflicto","desacuerdo",

  // Naturaleza / medio ambiente B1
  "ecología","medio ambiente","naturaleza","contaminación","polución","emisión",
  "calentamiento global","cambio climático","reciclaje","reciclar","reducir","reutilizar",
  "energía renovable","energía solar","energía eólica","combustible","gasolina","petróleo",
  "fauna","flora","especie","extinción","conservación","protección","reserva natural",
  "deforestación","incendio forestal","inundación","sequía","desierto","glaciar",

  // Cultura / arte B1
  "cultura","tradición","costumbre","ritual","ceremonia","festival","celebración",
  "carnaval","procesión","desfile","feria","exposición","muestra","galería",
  "artista","pintor","escultor","escritor","poeta","novelista","dramaturgo","cineasta",
  "obra","creación","colección","estilo","corriente","movimiento","tendencia",
  "novela","poesía","drama","comedia","tragedia","ensayo","biografía","autobiografía",
  "personaje","protagonista","antagonista","villano","héroe","heroína","narrador",
  "trama","argumento","clímax","desenlace","capítulo","escena","acto",

  // Comercio / economía B1
  "comercio","economía","mercado","empresa","negocio","corporación","sociedad",
  "accionista","socio","cliente","consumidor","proveedor","cliente","usuario",
  "producto","servicio","oferta","demanda","precio","tarifa","cuota","comisión",
  "factura","recibo","ticket","cuenta","balance","ganancia","pérdida","beneficio",
  "deuda","crédito","préstamo","hipoteca","ahorro","inversión","interés","tasa",

  // Adjetivos B1
  "complicado","complejo","sencillo","simple","obvio","evidente","claro","confuso",
  "ambiguo","preciso","vago","exacto","aproximado","detallado","general","específico",
  "esencial","fundamental","básico","secundario","principal","primario","importante",
  "trascendente","relevante","irrelevante","significativo","insignificante","crucial",
  "frecuente","común","raro","extraño","habitual","inusual","típico","atípico",
  "habitual","tradicional","convencional","moderno","contemporáneo","actual","reciente",
  "antiguo","ancestral","histórico","clásico","moderno","futurista","innovador",
  "creativo","original","auténtico","genuino","falso","artificial","imitación","réplica",
  "honesto","sincero","franco","abierto","reservado","tímido","extrovertido","introvertido",
  "responsable","irresponsable","cuidadoso","descuidado","atento","distraído",
  "eficiente","ineficiente","productivo","improductivo","útil","inútil","práctico",
  "imprudente","prudente","sensato","insensato","razonable","irrazonable","lógico",

  // === EXPANSIÓN B1 (cobertura ampliada) ===

  // Verbos B1 adicionales
  "acercar","alejarse","apoyar","aprovechar","arreglar","atrapar","atreverse","aumentar","averiguar","ayudar",
  "calmarse","cansarse","captar","caer","caracterizar","cargar","celebrar","clasificar","colgar","comparar",
  "comprometer","conectar","construir","contagiar","contar","contener","contribuir","convertir","convivir","copiar",
  "corregir","cortar","crear","crecer","cruzar","cubrir","cuidarse","curar","dar","darse",
  "deberse","decidir","declarar","dejar","demostrar","derrotar","desaparecer","descansar","descender","describir",
  "desear","despedirse","destruir","detener","determinar","diferenciarse","difundir","dirigirse","discutir","diseñar",
  "disminuir","disponer","disputar","distribuir","divertir","dividir","dormirse","ejecutar","elaborar","elevar",
  "emocionar","empezar","emplear","enamorarse","encantar","encargar","encerrar","encontrarse","enfadarse","enfocar",
  "engañar","enseñar","entender","enterarse","entrenar","entrevistar","enviar","equilibrar","equivocar","escoger",
  "escribir","esforzarse","esperar","establecer","estallar","estirar","evaluar","exhibir","experimentar","explotar",
  "exportar","expresar","extender","fabricar","facilitar","fallecer","faltar","felicitar","figurar","finalizar",
  "florecer","formar","forzar","fracasar","fumar","funcionar","ganar","garantizar","generar","grabar",
  "guiar","habitar","heredar","herir","huir","ignorar","ilustrar","importar","impresionar","incluir",
  "incorporar","indicar","influir","informar","ingresar","iniciar","inscribir","insistir","instalar","integrar",
  "intentar","interrumpir","interpretar","intervenir","investigar","invitar","ir","irse","jugar","juntarse",
  "lanzar","leer","liberar","limitar","limpiar","llenar","llevar","luchar","manejar","manifestar",
  "marcar","mejorar","memorizar","mentir","meter","mezclar","mirar","modificar","mojarse","montar",
  "morir","mostrar","mudarse","multiplicar","negociar","obedecer","observar","obligar","ocupar","ocurrir",
  "odiar","ofender","oponer","orientar","oír","pagar","participar","pasar","pasear","patrocinar",
  "pelear","pensar","percibir","perdurar","permitir","perseguir","persistir","pertenecer","pesar","pintar",
  "planear","poder","predecir","preferir","preguntar","preocuparse","preparar","presentar","presionar","prevalecer",
  "prevenir","procurar","producir","prohibir","promover","pronunciar","proporcionar","publicar","puntuar","quejarse",
  "querer","quitarse","reaccionar","reanudar","rebajar","recaer","recibir","reclamar","recomendar","reconciliar",
  "rechazar","reducir","referir","reflexionar","regalar","registrar","regresar","rehacer","relajarse","relacionar",
  "renunciar","reparar","reponer","reservar","resfriarse","residir","resignarse","respaldar","respetar","responder",
  "restaurar","retirar","reunir","revisar","robar","rodear","saber","sacudir","saludar","sanar",
  "satisfacer","secar","seguir","seleccionar","sentarse","señalar","servir","significar","sintetizar","situar",
  "sobrar","sobresalir","sonar","soñar","sostener","subir","subrayar","suceder","sugerir","suponer",
  "tardar","temblar","tender","tener","terminar","tirar","tocar","tolerar","tomar","traducir",
  "trasladar","tratar","triunfar","ubicar","unir","usar","utilizar","valer","valorar","velar",
  "vencer","vender","vengarse","venir","vestir","viajar","vigilar","visitar","volar","volver",
  "vivir","yacer",

  // Sustantivos B1 adicionales (vida diaria, sociedad, trabajo)
  "abogacía","acceso","accidente","acción","actividad","acuerdo","adolescente","aeropuerto","agente","agricultor",
  "alarma","alegría","almacén","alojamiento","amabilidad","ambiente","ambulancia","amistad","ancho","aniversario",
  "anuncio","aparato","aplicación","apoyo","aprendizaje","aprobación","área","armario","arquitectura","arroz",
  "artículo","ascensor","aseo","asignatura","asistencia","aspecto","aula","ausencia","autobús","autopista",
  "autoridad","aventura","aviso","barba","barco","barrio","bebé","biblioteca","bicicleta","bienestar",
  "billete","bingo","biología","boletín","boletería","bolsillo","bombero","bomba","botella","brecha",
  "brigada","broma","bruma","buceo","buque","bus","caballo","cabeza","cabina","cable",
  "cabra","cadena","cafetería","caída","caja","calefacción","calendario","calidad","calle","callejón",
  "calma","calle","cámara","camino","camión","camisa","campaña","cancha","canción","candidatura",
  "canguro","cantidad","capa","capacidad","capítulo","cara","caravana","carga","cargo","caridad",
  "caricia","carnet","carrera","carro","carta","cartel","cartera","cartón","casa","castillo",
  "casualidad","catálogo","categoría","cebra","celebración","celular","cementerio","cena","centímetro","central",
  "centro","ceremonia","cero","certeza","certificación","cerveza","chaqueta","cheque","chef","chimenea",
  "chiste","chofer","ciencia","ciencias","cierre","cifra","cigarro","cine","cinta","cintura",
  "circuito","ciudad","ciudadanía","clase","claustro","clima","clínica","cocina","código","coche",
  "cocinero","colaboración","colegio","colega","colección","colgador","colocación","color","columna","combate",
  "comedor","comentario","comercio","comida","comisión","compañero","compañía","compasión","competencia","competición",
  "completo","compra","computadora","comunicación","comunidad","concentración","concepto","conclusión","concurso","condena",
  "condición","conexión","conferencia","confianza","conflicto","confusión","conjunto","consejo","conservación","consideración",
  "consigna","construcción","consulta","consumidor","contacto","contado","contenido","contexto","continente","contraseña",
  "contrato","control","conversación","copia","corazón","corona","corral","corredor","correo","correspondencia",
  "corriente","costa","costo","costumbre","creación","creencia","crisis","crítica","cuaderno","cuadro",
  "cuarto","cubo","cuello","cuenta","cuento","cuerda","cuerpo","cuestión","cuidado","culpa",
  "curiosidad","curso","cursor","danza","deber","decisión","declaración","dedo","defecto","defensa",
  "deficiencia","demanda","democracia","departamento","deporte","derecho","derroche","desarrollo","desayuno","descanso",
  "descripción","descubrimiento","descuento","desempleo","desgracia","desierto","desorden","despedida","despertador","destino",
  "detalle","detective","deuda","diálogo","diario","dibujo","diccionario","dieta","dificultad","dinero",
  "director","disco","discurso","diseño","disputa","distancia","distribución","diversidad","divorcio","doctor",
  "documento","dólar","dolor","domicilio","duda","duración","ecología","economía","edad","edición",
  "edificio","editor","educación","efecto","ejemplo","ejercicio","ejército","electricidad","elemento","embajada",
  "embarazo","emergencia","emoción","empleado","empresario","encargado","encuesta","energía","enfermedad","enfoque",
  "enlace","entrada","entrega","entrenador","entrevista","envío","equipo","error","escalera","escena",
  "esclavo","escritor","escuela","esfuerzo","espacio","espalda","especialidad","especialista","especie","espejo",
  "espera","esperanza","estación","estado","estanque","estante","este","estilo","estrategia","estreno",
  "estrés","estudiante","estudio","etapa","evento","examen","éxito","experiencia","experto","explicación",
  "explosión","extensión","extranjero","fábrica","facilidad","factura","facultad","falda","familia","fantasma",
  "favor","fecha","felicidad","ficha","fiebre","fiesta","figura","fila","filosofía","final",
  "finanza","firma","física","flecha","flor","folleto","fondo","foro","fortaleza","foto",
  "fragmento","frecuencia","frente","frontera","fruta","fuente","fuerza","función","fundación","fútbol",
  "futuro","ganador","gana","ganancia","garganta","gas","gato","género","gerente","gestión",
  "gesto","gigante","gimnasio","gobierno","gracia","grado","gráfico","gramo","gripe","grupo",
  "guante","guerra","guía","guion","hábito","hambre","hecho","helado","herencia","herida",
  "hermana","heroína","herramienta","hierro","hígado","hijo","historia","historiador","hogar","hoja",
  "hombre","hombro","hora","horario","hospital","hospedaje","hotel","huelga","huérfano","huésped",
  "humo","huracán","idioma","iglesia","igualdad","ilusión","imagen","imaginación","impacto","importancia",
  "imprenta","impresora","impuesto","incendio","incidente","índice","industria","infancia","información","ingeniería",
  "ingreso","iniciativa","injusticia","insecto","instante","instinto","institución","instrumento","integración","intención",
  "interés","interior","internet","intersección","investigación","invierno","invitación","isla","jardín","jerarquía",
  "jornada","juego","juez","juicio","jurado","jugador","junio","juvenil","juventud","kilómetro",
  "laboratorio","lado","ladrón","lago","lápiz","lealtad","lección","lectura","leche","lema",
  "lengua","letra","letrero","levante","ley","leyenda","liberación","libertad","librería","libro",
  "licencia","licor","líder","limite","límite","línea","liquidación","lista","literatura","llave",
  "llegada","lluvia","logro","loro","losa","lucha","lujo","luna","luz","madera",
  "madre","maestría","maestro","magia","mamá","mancha","manera","manga","manifestación","mano",
  "manual","manzana","máquina","mar","marca","marido","marisco","masa","material","mayoría",
  "medalla","medicina","medio","mejora","memoria","mensaje","mentalidad","mercado","mesa","metro",
  "miembro","milagro","minoría","minuto","misión","mochila","moda","modelo","molde","momento",
  "monedero","montaje","montaña","monumento","moral","motivo","movimiento","muestra","mujer","multa",
  "mundo","muralla","museo","música","músico","nación","naranja","narrativa","naturaleza","necesidad",
  "negativa","negocio","nevera","nieve","niñez","nivel","noche","nombre","norma","noroeste",
  "norte","nota","noticia","novedad","novia","número","objeto","obligación","obra","obrero",
  "obstáculo","ocasión","ocio","oeste","oferta","oficina","oficio","ola","operación","opinión",
  "opción","oportunidad","orden","oreja","organización","origen","orquesta","oro","otorgamiento","paciente",
  "padre","página","pájaro","palabra","palacio","palmera","paliza","paloma","pan","pantalla",
  "papá","papel","paquete","paraguas","parámetro","parecido","pareja","pariente","parque","parte",
  "partido","pasado","pasaje","pasaporte","paseo","paso","pasta","pastel","patio","patria",
  "patrón","paz","pecho","pedido","pedazo","pedal","pegamento","peinado","pelea","película",
  "peligro","pelo","pelota","pena","pensión","pepino","período","permiso","persona","personaje",
  "perspectiva","pesca","peso","pez","pie","piel","pierna","pieza","piloto","pinta",
  "pintor","pintura","piscina","piso","placer","plan","plancha","planeta","plano","planta",
  "plástico","plato","playa","plaza","plazo","poder","poema","poesía","poeta","policía",
  "política","pollo","polvo","portada","portero","posibilidad","posición","postal","posterior","práctica",
  "precio","predicción","preferencia","pregunta","prensa","preocupación","preparación","presencia","presente","presentación",
  "presidente","presión","préstamo","prima","primavera","primero","primo","príncipe","prisa","prisión",
  "privacidad","privilegio","problema","procedimiento","proceso","producto","profesión","profesor","profundidad","programa",
  "programador","progreso","promesa","propiedad","propuesta","protección","proveedor","provincia","proyecto","prueba",
  "psicología","público","pueblo","puente","puerta","puerto","puesto","punto","punta","puñetazo",
  "quemadura","química","quincena","quiosco","racimo","radio","raíz","rancho","rango","razón",
  "reacción","realidad","rebaja","receta","recepción","reclamación","recomendación","recompensa","reconocimiento","récord",
  "recuerdo","recurso","red","reducción","referencia","reforma","refugiado","regalo","región","registro",
  "regla","regreso","reino","relación","relámpago","religión","reloj","remedio","reportaje","república",
  "reserva","residencia","resistencia","respiración","respuesta","restaurante","resto","resultado","retorno","retraso",
  "reunión","revelación","revista","rey","reyerta","riesgo","río","ritmo","ritual","robo",
  "rodilla","rol","romance","ropa","rostro","rueda","ruido","ruta","rutina","sabiduría",
  "sabor","sacerdote","sacrificio","sal","sala","salida","salón","salud","saludo","sangre",
  "sátira","secreto","sector","seda","seguidor","seguridad","sello","selva","semana","semilla",
  "señal","sensación","sentido","sentimiento","serie","servicio","sesión","sexo","siglo","signo",
  "silla","sillón","símbolo","simpatía","síntoma","sistema","sitio","situación","sobre","sobremesa",
  "sociedad","sofá","sol","soldado","soledad","solicitud","solución","sombra","sonido","sonrisa",
  "soporte","sorpresa","subida","subtítulo","suceso","suegra","suegro","suelo","sueño","suerte",
  "sufrimiento","sugerencia","superficie","supermercado","superviviente","sur","susto","tabla","tableta","tacto",
  "talla","talón","talento","tamaño","tapa","taquilla","tarde","tarea","tarjeta","tasa",
  "tatuaje","taza","techo","tecnología","tela","telediario","teléfono","teoría","terapia","terraza",
  "terreno","testigo","texto","tía","tiempo","tienda","tierra","tigre","tipo","título",
  "toalla","tomate","tono","torneo","tos","tour","trabajo","tractor","tradición","traducción",
  "traductor","tráfico","traje","tranquilidad","transporte","tras","trato","trayecto","trayectoria","trecho",
  "tren","tribu","triunfo","tronco","tropa","tubo","túnel","turismo","turista","turno",
  "ubicación","universidad","universo","urgencia","uso","usuario","vacaciones","vacante","vacío","vacuna",
  "valentía","valor","variable","variedad","vaso","vecino","vegetal","vehículo","velocidad","venda",
  "venta","ventana","verano","verdad","versión","vértice","vestido","viajero","víctima","victoria",
  "vida","vídeo","viento","vínculo","violencia","virgen","virtud","virus","visita","vista",
  "vitamina","vivienda","vocabulario","vocación","voluntario","volumen","voto","voz","vuelo","vuelta",
  "zanahoria","zapato","zona","zumo",

  // Adjetivos B1 adicionales (descripción de personas, estados, situaciones)
  "abierto","aburrido","accesible","activo","actual","adecuado","afectivo","agitado","agradable","agradecido",
  "agresivo","alegre","alto","amable","amargo","ambicioso","amplio","ancho","angelical","anglosajón",
  "ansioso","anterior","antiguo","aparente","apropiado","ardiente","áspero","astuto","atento","atractivo",
  "atrevido","auténtico","autoritario","baja","bajo","barato","básico","benévolo","blanco","blando",
  "bonito","borracho","breve","brillante","bruto","bueno","calmado","caliente","capaz","cariñoso",
  "casual","caro","celoso","central","cercano","claro","clásico","cobarde","colorido","cómico",
  "compatible","complejo","completo","común","concreto","concurrido","constante","cortés","correcto","corriente",
  "criminal","cristiano","crucial","crudo","cuadrado","cuestionable","culto","curioso","decente","delicado",
  "delicioso","democrático","derecho","desconocido","desnudo","detallado","determinado","diario","diferente","difícil",
  "dignidad","dinámico","directo","discreto","disponible","distante","divertido","divino","doble","dorado",
  "drástico","duro","educativo","efímero","eficaz","eléctrico","elegante","emocional","emocionante","encantador",
  "enérgico","enfermo","enorme","entusiasta","equilibrado","escaso","esencial","espectacular","específico","espiritual",
  "espontáneo","estable","estético","estricto","estructural","estudioso","eterno","ético","europeo","exacto",
  "excelente","exhausto","exigente","exitoso","exótico","experimentado","explicativo","externo","extraordinario","extremo",
  "fácil","falso","fanático","fantástico","favorable","feliz","feo","fértil","festivo","ficticio",
  "fiel","fino","físico","flexible","florido","francés","franco","frecuente","frío","fresco",
  "frustrado","fuerte","funcional","fundamental","futuro","general","genial","global","gordo","grande",
  "gratuito","grave","gris","grosero","guapo","habitual","hábil","helado","hermoso","heroico",
  "hispano","histórico","hondo","horrible","hueco","humilde","ideal","idéntico","ignorante","ilógico",
  "ilustrativo","impactante","imparcial","imparable","impecable","impensable","imperdonable","imperfecto","importante","imposible",
  "impresionante","incierto","increíble","independiente","indiferente","indignado","industrial","infiel","infinito","influyente",
  "informativo","inocente","insano","insatisfecho","inseguro","insensible","insolente","inspirador","instintivo","instructivo",
  "íntegro","intelectual","inteligente","intenso","interesante","interior","intermedio","internacional","interno","íntimo",
  "intrépido","intuitivo","inusual","irrelevante","irresponsable","italiano","izquierdo","jocoso","joven","jubilado",
  "justo","laboral","laborioso","largo","leal","legal","ledo","lejano","libre","liberal",
  "ligero","limpio","listo","lleno","loco","longevo","lujoso","luminoso","luxurioso","macabro",
  "magnífico","majestuoso","maleducado","malo","manual","maravilloso","material","matrimonial","máximo","mecánico",
  "mediano","medio","melancólico","memorable","mental","metálico","mexicano","militar","mínimo","minucioso",
  "miserable","misterioso","mítico","moderado","moderno","modesto","modular","molesto","monumental","moral",
  "mortal","motivado","móvil","mudo","múltiple","mundial","mutuo","narrativo","natural","necesario",
  "negativo","negociable","negro","neutro","niño","nocturno","normal","nostálgico","notable","notorio",
  "novedoso","nuclear","numérico","obediente","objetivo","obligatorio","obvio","occidental","ocupado","ocurrente",
  "odiable","ofensivo","oficial","optimista","oral","oratorio","ordenado","ordinario","orgánico","orgulloso",
  "oscuro","paciente","pacífico","pacífista","pasado","pasajero","pasivo","patológico","patriota","pecaminoso",
  "peligroso","penal","pequeño","perezoso","perfecto","periodístico","peruano","pesado","pesimista","placentero",
  "plano","poderoso","pobre","político","positivo","posible","posterior","postre","potente","práctico",
  "precavido","precioso","preciso","precoz","preferible","presente","previo","primario","primero","principal",
  "privado","privilegiado","probable","problemático","procesal","profesional","profundo","prolongado","prometedor","propio",
  "próspero","protegido","prudente","público","puerto","pulcro","puntual","puro","racional","radical",
  "rápido","raro","razonable","real","realista","reciente","recíproco","recto","redondo","reflexivo",
  "regional","regular","relativo","relevante","religioso","remoto","renombrado","reparable","representativo","respetable",
  "respetado","responsable","reverenciado","rico","rígido","riguroso","risueño","rojo","romántico","rosado",
  "rubio","ruidoso","ruinoso","ruso","rústico","sabio","saciado","saludable","santo","satisfactorio",
  "secreto","secundario","seductor","seguro","sembradío","semejante","sencillo","sensato","sensible","sentimental",
  "señalado","septentrional","sereno","serio","silencioso","similar","simpático","simple","singular","sintético",
  "sistemático","situado","sobrio","social","solidario","solitario","solo","soltero","sonriente","sorprendente",
  "sostenible","suave","subjetivo","subliminal","suficiente","sumo","superficial","superior","supremo","susceptible",
  "suspicaz","sutil","tacaño","talentoso","tardío","técnico","tedioso","tenaz","tensivo","teórico",
  "terco","tibio","tierno","tímido","típico","tolerable","tolerante","torpe","total","tóxico",
  "trabajador","tradicional","tranquilo","transparente","tremendo","trémulo","triste","trivial","tropical","turbio",
  "turístico","unánime","único","uniforme","unilateral","universitario","urbano","urgente","usual","útil",
  "utilitario","valido","valeroso","valido","valiente","valioso","vano","variable","variado","vasto",
  "vegetariano","venenoso","ventajoso","verdadero","verde","vergonzoso","veterano","viable","vibrante","viejo",
  "virtual","virtuoso","visible","vital","vívido","vivo","vocal","voluntario","volcánico","vulgar",
  "vulnerable","yermo","zanco","zonal",

  // Conectores y expresiones B1 adicionales
  "a continuación","a fin de","a la vez","a lo largo de","a menos que","a partir de","a pesar de","a propósito","a su vez","a través de",
  "a veces","ahora bien","al menos","al principio","antes que nada","con el fin de","con frecuencia","con tal de","cuanto antes","de ahí que",
  "de hecho","de manera","de modo","de vez en cuando","desde luego","en aquel momento","en breve","en cambio","en caso de","en cuanto",
  "en cuanto a","en definitiva","en este sentido","en general","en lugar de","en otras palabras","en primer lugar","en realidad","en resumen","en seguida",
  "en suma","en todo caso","en último lugar","en vez de","es decir","es por eso que","gracias a","hace falta","hasta cierto punto","hasta que",
  "incluso","mejor dicho","más bien","mientras tanto","no obstante","o sea","para que","por cierto","por ejemplo","por encima de",
  "por eso","por fin","por lo menos","por lo pronto","por lo tanto","por tanto","por una parte","posiblemente","puede que","puesto que",
  "se trata de","sin duda","sin embargo","tan pronto como","tanto que","ya que",

  // Trabajo y profesiones adicionales B1
  "agricultor","albañil","artesano","artista","asesor","atleta","auditor","bibliotecario","biólogo","cajero",
  "camionero","capataz","cardiólogo","carnicero","cartero","cirujano","contable","conserje","corresponsal","cura",
  "decorador","dentista","despachador","detective","dueño","editor","empresario","entrenador","escritor","escultor",
  "estilista","fontanero","fotógrafo","funcionario","granjero","historiador","ingeniero","investigador","jardinero","juez",
  "jugador","limpiador","maestro","mecánico","mensajero","minero","minorista","minorista","misionero","modisto",
  "monje","músico","narrador","notario","oculista","oftalmólogo","operador","panadero","pastor","peluquero",
  "periodista","pescador","piloto","pintor","plomero","podólogo","político","portero","predicador","presentador",
  "presidente","productor","profesor","programador","psicólogo","publicista","químico","recepcionista","redactor","relojero",
  "reportero","sacerdote","sastre","secretario","sociólogo","soldado","supervisor","taxista","tendero","terapeuta",
  "técnico","tornero","traductor","vendedor","veterinario","zapatero",

  // Cocina y comida B1
  "aceite","aceituna","ajo","albahaca","alcohol","almendra","arroz","atún","azúcar","bacalao",
  "bebida","bistec","bocadillo","botella","brócoli","cacahuete","cacao","calabacín","calabaza","caldo",
  "camarón","caña","caramelo","carbohidrato","carne","castaña","cebada","cebolla","cereal","cereza",
  "cerveza","champiñón","champán","chile","chocolate","chorizo","chuleta","cilantro","ciruela","clavo",
  "coco","codorniz","col","comida","comino","comino","condimento","conserva","copa","cordero",
  "cordero","crema","crujiente","cuchara","cuchillo","desayuno","empanada","ensalada","especia","espinaca",
  "estofado","fideos","filete","fresa","fruta","galleta","granada","grasa","guisante","guiso",
  "hamburguesa","helado","hierba","higo","horno","hortaliza","jamón","judía","kiwi","langosta",
  "leche","lechuga","legumbre","lima","limón","lubina","maíz","mango","manjar","mantequilla",
  "manzana","mariscos","mayonesa","melocotón","melón","menta","menú","merengue","mermelada","miel",
  "morcilla","mostaza","nabo","nata","navaja","nuez","ñoquis","ostra","paella","pan",
  "panceta","papaya","parrilla","pasta","pastel","patata","pato","pavo","pepino","pera",
  "perejil","pescado","picante","piña","plato","plátano","pollo","postre","puré","queso",
  "ración","ravioles","refresco","relleno","romero","sabroso","saciar","sal","salami","salchicha",
  "salmón","salsa","sandía","sardina","sazón","sopa","tarta","ternera","tocino","tomillo",
  "tortilla","trucha","uva","vinagre","vino","wasabi","yogur","zanahoria","zumo",

  // Cuerpo y salud B1 adicionales
  "anorexia","apetito","articulación","aspirina","ataque","cadera","cansancio","cesárea","cicatriz","clavícula",
  "codo","coordinación","corazón","costilla","cráneo","cuello","cuerpo","dedo","depresión","desnutrición",
  "diabetes","diafragma","dolor","embarazo","epidermis","esguince","espalda","estómago","fatiga","fémur",
  "frecuencia","fractura","gota","hambre","hipertensión","hombro","huesos","insomnio","intoxicación","jaqueca",
  "lengua","lesión","mandíbula","mareo","médula","menstruación","migraña","muñeca","músculos","obesidad",
  "ojos","ojeras","oreja","órgano","palma","párpado","pulmón","reumatismo","riñón","rodilla",
  "sangrado","sensibilidad","sequía","sobrepeso","sudor","tendinitis","tobillo","tos","tristeza","úlcera",
  "uretra","vejiga","vértebra","vesícula",
]);
