// Spanish B2 additional lemmas. Combine with A1+A2+B1 via
// `isSpanishUpToLevel(word, "b2")`. B2 introduces abstract concepts,
// academic discourse, nuanced emotions, formal vocabulary.

export const SPANISH_B2_LEMMAS: ReadonlySet<string> = new Set([
  // Análisis / discurso académico
  "análisis","síntesis","argumentación","tesis","antítesis","hipótesis","premisa",
  "fundamento","planteamiento","enfoque","aproximación","perspectiva","metodología",
  "procedimiento","estrategia","táctica","esquema","estructura","modelo","paradigma",
  "investigación","estudio","experimento","observación","análisis","evaluación",
  "valoración","juicio","crítica","reseña","comentario","interpretación","explicación",
  "exposición","disertación","conferencia","ponencia","intervención","presentación",
  "diagnóstico","pronóstico","previsión","predicción","proyección","estimación",
  "conclusión","resultado","hallazgo","descubrimiento","constatación","comprobación",

  // Conceptos abstractos
  "concepto","noción","idea","teoría","filosofía","ideología","doctrina","creencia",
  "convicción","principio","valor","ética","moral","virtud","vicio","dignidad",
  "honor","prestigio","reputación","fama","notoriedad","trascendencia","legado",
  "esencia","naturaleza","carácter","índole","identidad","personalidad","temperamento",
  "actitud","postura","posicionamiento","disposición","tendencia","inclinación","sesgo",
  "verdad","realidad","ficción","imaginación","fantasía","ilusión","apariencia",
  "consciencia","conciencia","subconsciente","inconsciente","mente","intelecto","razón",
  "intuición","percepción","sensibilidad","perspicacia","agudeza","ingenio","talento",
  "capacidad","habilidad","destreza","competencia","aptitud","cualidad","facultad",

  // Sociedad B2
  "diversidad","pluralidad","inclusión","exclusión","discriminación","prejuicio",
  "estereotipo","minoría","mayoría","marginación","integración","asimilación",
  "globalización","modernización","industrialización","urbanización","migración",
  "inmigración","emigración","exilio","refugiado","desplazado","ciudadanía","nacionalidad",
  "identidad cultural","patrimonio","herencia","legado cultural","raíces","tradiciones",
  "valores sociales","normas sociales","convenciones","tabúes","prohibiciones",
  "desigualdad","brecha","pobreza","riqueza","clase social","jerarquía","privilegio",
  "movilidad social","ascenso","descenso","éxito","fracaso","logro","reconocimiento",

  // Política / economía B2
  "democracia","autocracia","dictadura","monarquía","república","federalismo",
  "constitución","tratado","acuerdo","alianza","pacto","convenio","contrato",
  "negociación","mediación","arbitraje","reconciliación","reforma","revolución",
  "estabilidad","inestabilidad","crisis","auge","recesión","depresión","recuperación",
  "inflación","deflación","desempleo","empleo","productividad","competitividad",
  "comercio internacional","exportación","importación","arancel","sanción","embargo",
  "moneda","divisa","cambio","mercado financiero","bolsa","acción","bono","fondo",

  // Tecnología avanzada B2
  "inteligencia artificial","algoritmo","datos","big data","machine learning",
  "automatización","robótica","ciberseguridad","privacidad","encriptación","blockchain",
  "criptomoneda","plataforma digital","aplicación móvil","red social","interacción",
  "experiencia de usuario","interfaz","accesibilidad","usabilidad","funcionalidad",
  "innovación","desarrollo","prototipo","lanzamiento","mantenimiento","actualización",

  // Emociones complejas B2
  "resentimiento","rencor","amargura","resignación","conformismo","perfeccionismo",
  "ambición","codicia","avaricia","generosidad","desinterés","altruismo","egoísmo",
  "vanidad","humildad","modestia","arrogancia","soberbia","prepotencia","insolencia",
  "compasión","piedad","misericordia","crueldad","violencia","agresividad","hostilidad",
  "afecto","cariño","amor","pasión","obsesión","fascinación","atracción","repulsión",
  "anhelo","añoranza","melancolía","tristeza profunda","duelo","luto","pérdida",
  "tranquilidad","serenidad","paz interior","equilibrio","armonía","desequilibrio",

  // Cultura / arte B2
  "estética","creatividad","inspiración","talento","virtuosismo","maestría","genio",
  "obra maestra","clásico","contemporáneo","vanguardia","tradicional","experimental",
  "abstracción","figuración","realismo","surrealismo","impresionismo","expresionismo",
  "simbolismo","metáfora","alegoría","ironía","sátira","parodia","homenaje","tributo",
  "crítica literaria","crítica de arte","análisis textual","interpretación","exégesis",
  "intertextualidad","referencia","alusión","cita","plagio","autoría","autenticidad",

  // Naturaleza / ciencia B2
  "ecosistema","biodiversidad","sostenibilidad","sustentable","renovable","no renovable",
  "biológico","ecológico","orgánico","sintético","molecular","celular","genético",
  "evolución","adaptación","mutación","selección natural","especie","extinción",
  "experimento","laboratorio","investigación científica","hipótesis científica",
  "metodología científica","peer review","publicación","revista científica","estudio",

  // Verbos B2
  "analizar","examinar","investigar","explorar","indagar","escudriñar","profundizar",
  "evaluar","valorar","apreciar","ponderar","considerar","contemplar","reflexionar",
  "meditar","cavilar","reconsiderar","replantear","cuestionar","interpelar",
  "argumentar","fundamentar","sustentar","respaldar","corroborar","ratificar",
  "demostrar","probar","evidenciar","manifestar","exteriorizar","exhibir","desplegar",
  "implementar","ejecutar","aplicar","poner en práctica","llevar a cabo","materializar",
  "concretar","plasmar","cristalizar","consolidar","afianzar","reforzar","fortalecer",
  "debilitar","desgastar","erosionar","socavar","minar","subvertir","cuestionar",
  "transformar","modificar","alterar","reformar","renovar","actualizar","modernizar",
  "promover","fomentar","impulsar","incentivar","estimular","motivar","alentar",
  "desalentar","desincentivar","obstaculizar","entorpecer","frenar","ralentizar",

  // Adjetivos B2
  "trascendental","fundamental","esencial","intrínseco","inherente","característico",
  "distintivo","peculiar","particular","exclusivo","único","singular","excepcional",
  "extraordinario","notable","destacado","sobresaliente","prominente","relevante",
  "sutil","matizado","sofisticado","refinado","elegante","exquisito","selecto","exclusivo",
  "ambiguo","equívoco","impreciso","vago","nebuloso","difuso","borroso","oscuro",
  "explícito","implícito","tácito","sobreentendido","evidente","obvio","manifiesto",
  "subjetivo","objetivo","imparcial","neutro","sesgado","tendencioso","parcializado",
  "coherente","incoherente","consistente","inconsistente","contradictorio","paradójico",
  "factible","inviable","viable","practicable","ejecutable","alcanzable","inalcanzable",
  "polémico","controversial","polémica","debatible","cuestionable","incuestionable",
  "ético","inmoral","amoral","virtuoso","vicioso","corrupto","íntegro","honrado",

  // === EXPANSIÓN B2 (cobertura ampliada) ===

  // Verbos B2 adicionales (académicos, análisis, abstracción, registro formal)
  "abarcar","abogar","abordar","absorber","abstraer","acaecer","acaparar","acatar","acceder","acentuar",
  "acoger","acometer","acomodar","aconsejar","acoplar","acrecentar","acreditar","actuar","adaptar","adherir",
  "adjudicar","admirar","admitir","adolecer","adoptar","advertir","afectar","afianzar","afligir","afrontar",
  "agilizar","aglutinar","agotar","aguardar","ahorrar","ajustar","alargar","alentar","alimentar","aludir",
  "alterar","amenazar","ampliar","amplificar","analogizar","anhelar","apaciguar","apelar","apoderarse","aportar",
  "apostar","apreciar","aprobar","aprovecharse","arraigar","articular","ascender","asegurar","asentir","asignar",
  "asimilar","asistir","asociar","asomarse","aspirar","asumir","atender","atenuar","atestiguar","atinar",
  "atribuir","aumentar","autenticar","automatizar","auxiliar","avanzar","avenirse","balancear","basar","bastar",
  "bautizar","bloquear","bocetear","boicotear","brindar","calar","calibrar","callar","cambiar","canalizar",
  "captar","caracterizar","catalogar","categorizar","causar","cautivar","ceder","censurar","centrar","cernirse",
  "certificar","cesar","circular","circunscribir","civilizar","clamar","clarificar","clasificar","cobijar","cohibir",
  "coincidir","colectar","colocar","comandar","combatir","combinar","comparecer","compartir","compatibilizar","competir",
  "compilar","componer","comprender","compulsar","computar","comunicar","concebir","conceder","concentrar","conciliar",
  "concluir","concretar","concurrir","condicionar","conducir","conferir","configurar","confiscar","conformar","confrontar",
  "congeniar","congregar","conjeturar","conjugar","conllevar","conmemorar","conmocionar","conmover","connotar","consentir",
  "conservar","considerar","consolidar","constituir","construir","consultar","contemplar","contener","contradecir","contrastar",
  "contrarrestar","contribuir","controvertir","convencer","converger","convertir","convocar","cooperar","coordinar","copiar",
  "correlacionar","corresponder","cosechar","cotejar","crear","criar","cristalizar","cuajar","cuantificar","cubrir",
  "cuestionar","cultivar","cumplimentar","cumplir","custodiar","datar","deambular","debatir","debilitar","decidir",
  "declamar","declarar","decretar","dedicar","deducir","defenestrar","degenerar","delegar","delimitar","delinquir",
  "demandar","democratizar","denominar","denotar","denunciar","departir","depender","deplorar","deponer","depositar",
  "depreciar","depurar","derivar","derogar","desafiar","desafinar","desarrollar","desatar","desbordar","descalificar",
  "descartar","descender","descifrar","descomponer","desconcertar","desconfiar","descontar","descubrir","desdeñar","desencadenar",
  "deshacerse","designar","desistir","deslindar","desmentir","desmerecer","desmitificar","desmoronar","despertar","desplegar",
  "desplomar","despojar","desprenderse","despuntar","destacar","destrozar","desvanecerse","desviar","detallar","detectar",
  "deteriorar","determinar","detonar","devenir","dialogar","dictaminar","diferenciar","difundir","dignificar","dilapidar",
  "diluir","dinamizar","dirimir","discernir","discrepar","discriminar","discutir","disentir","disertar","disfrazar",
  "disipar","disminuir","disociar","disparar","distinguir","distorsionar","distraer","disuadir","divagar","diversificar",
  "documentar","domeñar","dominar","donar","dotar","duplicar","editar","educar","efectuar","ejercitar",
  "elevar","elidir","eliminar","elucidar","emanar","embelesar","emerger","emitir","emocionar","empapar",
  "emparentar","empatar","emprender","empujar","emular","enajenar","enaltecer","encabezar","encadenar","encajar",
  "encalar","encaminar","encarnar","encauzar","enclaustrar","encomendar","encubrir","encumbrar","endeudarse","endurecer",
  "enfatizar","engendrar","englobar","engrandecer","enhebrar","enjuiciar","enmarcar","enraizar","enredar","enriquecer",
  "ensanchar","ensayar","ensombrecer","enterar","entrelazar","entremezclar","entrever","entusiasmar","enumerar","enunciar",
  "envilecer","equilibrar","equiparar","erigir","erradicar","escalar","escasear","esclavizar","escribir","escudriñar",
  "escudar","esfumarse","esgrimir","esmerarse","esperar","esquematizar","esquivar","estabilizar","establecer","estandarizar",
  "estimar","estimular","estipular","estirar","estudiar","etiquetar","evacuar","evadir","evaluar","evidenciar",
  "evitar","evocar","evolucionar","exacerbar","examinar","exceder","excluir","exhibir","exhortar","existir",
  "exonerar","expedir","experimentar","explorar","explotar","exponer","exportar","expresar","exteriorizar","extinguir",
  "extirpar","extraer","extralimitarse","facilitar","facturar","falsificar","fascinar","favorecer","federar","filtrar",
  "finalizar","financiar","firmar","fiscalizar","fluir","fomentar","forjar","fortalecer","fortificar","fragmentar",
  "franquear","fraternizar","frecuentar","frenar","frustrar","fundamentar","funcionar","fundar","fundir","gravar",
  "guarnecer","guiar","habituar","hallar","hilar","historiar","homogeneizar","honrar","hospedar","hospitalizar",
  "humanizar","identificar","idolatrar","ignorar","iluminar","ilustrar","imitar","impedir","implantar","implementar",
  "implorar","imponer","importunar","impresionar","improvisar","impulsar","incentivar","incidir","incinerar","incitar",
  "incluir","incomodar","incorporar","incrementar","inculcar","incumplir","incurrir","indagar","indicar","individualizar",
  "inducir","industrializar","infectar","inferir","infiltrar","infligir","influenciar","informar","ingerir","inhabilitar",
  "inhibir","iniciar","injuriar","innovar","inquirir","inscribir","insertar","insinuar","instar","instigar",
  "instituir","instrumentalizar","integrarse","intensificar","interceptar","interesar","interferir","internalizar","interpelar","interpolar",
  "interpretar","intervenir","intuir","invadir","inventar","invertir","investigar","invitar","involucrar","irritar",
  "irrumpir","jerarquizar","juntar","justificar","juzgar","labrar","lacerar","lapidar","legalizar","legar",
  "legislar","levantar","liberar","liderar","limar","limitar","liquidar","localizar","lograr","mancomunar",
  "manchar","mandar","manejar","manipular","mantenerse","maquillar","maravillar","marcar","marcharse","martirizar",
  "matar","matizar","mecanizar","mediar","memorizar","mencionar","menguar","mentir","metamorfosear","migrar",
  "militar","militarizar","minimizar","mitigar","modelar","moderar","modular","molestar","monitorear","monopolizar",
  "moralizar","moverse","movilizar","mudarse","mutilar","narrar","naturalizar","necesitar","negociar","neutralizar",
  "nivelar","nombrar","normalizar","notificar","nuclear","numerar","nutrir","obedecer","obrar","observar",
  "obstinarse","obstruir","obtener","ocasionar","ocultar","ofrecer","ofuscar","operar","opinar","oponer",
  "opositar","optar","optimizar","ordenar","organizarse","orientarse","originar","oscurecer","ostentar","otorgar",
  "padecer","pactar","palpar","palpitar","paralizar","parar","parlamentar","participar","particularizar","partir",
  "patentar","patrocinar","pausar","pavimentar","pedir","peregrinar","perfeccionar","permanecer","permitir","perpetuar",
  "perseguir","persistir","personalizar","persuadir","pertenecer","plantear","plasmar","plebiscitar","poblar","polemizar",
  "ponderar","portar","postular","postergar","posteriorizar","potenciar","practicar","precaver","preceder","precipitar",
  "precisar","predicar","predisponer","predominar","preferir","prefigurar","preludiar","premiar","presagiar","prescribir",
  "presentar","preservar","presidir","prestar","presuponer","prevalecer","privar","privilegiar","procesar","proclamar",
  "procrear","procurar","producir","profanar","proferir","profesar","prohibir","prolongar","promediar","promulgar",
  "pronosticar","propagar","propiciar","propinar","proponer","proporcionar","propulsar","prorrogar","prosperar","prostituir",
  "proteger","protestar","prouevar","proveer","provenir","provocar","publicar","pujar","pulir","pulsar",
  "puntualizar","purificar","quebrar","quedarse","racionar","radicar","ramificarse","ratificar","reaccionar","reactivar",
  "realizar","reanudar","rebasar","rebelarse","rebotar","recabar","recapacitar","recibir","recobrar","recoger",
  "recomendar","reconocer","reconquistar","reconstruir","recopilar","recordar","recorrer","rectificar","recuperar","recurrir",
  "redactar","redimir","redoblar","redondear","reducir","reelaborar","reemplazar","refleccionar","reformar","reforzar",
  "refrenar","refugiarse","refundar","refutar","regenerar","regentar","registrar","regular","reír","reiterar",
  "rejuvenecer","relacionarse","relatar","releer","relegar","relevar","remarcar","rematar","remediar","remendar",
  "rememorar","remitir","remontar","remover","renombrar","renovar","reñir","reparar","repartir","repercutir",
  "repetir","replicar","reportar","repreender","reprimir","reprobar","reproducir","repudiar","requerir","resaltar",
  "resarcir","rescatar","resentir","reservar","resignar","resignificar","resistir","resolver","resonar","respaldar",
  "respetar","respirar","resplandecer","responder","restablecer","restaurar","restringir","resucitar","resumir","resurgir",
  "retar","retener","retirar","retomar","retornar","retraerse","retransmitir","retrasar","retroceder","retrotraer",
  "reunir","revalorar","revelar","reverenciar","revertir","revisar","revivir","revolucionar","robustecer","rodar",
  "romper","rotar","rubricar","sacar","sacralizar","sacrificar","saldar","salvaguardar","salvar","sancionar",
  "satisfacer","secuestrar","secundar","sedimentar","seducir","segmentar","segregar","seguir","sellar","sembrar",
  "semejarse","sensibilizar","sentenciar","señalar","separar","sepultar","serenarse","servir","sesgar","significar",
  "silenciar","simbolizar","simpatizar","simplificar","simular","sintetizar","sintonizar","sistematizar","situarse","sobrecargar",
  "sobrellevar","sobreponerse","sobrevenir","sobrevivir","socorrer","sofocar","soldar","solemnizar","solicitar","solidarizarse",
  "soltar","solucionar","solventar","someter","sondear","sonreír","sopesar","sortear","sosegar","sostener",
  "soterrar","subastar","subir","sublevarse","sublimar","subordinar","subrayar","subsanar","subsidiar","subsistir",
  "substraer","subvencionar","subvertir","suceder","suelar","suceder","suelar","sufragar","sugerir","suministrar",
  "supervisar","suplir","suponer","suprimir","sustanciar","sustentar","susurrar","tabular","tachar","tantear",
  "tarjetear","tasar","temer","tender","tergiversar","terminar","testimoniar","tildar","tipificar","titubear",
  "tolerar","topar","torcer","tornar","torturar","trabajar","transmitir","traducir","traer","traficar",
  "tragar","traicionar","trampear","tranquilizar","transcribir","transcurrir","transferir","transformar","transgredir","transigir",
  "transitar","transparentar","transportar","trastocar","trastornar","tratar","treparse","tributar","triturar","triunfar",
  "trivializar","trocar","tropezar","truncar","tutelar","ubicar","ulterar","ultimar","ultrajar","ungir",
  "unificar","unirse","universalizar","urbanizar","usar","usurpar","utilizar","vacilar","vagar","validar",
  "valorar","vanagloriarse","vaticinar","velar","venerar","ventilar","verificar","versar","vigorizar","vincular",
  "vindicar","visualizar","vivenciar","vocear","vociferar","volcar","yuxtaponer",

  // Sustantivos B2 adicionales (abstractos, sociales, académicos)
  "abdicación","abnegación","abogado","aboaminación","abrazo","abrumamiento","absolutismo","abstención","abundancia","abuso",
  "academia","accesibilidad","accesorio","acción","aceptación","acercamiento","acervo","aclamación","aclaración","acogida",
  "acompañamiento","acoso","acrobacia","actitud","actividad","activismo","acto","actor","acuerdo","acusación",
  "adaptación","adicción","adjetivo","administración","admiración","admisión","adolescencia","adoración","adquisición","adversario",
  "afán","afecto","afiche","aficionado","afluencia","agencia","agente","agitación","agnosticismo","agonía",
  "agresividad","agrupación","aguante","ahorro","aislamiento","ajuste","alarma","alcance","alegoría","alianza",
  "alimento","alivio","alma","almacén","altar","alternativa","altura","aluvión","amante","amargura",
  "amasamiento","ámbito","ambiente","amenaza","amparo","análisis","analogía","anhelo","anhídrido","animación",
  "anomalía","anonimato","ansiedad","antagonista","anticipo","antiguedad","antología","anuncio","apatía","aplauso",
  "apertura","apogeo","apología","aporte","aporte","apoyo","apreciación","aprendiz","aprobación","aproximación",
  "apuesta","aquiescencia","arancel","arbitraje","archivo","arenga","argumentación","arma","armadura","armisticio",
  "armonía","arquetipo","arquitecto","arraigo","arrebato","arrepentimiento","arribo","arte","articulación","artificio",
  "artillería","asamblea","asalto","asaltante","ascendente","ascenso","ascensión","ascetismo","aseguramiento","asentamiento",
  "asentimiento","asesoramiento","asfixia","aspecto","aspiración","asunción","asunto","ataque","atención","atestiguamiento",
  "atmósfera","atrocidad","audacia","auditoría","auge","aumento","ausencia","autenticidad","autocrítica","automatización",
  "autonomía","autopsia","autoridad","autoritarismo","autorización","auxilio","aval","avalancha","avance","aventura",
  "aviación","balance","banca","bandera","barbarie","base","beneficio","biografía","blasfemia","boato",
  "bombardeo","bondad","bonificación","brigada","brillo","búsqueda","cabal","calamidad","calidad","calumnia",
  "campo","candidato","cantidad","capital","captura","caracterización","carestía","caridad","catarsis","categoría",
  "causa","cautela","celebración","celibato","censura","cercanía","cerebro","certeza","certificado","cesación",
  "chusma","ciclo","cierre","cinismo","cita","civilidad","civilización","claridad","clausura","clemencia",
  "coalición","cobardía","cobertura","código","coexistencia","coincidencia","colaborador","colapso","colección","colectivo",
  "colega","colmena","colocación","columnista","combate","comentario","comerciante","cometido","comisión","competencia",
  "complacencia","complejidad","cómplice","componente","comportamiento","compraventa","compromiso","compulsión","comunicación","comunidad",
  "concentración","concepción","concesión","conciencia","conciliación","conclusión","concordia","condena","condicionamiento","conducta",
  "confederación","conferencia","confesión","confianza","configuración","conflicto","confluencia","conformidad","confort","confrontación",
  "confusión","congoja","congreso","conjetura","conjunción","conmoción","conocimiento","consenso","consideración","consigna",
  "consistencia","consolación","consolidación","conspiración","constancia","constatación","constelación","consternación","constructor","consulta",
  "consumismo","consumo","contemplación","contenedor","contención","contención","conteo","contestación","contextualización","contienda",
  "continuidad","contradicción","contraposición","contrato","contribución","contundencia","controversia","conveniencia","convergencia","conversación",
  "convicción","convivencia","convocatoria","cooperación","cordura","corolario","correctivo","correspondencia","corrupción","cortejo",
  "cosecha","costumbrismo","crápula","credibilidad","crédito","creencia","crepúsculo","crianza","crimen","cristalización",
  "criterio","crítica","crónica","cruce","crueldad","cuadrilla","cualificación","cuantificación","cuarentena","cuestionamiento",
  "cuidador","culminación","culpabilidad","cultismo","cumbre","cumplido","cumplimiento","cúmulo","curiosidad","custodia",
  "debate","decadencia","decepción","declinación","decoro","dedicación","defraudación","degradación","delegación","deliberación",
  "delicia","delincuencia","demarcación","demografía","demora","denuncia","departamento","dependencia","deporte","depresión",
  "derecha","derrocamiento","derrota","desacato","desacuerdo","desafección","desafío","desaliento","desamparo","desánimo",
  "desaparición","desarme","desarrollo","desbordamiento","descalabro","descalificación","descarga","descenso","descomposición","desconcierto",
  "descontento","descortesía","descubrimiento","desdicha","desdoblamiento","desempeño","desencanto","desenlace","deserción","desesperanza",
  "desfase","desfile","desgaste","desgracia","designio","designación","desilusión","desinformación","desinhibición","deslealtad",
  "desmedida","desmesura","desmotivación","desolación","desorden","desorientación","despego","despilfarro","despliegue","despojo",
  "desprecio","desprendimiento","destierro","destino","destitución","destreza","destrucción","desvalorización","desventaja","desviación",
  "detalle","detención","deterioro","determinación","deuda","devaluación","devastación","devoción","devolución","diagnóstico",
  "diatriba","dictador","dictadura","dictamen","didáctica","diferenciación","dignidad","digresión","dilatación","dilatoria",
  "diligencia","dimensión","dimisión","dinastía","diplomático","directiva","directriz","discernimiento","disciplina","discordancia",
  "discordia","discreción","discriminación","discrepancia","discurso","disertación","disfrute","disidencia","disimulo","disolución",
  "disparidad","disposición","disputa","distancia","distinción","distorsión","distrito","disturbio","disuasión","divergencia",
  "diversificación","diversión","divinidad","divulgación","docencia","doctrina","documental","dogma","dolor","dominante",
  "dominio","donativo","drama","dualidad","duda","dureza","ecuación","edición","educador","efectivo",
  "efectividad","eficacia","eficiencia","egoísmo","elaboración","élite","elocuencia","emancipación","embajador","embate",
  "embelesamiento","emblema","embuste","emisión","emoción","empatía","empeño","emperador","empoderamiento","emprendedor",
  "encarnación","encendido","encierro","encrucijada","encuadre","endeudamiento","enemigo","enfermo","enfoque","engaño",
  "enmienda","enojo","ensayo","enseñanza","entendimiento","entorno","entusiasmo","envidia","equidad","equilibrio",
  "equiparación","equivocación","errata","escalada","escándalo","escarmiento","esencia","esfuerzo","esmero","espejismo",
  "esperanza","espectáculo","espíritu","espontaneidad","estabilización","establecimiento","estancamiento","estandarte","estatuto","estética",
  "estigma","estilo","estímulo","estrategia","estremecimiento","estrenamiento","estructura","estruendo","estuche","etapa",
  "ética","etnicidad","eufemismo","euforia","evangelio","evasión","evidencia","evocación","evolución","exactitud",
  "exaltación","examen","excelencia","exceso","exclusión","exhibición","exhortación","exigencia","exilio","existencia",
  "exorcismo","expansión","expectativa","expedición","expediente","experiencia","experimentación","expiación","explanada","explicación",
  "explotación","exposición","expresión","expropiación","exquisitez","éxtasis","extensión","exterior","externalización","extinción",
  "extracción","extranjería","extravagancia","extravío","extremismo","extremo","facción","facilidad","facsímil","factor",
  "facultad","falacia","falsedad","fanatismo","fantasía","fascinación","favoritismo","fe","fecundación","federalismo",
  "feminismo","fenómeno","ferocidad","ferrocarril","fervor","fibra","ficción","fidelidad","figuración","filiación",
  "filosofía","financiación","fineza","firmeza","fiscalía","fluctuación","fondo","forma","formación","formulación",
  "fortaleza","fortuna","franquicia","fraternidad","fricción","frontera","fruición","frustración","fuente","fuerza",
  "fugacidad","función","fundación","fundamento","fundamentalismo","fundición","fusilamiento","fusión","gallardía","ganancia",
  "garantía","gastronomía","genealogía","generación","género","generosidad","genio","gentileza","gerencia","gestación",
  "gimnasia","globo","glamour","gobernabilidad","gobernanza","gobernante","gracias","grandeza","granito","granjería",
  "gravamen","gravedad","gremio","grieta","grosería","guardia","guarnición","guerrilla","habilidad","hacienda",
  "hallazgo","hambruna","haz","hazaña","hegemonía","heredero","herida","heroísmo","hipocresía","historia",
  "holocausto","homenaje","homogeneidad","honorario","horizonte","horror","hostilidad","huelga","humillación","ideación",
  "ideal","idealismo","identificación","ideología","ignominia","ilegalidad","ilegitimidad","ilícito","ilustración","ilusión",
  "imaginario","imitación","impacto","imparcialidad","impasse","impedimento","ímpetu","implicación","imposición","impotencia",
  "imprecación","impredecibilidad","imprenta","improvisación","imprudencia","impulsividad","impuro","inacción","inactividad","inaccesibilidad",
  "inauguración","incertidumbre","incidencia","incidente","incitación","inclusión","incógnita","incomodidad","incompatibilidad","incompetencia",
  "inconsistencia","inconveniencia","incorrección","incorporación","incremento","increpación","independencia","indicador","indignación","indisciplina",
  "indolencia","inducción","ineficacia","ineptitud","infamia","infancia","inferencia","inferioridad","infierno","infiltración",
  "infinidad","inflación","infracción","ingenio","ingenuidad","ingeniería","iniciación","iniciativa","injerencia","injusticia",
  "innovación","insistencia","insolvencia","inspección","inspiración","instalación","institucionalización","integración","integridad","intelecto",
  "intelectualidad","intencionalidad","intensidad","interacción","intercambio","intercesión","interés","interlocutor","intermediación","interpretación",
  "interrupción","intervención","intimación","intimidación","intolerancia","introspección","intuición","invalidez","invasión","inventiva",
  "inversión","investigador","invitación","irrelevancia","irreverencia","irritación","jerarca","jerarquía","jerigonza","juicio",
  "justeza","justificación","kafkiano","laberinto","lacra","lamento","languidez","largueza","latinidad","laxitud",
  "lealtad","legado","legislación","legislatura","legitimidad","lema","lentitud","lesión","letargo","levantamiento",
  "lexicón","liberalismo","liderazgo","ligereza","limitación","linaje","liquidación","literatura","litigio","logística",
  "lozanía","lucidez","lucimiento","ludismo","madurez","magia","magnanimidad","magnitud","majestuosidad","malestar",
  "maldad","maldición","maleducación","malentendido","malicia","mandamiento","mandato","manejo","manera","manifestación",
  "maniobra","manipulación","manuscrito","marca","marginalización","martirio","masacre","matanza","materialismo","matización",
  "matrimonio","maximización","máxima","mecenas","mediación","mediocridad","mejora","memorando","menosprecio","mensaje",
  "mentalidad","mentira","mérito","metáfora","método","metodología","metrópolis","milicia","misántropo","misericordia",
  "misión","misoginia","misterio","mitificación","mito","modalidad","moderación","modificación","molestia","monarquía",
  "monasterio","monopolio","monotonía","moralidad","moralización","mortandad","motín","movilidad","movilización","muchedumbre",
  "muerte","multitud","municipalidad","mutilación","narcisismo","narración","negación","negligencia","negociación","neutralidad",
  "nobleza","nominación","nostalgia","novedad","novelista","nulidad","obediencia","objeción","objetividad","obligación",
  "obra","obscuridad","obsequio","obsesión","obstáculo","obstinación","obtención","ocupación","ocurrencia","odio",
  "ofensiva","oficialidad","ofuscación","oleada","olvido","omisión","omnipotencia","opacidad","operatividad","oposición",
  "opresión","orador","oratoria","orden","ordenamiento","ordenanza","organicidad","organización","organismo","orgullo",
  "originalidad","orgía","orientación","ornamentación","oscuridad","ostentación","otorgamiento","pacificación","pacto","padecimiento",
  "padrinazgo","paliativo","palabrería","palabreja","panacea","panfleto","paradoja","parálisis","paramilitar","paranoia",
  "parlamento","parodia","paroxismo","participación","particularidad","parto","pasaje","pasividad","pasmo","patología",
  "patrimonio","patrocinio","pauta","paz","pecado","peculiaridad","peculado","peligrosidad","pensamiento","penuria",
  "percance","percatación","percepción","perdición","peregrinación","perfeccionamiento","perfil","perjuicio","permanencia","perpetuidad",
  "persecución","perseverancia","persistencia","personalismo","personalización","persuasión","pertenencia","perturbación","perversidad","pesadumbre",
  "pesquisa","petición","piedad","planificación","planteamiento","plasmación","plebiscito","plenitud","pluralismo","pobreza",
  "polarización","polémica","poliedro","polución","ponderación","portento","portavoz","postergación","posteridad","postulado",
  "potencia","potestad","práctica","preámbulo","precariedad","precaución","precedente","precepto","precio","precisión",
  "predicación","predicamento","predilección","predominio","preeminencia","preexistencia","prefacio","preferencia","prejuicio","preludio",
  "premisa","preocupación","preparativo","prerrogativa","presagio","prescripción","presentación","presentimiento","preservación","presidencia",
  "presunción","pretensión","prevención","previsión","primacía","prioridad","privación","privilegio","probabilidad","probidad",
  "procedimiento","proceso","procesión","proclamación","prodigio","producción","productividad","profecía","profesionalismo","profesionalización",
  "profundización","profusión","progresión","promiscuidad","promoción","promulgación","pronóstico","pronunciamiento","propagación","propaganda",
  "propensión","propiciación","propiedad","proporción","propósito","propuesta","prosperidad","prostíbulo","prostitución","protagonismo",
  "protagonista","protocolo","provincialismo","provisión","provocación","proxenetismo","proximidad","proyección","prudencia","puerilidad",
  "pugna","pulcritud","pulverización","pundonor","punición","pureza","purga","purificación","puzzle","quebranto",
  "quehacer","quejido","quietud","quietismo","quiltro","quiebra","quirófano","quirúrgico","quizás","racionalidad",
  "racismo","radicalismo","radicalización","ramificación","rapidez","rapsodia","rasgo","rastro","ratificación","razonamiento",
  "reaccionario","reactivación","realeza","realización","reanimación","reanudación","rebajo","rebelión","rebrote","recadero",
  "recaída","recaudación","recelo","recibimiento","reciprocidad","reclamación","recomendación","reconciliación","reconocimiento","reconquista",
  "reconsideración","reconstrucción","reconversión","recorrido","recriminación","rectificación","rectitud","recuento","recuperación","redención",
  "redentor","redondez","reducción","reedición","reembolso","reemplazo","referéndum","refinamiento","reforma","refrendo",
  "refresco","refugio","regaño","regencia","régimen","reglamentación","regocijo","regresión","regulación","regularidad",
  "rehabilitación","reincidencia","reintegración","reiteración","reivindicación","relación","relajamiento","relato","relevancia","relieve",
  "religiosidad","reliquia","relleno","remembranza","remesa","reminiscencia","remisión","remodelación","remordimiento","remuneración",
  "renacimiento","renombre","renovación","renta","renuncia","reorganización","reorientación","reparación","repartición","reparto",
  "repentinidad","repercusión","reposo","reposición","representación","represalia","represión","reproducción","república","repudio",
  "repugnancia","reputación","requerimiento","requisito","resabio","resaltado","resarcimiento","resentimiento","reserva","resfrío",
  "resignación","resistencia","resolución","resonancia","resorte","respaldo","respetabilidad","respiración","resplandor","responsabilidad",
  "restablecimiento","restauración","restitución","restricción","resultante","resurgimiento","retención","reticencia","retirada","retórica",
  "retoma","retorno","retraimiento","retraso","retribución","retroceso","reunión","revelación","reverberación","reverencia",
  "revés","revisión","revocación","revuelta","ridiculez","rigidez","riguridad","rigor","rimero","ritualidad",
  "robustez","ronquera","rosario","rostro","rotura","rotación","rubor","ruegos","ruido","ruina",
  "rumbo","ruptura","rutina","sabia","sabor","sacrificio","sagacidad","salubridad","salvaguardia","salvajada",
  "salvedad","sanción","santidad","sapiencia","saturación","secrecía","secuela","secuestro","sedición","sedimento",
  "seducción","seguidor","seguimiento","seguridad","selectividad","semblante","sensación","sensibilidad","sentenciar","sentido",
  "sentimentalismo","señorío","seriedad","servidumbre","severidad","sicariato","siembra","silencio","simplicidad","simulacro",
  "sinceridad","sindicato","sinfín","singularidad","síntesis","situación","sobrenombre","sobreproducción","sobriedad","sociabilidad",
  "socialismo","sociología","solapamiento","soledad","solidaridad","solidez","solitario","sometimiento","sondeo","sorpresa",
  "sosiego","sospecha","sostenimiento","stalinismo","subida","sublevación","subordinación","subrayo","subsanación","subsidio",
  "substancia","subsuelo","subversión","sucesión","sucesor","sucumbir","sufragio","sufrimiento","superación","superación",
  "superpotencia","supervisión","supervivencia","suplemento","súplica","supremacía","supresión","susceptibilidad","suspensión","suspicacia",
  "sustancialidad","sustento","sustitución","sutileza","tacañería","tácito","tangibilidad","táctica","talento","tarea",
  "tasación","teatralidad","técnica","tecnología","televidente","temeridad","temperancia","temple","templo","tenacidad",
  "tendencia","tensión","tentación","teólogo","teoría","ternura","terquedad","testamento","testigo","testimonio",
  "tilde","timbre","timidez","tipología","tirano","tiranía","titularidad","tolerancia","toma","tono",
  "tópico","tortura","totalidad","totalitarismo","toxicidad","trabajador","trabajo","traducción","tragedia","traición",
  "trama","trampa","tramposo","tranquilidad","trance","transacción","transcurso","transformación","transgresión","transición",
  "transmisión","transparencia","trasfondo","traslado","transporte","trastorno","tratamiento","traumas","travesía","traza",
  "tribunal","trinchera","triunfo","trofeo","tropelía","trotamundos","tutela","tutor","ulteridad","ultimátum",
  "umbral","unanimidad","unidad","unificación","uniformidad","unión","universalismo","universalidad","urgencia","usurpación",
  "uso","utilidad","utopía","vacilación","vacío","valía","validación","validez","valoración","vanidad",
  "variedad","veneración","ventaja","veracidad","verbalización","verdadero","verificación","verosimilitud","veredicto","vergüenza",
  "verosimilitud","versión","vértigo","veteranía","vetustez","viabilidad","viaje","vicio","victimización","vigencia",
  "vigilancia","villanía","vínculo","violación","violencia","viraje","viril","virtud","visión","vista",
  "vistazo","vituperio","vivencia","vocación","vocería","volatilidad","voluntariado","voluptuosidad","voracidad","vorágine",
  "votante","vuelco","vulgaridad","vulnerabilidad","yermo","yugo","zalamería","zancada","zaranda","zarpazo",
  "zona","zozobra",
]);
