SETS = {
"el-cafe-lo-pones-tu": {
 "M": [("candado", "padlock"), ("madera", "wood"), ("mudanza", "house move"), ("derrota", "defeat")],
 "E": [
  ("C", "peña", "La [[peña]] le había encargado que digitalizara su archivo.", "social club", "town hall", "sports team", "family firm"),
  ("F", "cabe", "La maleta es pequeña y el abrigo no _____ dentro.", ["cuesta", "brilla", "suena"],
   "The suitcase is small and the coat doesn't _____ inside.", ["fit", "cost", "shine", "sound"]),
  ("C", "caer en la cuenta", "De golpe [[cayó en la cuenta]]: era la entrada, no cortesía.", "to realise", "to fall asleep", "to lose count", "to give up"),
  ("M",),
  ("C", "encargar", "Le había [[encargado]] que digitalizara su archivo antes de la mudanza.", "to commission", "to forbid", "to explain", "to forgive"),
  ("F", "apunto", "Si no lo _____ en la libreta, se me olvida.", ["pierdo", "rompo", "vendo"],
   "If I don't _____ it in the notebook, I forget it.", ["write down", "lose", "break", "sell"]),
  ("C", "de golpe", "[[De golpe]] cayó en la cuenta y se le calentó la cara.", "all at once", "little by little", "too late", "by chance"),
  ("C", "calentarse la cara", "[[Se le calentó la cara]]: era la entrada, no cortesía.", "to blush", "to feel cold", "to get angry", "to feel sick"),
  ("F", "aburrió", "No había nada que hacer en la sala y se _____.", ["peinó", "mojó", "duchó"],
   "There was nothing to do in the room, and she _____.",["got bored", "combed her hair", "got wet", "showered"]),
  ("C", "despacio", "Tapó el bolígrafo y respondió [[despacio]].", "slowly", "loudly", "rudely", "briefly"),
  ("C", "trámite", "Pidió las llaves como quien despacha un [[trámite]].", "formality", "favour", "complaint", "bargain"),
  ("F", "tapa", "Siempre _____ el bolígrafo para que no se seque.", ["pinta", "dobla", "rompe"],
   "She always _____ the pen so that it doesn't dry out.", ["caps", "paints", "folds", "breaks"]),
  ("C", "quedarse", "La barra preguntaba cuánto [[se quedaba]] y si se aburría.", "to stay", "to rest", "to wait", "to hide"),
  ("C", "entero", "Respondió despacio, [[entera]].", "whole", "tired", "angry", "shy"),
  ("F", "quieto", "Si te mueves, la foto sale mal; quédate _____.", ["flaco", "calvo", "rubio"],
   "If you move, the photo comes out wrong; stay _____.", ["still", "thin", "bald", "blond"]),
  ("C", "sin prisa", "Le avisó [[sin prisa]]: hoy la casa, mañana el papel.", "unhurriedly", "by mistake", "in secret", "on purpose"),
  ("C", "debajo", "Apuntó la hora y, [[debajo]]: mañana pregunto yo.", "underneath", "beside", "behind", "above"),
 ]},
"la-bolsa-como-prueba": {
 "M": [("puesto", "market stall"), ("prueba", "proof"), ("vergüenza", "embarrassment"), ("lista de la compra", "shopping list")],
 "E": [
  ("C", "mercado de abastos", "Llevaba días oyendo pedir en el [[mercado de abastos]].", "covered food market", "shopping centre", "street festival", "bus station"),
  ("F", "ensayó", "Antes de la entrevista, _____ las respuestas delante del espejo.", ["rompió", "vendió", "pintó"],
   "Before the interview, she _____ the answers in front of the mirror.", ["rehearsed", "broke", "sold", "painted"]),
  ("M",),
  ("C", "salirse con la suya", "Salió con la bolsa llena, segura de haberse [[salido con la suya]].", "to get your way", "to lose your temper", "to go home early", "to change your mind"),
  ("C", "tomar por", "Hoy nadie me ha [[tomado por]] turista.", "to mistake for", "to charge as", "to welcome as", "to warn about"),
  ("F", "eligieron", "En la frutería me _____ los melocotones más maduros.", ["pintaron", "contaron", "rompieron"],
   "At the greengrocer's they _____ the ripest peaches for me.", ["picked", "painted", "counted", "broke"]),
  ("C", "en voz baja", "Ensayó la frase [[en voz baja]].", "quietly", "by heart", "in a hurry", "out loud"),
  ("C", "tocarle a alguien", "Llevaba días oyendo pedir; hoy [[le tocaba]] a ella.", "to be someone's turn", "to be someone's fault", "to be someone's gift", "to be someone's secret"),
  ("F", "lleno", "No cabía nada más: el autobús iba _____.", ["barato", "oscuro", "nuevo"],
   "Nothing else would fit: the bus was _____.", ["full", "cheap", "dark", "new"]),
  ("C", "colar", "La conocían desde el primer día: nada que [[colar]].", "to slip past", "to throw away", "to pay back", "to write down"),
  ("C", "redondear", "Presumió con la bolsa como prueba y la cuenta [[redondeada]].", "to round off", "to split", "to double", "to check"),
  ("F", "repartió", "Al llegar a casa, _____ la fruta entre los vecinos.", ["pintó", "apagó", "cerró"],
   "When she got home, she _____ the fruit among the neighbours.", ["shared out", "painted", "switched off", "closed"]),
  ("C", "guardar", "Pues que me [[guarden]] lo que quieran.", "to keep aside", "to throw out", "to sell off", "to give back"),
  ("C", "fresco", "En el puesto, con olor a pescado [[fresco]], le eligieron la fruta.", "fresh", "frozen", "salty", "smoked"),
  ("F", "duró", "La tormenta _____ poco; enseguida salió el sol.", ["pesó", "costó", "midió"],
   "The storm _____ a short time; the sun came out right away.", ["lasted", "weighed", "cost", "measured"]),
  ("C", "de más", "Nadie la miró [[de más]].", "more than necessary", "for a second", "with anger", "from far away"),
  ("C", "de los buenos", "Te guarda tomates [[de los buenos]].", "of the best kind", "of every colour", "from last week", "for the sauce"),
 ]},
"la-sobremesa-se-estira": {
 "M": [("libreta", "notebook"), ("comedor", "dining room"), ("obras", "building works"), ("pregón", "festival opening speech")],
 "E": [
  ("C", "sobremesa", "La [[sobremesa]] del sábado era de las segundas.", "after-meal chat at the table", "nap on the sofa", "dessert at the end", "walk after lunch"),
  ("F", "acercó", "Hacía frío y _____ la silla al fuego.", ["pintó", "lavó", "cosió"],
   "It was cold, and she _____ her chair to the fire.", ["pulled closer", "painted", "washed", "sewed"]),
  ("M",),
  ("C", "soltar", "Hay mesas que no [[sueltan]] a nadie.", "to release", "to feed", "to invite", "to notice"),
  ("C", "costar", "Seguía allí, aunque le [[costaba]].", "to be hard", "to be fun", "to be cheap", "to be late"),
  ("F", "recogieron", "Después de cenar, entre todos _____ la mesa.", ["bebieron", "soñaron", "ganaron"],
   "After dinner, everyone together _____ the table.", ["cleared", "drank", "dreamed", "won"]),
  ("C", "dar igual", "La tarde se estiró hasta la noche; le [[dio igual]].", "to not mind", "to feel sad", "to get angry", "to be surprised"),
  ("C", "por una vez", "[[Por una vez]] no apunto nada.", "for once", "once again", "at once", "once upon a time"),
  ("F", "vacíos", "Todos comieron mucho: los platos volvieron _____.", ["caros", "azules", "nuevos"],
   "Everyone ate a lot: the plates came back _____.", ["empty", "expensive", "blue", "new"]),
  ("C", "nudo", "Le guardaron silla; le subió un [[nudo]] agradecido.", "lump in the throat", "pain in the chest", "smile on the face", "tear in the eye"),
  ("C", "antiguo", "Se discutía de obras y de un pregón [[antiguo]].", "old", "famous", "boring", "short"),
  ("F", "levanto", "Tengo prisa, así que me _____ de la mesa enseguida.", ["peino", "ducho", "visto"],
   "I'm in a hurry, so I _____ from the table right away.", ["get up", "comb my hair", "shower", "get dressed"]),
  ("C", "pronto", "Hay mesas de las que uno se levanta [[pronto]].", "early", "late", "slowly", "again"),
  ("C", "dejar ir", "No apuntó nada, y [[dejó ir]] la tarde.", "to let go of", "to plan ahead", "to fill up", "to cut short"),
  ("F", "agradecido", "Le ayudaron con la mudanza y quedó muy _____.", ["pesado", "peludo", "famoso"],
   "They helped him with the move and he was very _____.", ["grateful", "heavy", "hairy", "famous"]),
  ("C", "de fuera", "Ya era menos [[de fuera]].", "from elsewhere", "on holiday", "in a hurry", "out of breath"),
  ("C", "sin palabras", "Le guardaron silla [[sin palabras]].", "without words", "without money", "without doubt", "without help"),
 ]},
}
