SETS = {
"la-guasa-del-domingo": {
 "M": [("escoba", "broom"), ("tinta", "ink"), ("socio", "club member"), ("letra", "lyrics")],
 "E": [
  ("C", "copla", "En el archivo, las [[coplas]] vivían en cajas.", "carnival song", "love letter", "old photograph", "local newspaper"),
  ("F", "barría", "Cada tarde _____ el suelo de la cocina.", ["leía", "bebía", "oía"],
   "Every afternoon he _____ the kitchen floor.", ["swept", "read", "drank", "heard"]),
  ("M",),
  ("C", "guasa", "Ya le va saliendo la [[guasa]] de aquí.", "teasing humour", "local accent", "bad temper", "good manners"),
  ("C", "picarse", "[[Se picó]] y lo disimuló mal.", "to take offence", "to get sunburnt", "to get hungry", "to fall asleep"),
  ("F", "disimuló", "Le dolió el comentario, pero lo _____ con una sonrisa.", ["cocinó", "alquiló", "planchó"],
   "The comment hurt, but she _____ it with a smile.", ["hid", "cooked", "rented", "ironed"]),
  ("C", "vacilar", "Aquí se [[vacila]] a quien está dentro.", "to tease", "to ignore", "to hire", "to punish"),
  ("C", "pique", "El [[pique]] se le deshizo sin avisar.", "hurt pride", "headache", "appetite", "hiccup"),
  ("F", "graciosa", "Siempre nos hace reír; es la más _____ del grupo.", ["lenta", "pálida", "delgada"],
   "She always makes us laugh; she's the _____ one in the group.", ["funniest", "slowest", "palest", "thinnest"]),
  ("C", "media sonrisa", "Lo admitió con [[media sonrisa]].", "half smile", "loud laugh", "deep sigh", "blank stare"),
  ("C", "mandar", "Quien [[mandaba]] en las letras escribía las nuevas.", "to be in charge", "to be absent", "to be wrong", "to be tired"),
  ("F", "propuso", "Para celebrarlo, _____ una cena en su casa.", ["mordió", "cosió", "peinó"],
   "To celebrate, she _____ a dinner at her place.", ["suggested", "bit", "sewed", "combed"]),
  ("C", "flojo", "Contestó, y le salió [[flojo]].", "weak", "loud", "rude", "clever"),
  ("C", "querido", "Era el más [[querido]] de la casa.", "beloved", "feared", "lazy", "quiet"),
  ("F", "húmedo", "Después de la lluvia, el banco del parque seguía _____.", ["alegre", "famoso", "gordo"],
   "After the rain, the park bench was still _____.", ["damp", "cheerful", "famous", "fat"]),
  ("C", "cortar por el mismo patrón", "Estaban [[cortadas por el mismo patrón]].", "cut from the same cloth", "written in a hurry", "sung out of tune", "kept under lock"),
  ("C", "por encima del hombro", "Lo dijo [[por encima del hombro]], sin dejar de trabajar.", "over her shoulder", "under her breath", "behind his back", "in front of everyone"),
 ]},
"un-mantel-mojado": {
 "M": [("servilleta", "napkin"), ("mantel", "tablecloth"), ("patio", "courtyard"), ("chirigota", "carnival singing group")],
 "E": [
  ("C", "hueco", "Vio el [[hueco]] y se lanzó.", "opening", "danger", "signal", "mistake"),
  ("F", "apiló", "Terminó de fregar y _____ los platos en el armario.", ["besó", "regó", "saludó"],
   "She finished washing up and _____ the plates in the cupboard.", ["stacked", "kissed", "watered", "greeted"]),
  ("M",),
  ("C", "atreverse", "Estaba contenta de [[atreverse]] por fin.", "to dare", "to rest", "to hide", "to leave"),
  ("C", "al pie de la letra", "Había seguido la regla [[al pie de la letra]].", "to the letter", "by accident", "half-heartedly", "in secret"),
  ("F", "mojado", "Llovía tanto que llegó con el pelo _____.", ["dulce", "barato", "triste"],
   "It was raining so hard that he arrived with his hair _____.", ["wet", "sweet", "cheap", "sad"]),
  ("C", "dejarse querer", "Él [[se dejó querer]] e hizo teatro.", "to enjoy the attention", "to fall in love", "to lose patience", "to hide away"),
  ("C", "disparar", "[[Disparó]] la broma sin pensarlo.", "to fire off", "to take back", "to write down", "to whisper"),
  ("F", "doblada", "Guardó la camisa bien _____ en la maleta.", ["frita", "hervida", "asada"],
   "She packed the shirt neatly _____ in the suitcase.", ["folded", "fried", "boiled", "roasted"]),
  ("C", "apretar", "Le [[apretó]] el brazo al pasar.", "to squeeze", "to scratch", "to wave", "to push away"),
  ("C", "lanzarse", "Por fin [[se lanzó]] a contar su broma.", "to go for it", "to hold back", "to apologise", "to calm down"),
  ("F", "afila", "Antes de cortar el pan, siempre _____ el cuchillo.", ["borda", "cose", "riega"],
   "Before cutting the bread, he always _____ the knife.", ["sharpens", "embroiders", "sews", "waters"]),
  ("C", "echar", "Cuando os [[echen]] del local, el candado me lo quedo.", "to throw out", "to welcome", "to pay", "to visit"),
  ("C", "ligero", "A la sobremesa de aquel sábado se llegaba [[ligero]].", "light-hearted", "hungry", "late", "dressed up"),
  ("F", "rescató", "El socorrista _____ al bañista del agua.", ["tejió", "horneó", "exprimió"],
   "The lifeguard _____ the swimmer from the water.", ["rescued", "knitted", "baked", "squeezed"]),
  ("C", "por medio", "Se llegaba con la fruta y el café [[por medio]].", "in between", "at the end", "for free", "on the floor"),
  ("C", "de recuerdo", "El candado me lo quedo yo [[de recuerdo]].", "as a keepsake", "as a joke", "as a loan", "as a bribe"),
 ]},
"ya-no-va-a-cerrar-nada": {
 "M": [("mostrador", "counter"), ("estantería", "shelving unit"), ("ceja", "eyebrow"), ("cinta", "tape")],
 "E": [
  ("C", "dueño", "Al [[dueño]] le han comprado el edificio.", "owner", "tenant", "builder", "neighbour"),
  ("F", "cuelgo", "Tengo un cuadro nuevo y lo _____ en el salón.", ["riego", "frío", "barro"],
   "I have a new painting and I _____ it in the living room.", ["hang", "water", "fry", "sweep"]),
  ("M",),
  ("C", "culpa", "La [[culpa]] se le quedó más pequeña.", "guilt", "fear", "anger", "hunger"),
  ("C", "sin rodeos", "Se lo contó [[sin rodeos]].", "straight out", "in tears", "by letter", "in a whisper"),
  ("F", "desmontar", "Para la mudanza hay que _____ la cama y la mesa.", ["cocinar", "hervir", "freír"],
   "For the move we have to _____ the bed and the table.", ["take apart", "cook", "boil", "fry"]),
  ("C", "trato hecho", "[[Trato hecho]], pero lo cuelgo en mi casa.", "it's a deal", "no way", "thanks anyway", "see you later"),
  ("C", "perdón", "Valía por un [[perdón]] entero.", "apology", "reward", "promise", "warning"),
  ("F", "desapareció", "Busqué mi paraguas por todas partes, pero _____.", ["cantó", "sonrió", "estornudó"],
   "I looked everywhere for my umbrella, but it _____.", ["disappeared", "sang", "smiled", "sneezed"]),
  ("C", "con ganas", "Se rio [[con ganas]].", "wholeheartedly", "nervously", "quietly", "bitterly"),
  ("C", "broma", "La [[broma]] no había sido mala; había sido de otro.", "joke", "lie", "plan", "gift"),
  ("F", "devolver", "Si no te gusta la camisa, la puedes _____ en la tienda.", ["morder", "regar", "hornear"],
   "If you don't like the shirt, you can _____ it at the shop.", ["return", "bite", "water", "bake"]),
  ("C", "conceder", "Eso ya es una copla, [[concedió]] él.", "to admit", "to deny", "to demand", "to complain"),
  ("C", "levantado", "Lo soltó con la ceja [[levantada]].", "raised", "shaved", "painted", "broken"),
  ("F", "valía", "Aquel reloj antiguo _____ más que el coche.", ["dormía", "nadaba", "cantaba"],
   "That old watch was _____ more than the car.", ["worth", "sleeping", "swimming", "singing"]),
  ("C", "de momento", "Y de eso, [[de momento]], solo se ríe él.", "for now", "forever", "by accident", "at last"),
  ("C", "ponerse a", "[[Se puso a]] desmontar la primera estantería.", "to start", "to refuse", "to pretend", "to forget"),
 ]},
}
