SETS = {
"apuntame-la-de-manana": {
 "M": [("churros", "fried dough sticks"), ("taza", "cup"), ("ronda", "round of drinks"), ("estreno", "debut")],
 "E": [
  ("C", "fijo", "A los [[fijos]] nadie les preguntaba qué querían.", "regular customer", "new waiter", "delivery driver", "tourist"),
  ("F", "empujar", "La puerta pesa mucho; hay que _____ fuerte para abrirla.", ["cantar", "llorar", "dormir"],
   "The door is very heavy; you have to _____ hard to open it.", ["push", "sing", "cry", "sleep"]),
  ("M",),
  ("C", "lo de siempre", "¿[[Lo de siempre]], o hoy quieres otra cosa?", "the usual", "the bill", "the menu", "something new"),
  ("C", "orgullo", "El [[orgullo]] le dio risa.", "pride", "shame", "fear", "relief"),
  ("F", "ocupó", "Llegó temprano y _____ el mejor asiento del tren.", ["hirvió", "sembró", "frió"],
   "He arrived early and _____ the best seat on the train.", ["took", "boiled", "sowed", "fried"]),
  ("C", "ya era hora", "Pues [[ya era hora]] de llegar.", "about time", "too early", "just in case", "never again"),
  ("C", "fiarse", "¿Hoy tampoco [[te fías]] de mi máquina?", "to trust", "to fix", "to pay for", "to hate"),
  ("F", "libre", "¿Está _____ este asiento, o espera a alguien?", ["salado", "peludo", "maduro"],
   "Is this seat _____, or are you waiting for someone?", ["free", "salty", "hairy", "ripe"]),
  ("C", "mejor que nunca", "Aquel café le supo [[mejor que nunca]].", "better than ever", "worse than usual", "as always", "too strong"),
  ("C", "asunto", "Unos clientes discutían un [[asunto]] viejo.", "matter", "debt", "joke", "song"),
  ("F", "firma", "Ella lee el contrato y luego lo _____ con su nombre.", ["hornea", "poda", "pela"],
   "She reads the contract and then _____ it with her name.", ["signs", "bakes", "prunes", "peels"]),
  ("C", "tonto", "Ocupó el sitio con el corazón [[tonto]].", "silly", "broken", "cold", "brave"),
  ("C", "detrás", "[[Detrás]], unos clientes discutían en voz alta.", "behind", "upstairs", "outside", "opposite"),
  ("F", "discutían", "Los vecinos _____ a gritos por el ruido de la obra.", ["nadaban", "cosían", "pescaban"],
   "The neighbours were _____ loudly about the building noise.", ["arguing", "swimming", "sewing", "fishing"]),
  ("C", "dar por sabido", "Por fin alguien daba su café [[por sabido]].", "to take as known", "to take as a gift", "to take by force", "to take too long"),
  ("C", "lo suyo", "A los fijos, [[lo suyo]] les llegaba solo.", "their usual", "their change", "their bill", "their coats"),
 ]},
"la-cana-de-marcos": {
 "M": [("pizarra", "blackboard"), ("tiza", "chalk"), ("trapo", "cloth"), ("caña", "small draught beer")],
 "E": [
  ("C", "deuda", "Una [[deuda]] pequeña la ataba al bar.", "debt", "secret", "habit", "favour"),
  ("F", "señaló", "No sabía el nombre, así que _____ el pastel con el dedo.", ["cosió", "planchó", "barrió"],
   "He didn't know the name, so he _____ at the cake with his finger.", ["pointed", "sewed", "ironed", "swept"]),
  ("M",),
  ("C", "a fin de mes", "Aquí se apunta y se paga [[a fin de mes]].", "at the end of the month", "at the start of the day", "every weekend", "in advance"),
  ("C", "deber", "[[Deber dinero]] le molestaba mucho.", "to owe", "to earn", "to lend", "to save"),
  ("F", "secando", "Está en el balcón, _____ la ropa al sol.", ["bebiendo", "leyendo", "cantando"],
   "She's on the balcony, _____ the washing in the sun.", ["drying", "drinking", "reading", "singing"]),
  ("C", "al día", "El que paga [[al día]] es un turista.", "up to date", "in cash", "by card", "late"),
  ("C", "en paz", "Cóbrame y [[en paz]].", "even, settled", "in debt", "in a hurry", "in trouble"),
  ("F", "tranquila", "Ya no tiene prisa; habla con voz _____.", ["amarilla", "cuadrada", "salada"],
   "She's not in a hurry any more; she speaks in a _____ voice.", ["calm", "yellow", "square", "salty"]),
  ("C", "propina", "La ataba al bar mejor que cualquier [[propina]].", "tip", "discount", "receipt", "refund"),
  ("C", "billete", "Insistió en pagar, [[billete]] en mano.", "banknote", "coin", "receipt", "credit card"),
  ("F", "atar", "Antes de correr, hay que _____ bien los cordones.", ["afeitar", "maquillar", "rascar"],
   "Before running, you have to _____ your laces tightly.", ["tie", "shave", "put make-up on", "scratch"]),
  ("C", "raya", "Escribió su nombre con una [[raya]] corta.", "line", "circle", "stain", "crack"),
  ("C", "sonreír", "Ahora ya te fío yo a ti, [[sonrió]] él.", "to smile", "to shout", "to sigh", "to frown"),
  ("F", "corta", "La reunión fue muy _____; terminamos enseguida.", ["salada", "peluda", "dulce"],
   "The meeting was very _____; we finished right away.", ["short", "salty", "hairy", "sweet"]),
  ("C", "prometer", "Era una raya corta que [[prometía]].", "to promise", "to warn", "to forget", "to cost"),
  ("C", "a la vista de todos", "Una deuda pequeña, [[a la vista de todos]].", "in full view of everyone", "behind closed doors", "in a secret place", "out of sight"),
 ]},
"la-cuenta-perdida": {
 "M": [("posavasos", "coaster"), ("aceituna", "olive"), ("tapa", "bar snack"), ("polvo", "dust")],
 "E": [
  ("C", "mirada", "Preguntó con la [[mirada]] y nadie contestó.", "look", "hand", "voice", "smile"),
  ("F", "chocaron", "Para brindar, _____ los vasos y bebieron.", ["doblaron", "pelaron", "cosieron"],
   "To make a toast, they _____ their glasses and drank.", ["clinked", "folded", "peeled", "sewed"]),
  ("M",),
  ("C", "de reojo", "Hubo sonrisas [[de reojo]].", "out of the corner of the eye", "from ear to ear", "with tears", "behind a hand"),
  ("C", "darse por aludido", "Nadie [[se dio por aludido]].", "to take the hint", "to take the blame", "to take a break", "to take a seat"),
  ("F", "alzó", "Para hacer una pregunta, _____ la mano.", ["mordió", "cortó", "vendó"],
   "To ask a question, she _____ her hand.", ["raised", "bit", "cut", "bandaged"]),
  ("C", "de la casa", "Esas tapas son [[de la casa]].", "on the house", "very expensive", "for sharing", "for later"),
  ("C", "encogido", "Hubo miradas y hombros [[encogidos]].", "shrugged", "broad", "bare", "sore"),
  ("F", "agotados", "Después de la mudanza, todos estaban _____ y se fueron a dormir.", ["azules", "redondos", "peludos"],
   "After the move, everyone was _____ and went to bed.", ["exhausted", "blue", "round", "hairy"]),
  ("C", "sin bajar la voz", "La siguiente es mía, avisó, [[sin bajar la voz]].", "without lowering her voice", "without looking up", "without paying", "without a word"),
  ("C", "punta", "Le guiñó un ojo desde la otra [[punta]].", "far end", "corner table", "kitchen door", "back room"),
  ("F", "avisar", "Si vas a llegar tarde, hay que _____ antes.", ["bailar", "dormir", "nadar"],
   "If you're going to be late, you have to _____ beforehand.", ["let people know", "dance", "sleep", "swim"]),
  ("C", "cuenta", "Nadie lleva esa [[cuenta]].", "tab", "tip", "menu", "change"),
  ("C", "bajito", "Lo preguntó [[bajito]], casi sin voz.", "very quietly", "very fast", "very angrily", "very late"),
  ("F", "guiñó", "Para que supiera que era broma, le _____ un ojo.", ["pidió", "prestó", "vendió"],
   "So that she knew it was a joke, he _____ at her.", ["winked", "asked", "lent", "sold"]),
  ("C", "de buen humor", "Bajaron con la peña [[de buen humor]].", "in a good mood", "in a hurry", "in silence", "in trouble"),
  ("C", "cosa de", "Los milagros aquí son [[cosa de la casa]].", "a matter for", "a gift from", "a danger to", "a copy of"),
 ]},
}
