SETS = {
"la-persiana-a-media-tarde": {
 "M": [("kiosco", "newsstand"), ("sello", "stamp"), ("persiana", "metal shutter"), ("montón", "pile")],
 "E": [
  ("C", "fecha", "Miró la [[fecha]] y tardó en contestar.", "date", "price", "headline", "address"),
  ("F", "subrayó", "Para no olvidarla, _____ la fecha en rojo.", ["masticó", "tragó", "sopló"],
   "So as not to forget it, she _____ the date in red.", ["underlined", "chewed", "swallowed", "blew"]),
  ("M",),
  ("C", "a primera hora", "Vuelve el jueves [[a primera hora]].", "first thing", "last thing", "at lunchtime", "at midnight"),
  ("C", "sonar a", "La respuesta [[sonaba a]] puerta cerrada.", "to sound like", "to smell of", "to look like", "to taste of"),
  ("F", "tardó", "El autobús _____ mucho en llegar y perdimos el tren.", ["bailó", "ladró", "sudó"],
   "The bus _____ ages to arrive and we missed the train.", ["took", "danced", "barked", "sweated"]),
  ("C", "al fin", "Pregunta por la caja azul, soltó [[al fin]].", "at last", "at once", "at first", "at random"),
  ("C", "con la palabra en la boca", "La plaza entera se quedó [[con la palabra en la boca]].", "cut off mid-sentence", "with a full mouth", "out of breath", "lost for a name"),
  ("F", "dolía", "Me caí ayer y toda la noche me _____ la rodilla.", ["sobraba", "encantaba", "apetecía"],
   "I fell yesterday and my knee _____ all night.", ["hurt", "was left over", "delighted me", "appealed to me"]),
  ("C", "por eso mismo", "Ya lo sé; [[por eso mismo]].", "for that very reason", "just in case", "even so", "by the way"),
  ("C", "respuesta", "Él tardó en dar una [[respuesta]].", "answer", "question", "visit", "smell"),
  ("F", "falta", "No podemos hacer la tarta porque _____ azúcar.", ["ladra", "tose", "llueve"],
   "We can't make the cake because sugar is _____.", ["missing", "barking", "coughing", "raining"]),
  ("C", "agotarse", "No queda nada, y no porque [[se agotara]].", "to sell out", "to get lost", "to get wet", "to break down"),
  ("C", "atrasado", "¿Guardas también los números [[atrasados]]?", "back-dated", "brand-new", "hand-written", "expensive"),
  ("F", "perdido", "Busqué el gato por todo el barrio; seguía _____.", ["cocido", "pelado", "tostado"],
   "I looked for the cat all over the neighbourhood; it was still _____.", ["lost", "boiled", "peeled", "toasted"]),
  ("C", "seco", "Contestó [[seco]], sin mirarla.", "curt", "cheerful", "tired", "polite"),
  ("C", "a media tarde", "Bajó la persiana [[a media tarde]].", "in mid-afternoon", "at dawn", "late at night", "at noon"),
 ]},
"yo-ya-decidi-una-vez": {
 "M": [("recorte", "clipping"), ("portada", "front page"), ("titular", "headline"), ("almacén", "warehouse")],
 "E": [
  ("C", "susto", "Para que el [[susto]] no se repita.", "scare", "party", "joke", "storm"),
  ("F", "marcó", "Para encontrar la página luego, la _____ con un papel.", ["untó", "ordeñó", "lamió"],
   "To find the page later, she _____ it with a slip of paper.", ["marked", "spread", "milked", "licked"]),
  ("M",),
  ("C", "sin adornos", "Se lo explicó [[sin adornos]], tal como fue.", "plainly", "with jokes", "in a letter", "with tears"),
  ("C", "herida", "La abrió como quien abre una [[herida]] pequeña.", "wound", "door", "letter", "window"),
  ("F", "asintió", "Estaba de acuerdo y _____ con la cabeza.", ["bostezó", "silbó", "roncó"],
   "He agreed and _____ his head.", ["nodded", "yawned", "whistled", "snored"]),
  ("C", "el otro lado", "Ahora veía [[el otro lado]].", "the other side", "the whole story", "the bright side", "the way out"),
  ("C", "callar", "El archivo [[calló]] porque nosotros callamos.", "to go quiet", "to break", "to burn", "to grow"),
  ("F", "gritar", "No hace falta _____; te oigo perfectamente.", ["coser", "tejer", "remar"],
   "There's no need to _____; I can hear you perfectly.", ["shout", "sew", "knit", "row"]),
  ("C", "por primera vez", "El archivo, [[por primera vez]], le pareció una casa.", "for the first time", "for the last time", "once again", "every time"),
  ("C", "bando", "Cada [[bando]] tenía su periódico.", "side", "choir", "family", "shift"),
  ("F", "cuidar", "Cuando se fue de viaje, me pidió _____ sus plantas.", ["morder", "freír", "quemar"],
   "When she went away, she asked me to _____ her plants.", ["look after", "bite", "fry", "burn"]),
  ("C", "venta", "Aquel año se firmó la [[venta]] del primer local.", "sale", "rent", "repair", "opening"),
  ("C", "repetirse", "Estas entran, para que el susto no [[se repita]].", "to happen again", "to be forgotten", "to get worse", "to be solved"),
  ("F", "amable", "La vecina nos ayudó con las cajas; es muy _____.", ["azul", "verde", "gris"],
   "The neighbour helped us with the boxes; she's very _____.", ["kind", "blue", "green", "grey"]),
  ("C", "apartar", "Lo dijo y [[apartó]] la vista.", "to turn away", "to fix", "to lift", "to close"),
  ("C", "partido", "Aquel año la peña quedó [[partida]].", "split", "united", "famous", "ruined"),
 ]},
"una-copla-sin-firma": {
 "M": [("revista", "magazine"), ("inicial", "initial"), ("autor", "author"), ("verso", "line of verse")],
 "E": [
  ("C", "a mano", "Apareció una copla escrita [[a mano]].", "by hand", "by machine", "in pencil", "in secret"),
  ("F", "dibuja", "En clase de arte, _____ un árbol con lápices de colores.", ["bebe", "masca", "riega"],
   "In art class, she _____ a tree with coloured pencils.", ["draws", "drinks", "chews", "waters"]),
  ("M",),
  ("C", "con el corazón en un puño", "Se la llevó [[con el corazón en un puño]].", "with her heart in her mouth", "with a light heart", "with open arms", "with empty hands"),
  ("C", "dejar de", "Hablaba de amigos que [[dejaron de]] hablarse.", "to stop", "to start", "to try", "to pretend"),
  ("F", "pesa", "Esta maleta _____ demasiado para subirla sola.", ["nada", "tose", "llora"],
   "This suitcase _____ too much to carry up alone.", ["weighs", "swims", "coughs", "cries"]),
  ("C", "nombrar", "Pedía perdón sin [[nombrar]] la palabra.", "to name", "to spell", "to change", "to erase"),
  ("C", "notarse", "Nadie la cantó nunca; [[se notaba]] en el doblez.", "to show", "to hide", "to break", "to fade"),
  ("F", "torcido", "El cuadro está _____; hay que ponerlo recto.", ["enfadado", "hambriento", "contento"],
   "The picture is _____; it needs straightening.", ["crooked", "angry", "hungry", "happy"]),
  ("C", "ajeno", "Cuidaba las cosas [[ajenas]] con respeto.", "belonging to others", "very old", "broken", "cheap"),
  ("C", "aire", "La luz dibujaba el polvo en el [[aire]].", "air", "water", "wall", "floor"),
  ("F", "limpio", "Acabo de fregar, así que el suelo está _____.", ["tímido", "celoso", "sordo"],
   "I've just mopped, so the floor is _____.", ["clean", "shy", "jealous", "deaf"]),
  ("C", "respeto", "Trabajaba con el [[respeto]] de las cosas ajenas.", "respect", "speed", "noise", "fear"),
  ("C", "delante", "La puso [[delante]], entre las revistas.", "in front", "underneath", "far away", "inside"),
  ("F", "llevó", "Al salir del restaurante, se _____ las sobras a casa.", ["rascó", "lavó", "secó"],
   "Leaving the restaurant, she _____ the leftovers home.", ["took", "scratched", "washed", "dried"]),
  ("C", "al pie", "[[Al pie]] había una fecha y unas iniciales.", "at the bottom", "at the top", "on the back", "in the margin"),
  ("C", "de lado", "La luz entraba [[de lado]].", "sideways", "straight down", "very slowly", "through the door"),
 ]},
}
