SETS = {
"el-levante-del-jueves": {
 "M": [("bahía", "bay"), ("muelle", "dock"), ("dedo", "finger"), ("atardecer", "sunset")],
 "E": [
  ("C", "patrona", "La [[patrona]] del barco amarró en el muelle.", "skipper", "cook", "passenger", "lifeguard"),
  ("F", "amarró", "Al llegar al puerto, el pescador _____ la barca.", ["trituró", "exprimió", "batió"],
   "When he reached the port, the fisherman _____ the boat.", ["moored", "crushed", "squeezed", "whisked"]),
  ("M",),
  ("C", "hacer una excepción", "Yo de la orilla no paso; hoy [[hago una excepción]].", "to make an exception", "to make a mistake", "to make a deal", "to make a scene"),
  ("C", "ir por", "Esta ronda [[va por]] el que pagó la del viernes.", "to be in honour of", "to be paid by", "to go looking for", "to be instead of"),
  ("F", "arrancó", "Giró la llave y el coche no _____.", ["maulló", "parpadeó", "tartamudeó"],
   "She turned the key and the car didn't _____.", ["start", "meow", "blink", "stutter"]),
  ("C", "cara a", "Dejó el barco [[cara al]] atardecer.", "facing", "behind", "after", "without"),
  ("C", "confesar", "Nadie [[confesó]] y todos bebieron.", "to confess", "to complain", "to pay", "to sing"),
  ("F", "apaga", "Antes de dormir, _____ la luz de la mesilla.", ["muerde", "sala", "ralla"],
   "Before sleeping, she _____ the bedside light.", ["switches off", "bites", "salts", "grates"]),
  ("C", "dorado", "La ciudad se veía [[dorada]].", "golden", "grey", "noisy", "empty"),
  ("C", "señal", "Pagó la [[señal]] del barco.", "deposit", "fine", "tip", "ticket"),
  ("F", "disfrutar", "Hace un día precioso; hay que _____ del sol.", ["dudar", "desconfiar", "burlarse"],
   "It's a lovely day; we have to _____ the sun.", ["enjoy", "doubt", "distrust", "make fun of"]),
  ("C", "borda", "Agarrado a la [[borda]], hizo una excepción.", "side of the boat", "anchor chain", "ship's bell", "life jacket"),
  ("C", "vaivén", "Apagó el motor y dejó el barco al [[vaivén]].", "rocking", "anchor", "harbour", "engine"),
  ("F", "sencillo", "El plan es muy _____: comer y volver pronto.", ["cojo", "zurdo", "pelirrojo"],
   "The plan is very _____: eat and come back early.", ["simple", "lame", "left-handed", "red-haired"]),
  ("C", "agarrarse", "Lo avisó, [[agarrado]] a la borda.", "to hold on", "to lean out", "to slip", "to jump"),
  ("C", "pendiente", "Tenía una frase [[pendiente]].", "pending", "famous", "funny", "forgotten"),
 ]},
"azotea-y-paciencia": {
 "M": [("azotea", "flat rooftop"), ("nevera", "cool box"), ("lona", "tarpaulin"), ("refrán", "proverb")],
 "E": [
  ("C", "levante", "El [[levante]] llegó el jueves.", "east wind", "high tide", "heavy rain", "sea fog"),
  ("F", "aplazó", "Estaba enferma, así que _____ la cita para la semana siguiente.", ["lijó", "embaló", "fregó"],
   "She was ill, so she _____ the appointment to the following week.", ["postponed", "sanded", "packed", "scrubbed"]),
  ("M",),
  ("C", "echar de menos", "No [[echó de menos]] el barco.", "to miss", "to forget", "to sell", "to fear"),
  ("C", "hacer caso", "El viento silbaba y nadie le [[hacía caso]].", "to pay attention", "to answer back", "to give way", "to take shelter"),
  ("F", "volaban", "Hacía tanto viento que las hojas _____ por la calle.", ["maullaban", "tosían", "lloraban"],
   "It was so windy that the leaves were _____ down the street.", ["flying", "meowing", "coughing", "crying"]),
  ("C", "deber una", "Con levante no salgo; [[os debo una]].", "to owe a favour", "to owe money", "to lose a bet", "to break a promise"),
  ("C", "hermanar", "Aguantar el mismo viento [[hermanaba]].", "to bring together", "to divide", "to tire out", "to scare"),
  ("F", "despeinada", "Con tanto viento, llegó a casa _____.", ["casada", "zurda", "famosa"],
   "With so much wind, she got home _____.", ["windswept", "married", "left-handed", "famous"]),
  ("C", "de andar por casa", "Sonaba a refrán [[de andar por casa]].", "homespun", "very old", "foreign", "rude"),
  ("C", "viento", "La ciudad aguantaba el mismo [[viento]].", "wind", "weight", "noise", "heat"),
  ("F", "estropea", "La lluvia siempre _____ los planes de playa.", ["bautiza", "peina", "sazona"],
   "The rain always _____ beach plans.", ["ruins", "baptises", "combs", "seasons"]),
  ("C", "sujetar", "Las servilletas volaban a menos que alguien las [[sujetara]].", "to hold down", "to fold up", "to throw away", "to wash"),
  ("C", "llorar", "La tarde no volvería, y nadie la [[lloró]].", "to mourn", "to forget", "to celebrate", "to repeat"),
  ("F", "silbaba", "Mientras trabajaba, _____ una canción alegre.", ["rallaba", "horneaba", "podaba"],
   "While he worked, he _____ a cheerful song.", ["whistled", "grated", "baked", "pruned"]),
  ("C", "puntual", "Llegó [[puntual]], como todo lo que estropea planes.", "on time", "too late", "by surprise", "uninvited"),
  ("C", "arriba", "Desde [[arriba]], la ciudad aguantaba el mismo viento.", "up above", "down below", "far away", "inside"),
 ]},
"la-herramienta-seria": {
 "M": [("lápiz", "pencil"), ("herramienta", "tool"), ("bolso", "handbag"), ("parte", "weather report")],
 "E": [
  ("C", "a lápiz", "Aquí una fecha se escribe [[a lápiz]].", "in pencil", "in ink", "in capitals", "in red"),
  ("F", "encendió", "Entró a oscuras y _____ la lámpara del salón.", ["abrochó", "amasó", "desplumó"],
   "She came in in the dark and _____ the living-room lamp.", ["switched on", "buttoned", "kneaded", "plucked"]),
  ("M",),
  ("C", "de pronto", "Y [[de pronto]] entendió su primera semana.", "suddenly", "slowly", "finally", "again"),
  ("C", "amanecer", "¿Y si el viernes [[amanece]] con poniente?", "to dawn", "to end", "to rain", "to cool down"),
  ("F", "cargamos", "Para la mudanza, _____ las cajas en el camión.", ["rallamos", "tejimos", "remamos"],
   "For the move, we _____ the boxes onto the lorry.", ["loaded", "grated", "knitted", "rowed"]),
  ("C", "negociar", "Aquí las fechas [[se negocian]] con el viento.", "to negotiate", "to forget", "to celebrate", "to count"),
  ("C", "mudo", "Su calendario se quedó [[mudo]].", "silent", "empty", "broken", "full"),
  ("F", "verde", "No te comas ese plátano; todavía está _____.", ["tímido", "celoso", "educado"],
   "Don't eat that banana; it's still _____.", ["green", "shy", "jealous", "polite"]),
  ("C", "a medias", "Escuchó [[a medias]], esperando que acabara.", "only half", "very carefully", "twice", "in silence"),
  ("C", "poniente", "El viernes llegó limpio, con luz de [[poniente]].", "west wind", "east wind", "low tide", "full moon"),
  ("F", "escuchó", "Puso la radio y _____ las noticias en silencio.", ["peló", "sembró", "bordó"],
   "She put the radio on and _____ the news in silence.", ["listened to", "peeled", "sowed", "embroidered"]),
  ("C", "repasar", "La fecha [[se repasó]] con bolígrafo.", "to go over again", "to rub out", "to translate", "to forget"),
  ("C", "saludar", "Qué valiente vienes hoy, [[saludó]] él.", "to greet", "to complain", "to leave", "to apologise"),
  ("F", "valiente", "Saltó al agua para ayudarlo; fue muy _____.", ["azul", "gris", "marrón"],
   "He jumped into the water to help; he was very _____.", ["brave", "blue", "grey", "brown"]),
  ("C", "serio", "En esta ciudad, era la herramienta [[seria]].", "serious, reliable", "old-fashioned", "expensive", "borrowed"),
  ("C", "quedar por", "Todavía [[quedaba por]] elegir el día de la mudanza.", "to remain to be", "to have already been", "to be impossible to", "to be ready to"),
 ]},
}
