SETS = {
"vuelva-cuando-quiera": {
 "M": [("librería", "bookshop"), ("campanilla", "little bell"), ("escalera", "ladder"), ("escudo", "crest")],
 "E": [
  ("C", "de segunda mano", "Era una librería [[de segunda mano]].", "second-hand", "brand-new", "very expensive", "closed down"),
  ("F", "reconoció", "Llevaba años sin verla, pero la _____ al instante.", ["enjabonó", "abanicó", "enhebró"],
   "He hadn't seen her for years, but he _____ her instantly.", ["recognised", "lathered", "fanned", "threaded"]),
  ("M",),
  ("C", "bajo el brazo", "Salió con el libro [[bajo el brazo]].", "under her arm", "in her hand", "on her head", "in her bag"),
  ("C", "lomo", "Paseó la mirada por los [[lomos]].", "spine (of a book)", "price tag", "front cover", "bookmark"),
  ("F", "vender", "Se mudan al extranjero y quieren _____ el piso.", ["podar", "ordeñar", "tostar"],
   "They're moving abroad and want to _____ the flat.", ["sell", "prune", "milk", "toast"]),
  ("C", "respirar", "Miraron los libros como si [[respiraran]].", "to breathe", "to sleep", "to shout", "to burn"),
  ("C", "por ahí", "Si es que le queda algo [[por ahí]].", "around somewhere", "for free", "by post", "on the top shelf"),
  ("F", "redonda", "La mesa no tiene esquinas; es _____.", ["celosa", "calva", "miope"],
   "The table has no corners; it's _____.", ["round", "jealous", "bald", "short-sighted"]),
  ("C", "clienta", "Era una [[clienta]] sin encargo.", "customer", "owner", "teacher", "thief"),
  ("C", "exlibris", "Los libros llevaban un [[exlibris]] redondo.", "bookplate", "coffee stain", "library fine", "torn page"),
  ("F", "movía", "Estaba tan asustado que no se _____ del sitio.", ["bañaba", "vestía", "rascaba"],
   "He was so scared that he didn't _____ from the spot.", ["move", "bathe", "get dressed", "scratch"]),
  ("C", "guarda", "Llevaban un exlibris redondo en la [[guarda]].", "endpaper", "spine", "dust jacket", "last chapter"),
  ("C", "cuesta", "La librería de la [[cuesta]] olía a papel.", "slope", "square", "coast", "market"),
  ("F", "dormido", "Está tan cansado que se ha quedado _____ en el sofá.", ["cuadrado", "oxidado", "hervido"],
   "He's so tired that he's fallen _____ on the sofa.", ["asleep", "square", "rusty", "boiled"]),
  ("C", "pasear", "[[Paseó]] la mirada por los libros.", "to let wander", "to fix", "to lower", "to close"),
  ("C", "por fin", "Contestó la librera, bajando [[por fin]].", "at last", "too soon", "by mistake", "again"),
 ]},
"el-tomo-aparte": {
 "M": [("tomo", "volume"), ("dedicatoria", "dedication"), ("apretón", "handshake"), ("cifra", "figure")],
 "E": [
  ("C", "propuesta", "Volvió con una [[propuesta]].", "proposal", "complaint", "apology", "bill"),
  ("F", "enseñó", "Orgulloso, nos _____ las fotos de su casa nueva.", ["amasó", "ralló", "hiló"],
   "Proudly, he _____ us the photos of his new house.", ["showed", "kneaded", "grated", "spun"]),
  ("M",),
  ("C", "con cara de", "Las repasó [[con cara de examen]].", "with the look of", "with the smell of", "in the shape of", "in the name of"),
  ("C", "volver a", "Lo abrió, lo pensó y lo [[volvió a]] cerrar.", "to do again", "to stop doing", "to try to", "to refuse to"),
  ("F", "agachó", "La moneda se cayó y se _____ para cogerla.", ["casó", "vacunó", "graduó"],
   "The coin fell and she _____ to pick it up.", ["bent down", "got married", "got vaccinated", "graduated"]),
  ("C", "dando vueltas", "La palabra se quedó [[dando vueltas]] toda la tarde.", "going round in her head", "written on the wall", "lost in the post", "hidden in a drawer"),
  ("C", "a la antigua", "El trato se cerró [[a la antigua]].", "the old way", "by email", "in a rush", "in secret"),
  ("F", "manuscrita", "No es un correo; es una carta _____, con su letra.", ["oxidada", "hervida", "calva"],
   "It's not an email; it's a _____ letter, in her own writing.", ["handwritten", "rusty", "boiled", "bald"]),
  ("C", "uno a uno", "Los conté [[uno a uno]].", "one by one", "all at once", "twice over", "roughly"),
  ("C", "tanda", "Los libros salieron por [[tandas]].", "batch", "colour", "size", "author"),
  ("F", "envolvió", "Para el cumpleaños, _____ el regalo en papel brillante.", ["fumó", "rastrilló", "ordeñó"],
   "For the birthday, she _____ the present in shiny paper.", ["wrapped", "smoked", "raked", "milked"]),
  ("C", "promesa", "Una pared no es una [[promesa]], pero se le parece.", "promise", "threat", "gift", "lie"),
  ("C", "forrar", "Sacó un tomo aparte, [[forrado]] a mano.", "to cover (a book)", "to tear", "to sign", "to glue shut"),
  ("F", "sacó", "Abrió la nevera y _____ una botella de agua.", ["afiló", "cepilló", "bordó"],
   "She opened the fridge and _____ a bottle of water.", ["took out", "sharpened", "brushed", "embroidered"]),
  ("C", "cruzado", "Escuchó con los brazos [[cruzados]].", "crossed", "raised", "broken", "open"),
  ("C", "aparte", "Al final, sacó un tomo [[aparte]], forrado a mano.", "set apart", "brand-new", "very heavy", "damaged"),
 ]},
"la-balda-del-medio": {
 "M": [("carretilla", "handcart"), ("balda", "shelf"), ("pared", "wall"), ("firma", "signature")],
 "E": [
  ("C", "custodia", "Entendió de golpe la [[custodia]] callada.", "safekeeping", "sale", "loss", "theft"),
  ("F", "cruzar", "Mira bien antes de _____ la calle.", ["freír", "ordeñar", "bordar"],
   "Look carefully before you _____ the street.", ["cross", "fry", "milk", "embroider"]),
  ("M",),
  ("C", "tender la mano", "Él le [[tendió la mano]].", "to hold out a hand", "to wave goodbye", "to raise a fist", "to clap"),
  ("C", "sin pedir permiso", "Lo dejó en la balda del medio, [[sin pedir permiso]].", "without asking permission", "without saying thanks", "without looking back", "without paying"),
  ("F", "invitó", "Cumplía años y nos _____ a todos a cenar.", ["vacunó", "afeitó", "tatuó"],
   "It was his birthday and he _____ us all to dinner.", ["invited", "vaccinated", "shaved", "tattooed"]),
  ("C", "en voz alta", "La peña me enseñó a leer [[en voz alta]].", "aloud", "silently", "fast", "in secret"),
  ("C", "perderse", "La compré yo, para que no [[se perdiera]].", "to get lost", "to get wet", "to get bored", "to get married"),
  ("F", "enorme", "La casa tiene muchísimas habitaciones; es _____.", ["joven", "alegre", "feliz"],
   "The house has loads of rooms; it's _____.", ["huge", "young", "cheerful", "happy"]),
  ("C", "comienzo", "Había olor a madera nueva y a [[comienzo]].", "new beginning", "old age", "goodbye", "paint"),
  ("C", "permiso", "Nadie le había dado [[permiso]].", "permission", "money", "advice", "time"),
  ("F", "añadió", "Probó la sopa y le _____ un poco de sal.", ["prestó", "alquiló", "dedicó"],
   "She tasted the soup and _____ a little salt.", ["added", "lent", "rented", "dedicated"]),
  ("C", "negar", "Nadie se lo habría [[negado]].", "to refuse", "to allow", "to sell", "to explain"),
  ("C", "último", "Ella llegó la [[última]], con el tomo.", "last", "first", "alone", "early"),
  ("F", "callado", "No dijo nada en toda la cena; estuvo muy _____.", ["oxidado", "pelado", "maduro"],
   "He didn't say a word all dinner; he was very _____.", ["quiet", "rusty", "peeled", "ripe"]),
  ("C", "con las dos manos", "Lo abrió [[con las dos manos]].", "with both hands", "with one finger", "without looking", "with gloves on"),
  ("C", "por el mundo", "La compró para que no se perdiera [[por el mundo]].", "out in the world", "at home", "in the post", "in a drawer"),
 ]},
}
