SETS = {
"una-agenda-de-desconocida": {
 "M": [("andén", "platform"), ("maleta", "suitcase"), ("paquete", "parcel"), ("agenda", "planner")],
 "E": [
  ("C", "de toda la vida", "Pides sin hablar, como los [[de toda la vida]].", "lifelong", "brand-new", "part-time", "out of town"),
  ("F", "funciona", "El ascensor no _____; tenemos que subir andando.", ["bosteza", "maúlla", "parpadea"],
   "The lift doesn't _____; we'll have to walk up.", ["work", "yawn", "meow", "blink"]),
  ("M",),
  ("C", "sin abrir la boca", "Pidió los cafés [[sin abrir la boca]].", "without saying a word", "without paying", "without sitting down", "without a smile"),
  ("C", "hojear", "Lo [[hojeó]] como la agenda de una desconocida.", "to leaf through", "to tear up", "to throw away", "to sign"),
  ("F", "traigo", "Si vienes a cenar, yo _____ el postre.", ["afilo", "cepillo", "lijo"],
   "If you come to dinner, I'll _____ the dessert.", ["bring", "sharpen", "brush", "sand"]),
  ("C", "dar las gracias", "Le [[dio las gracias]] de verdad.", "to say thank you", "to say sorry", "to say goodbye", "to say no"),
  ("C", "talla", "La vida de antes era de otra [[talla]].", "size", "colour", "price", "country"),
  ("F", "abrazaron", "Hacía años que no se veían y se _____ en la estación.", ["afeitaron", "maquillaron", "graduaron"],
   "They hadn't seen each other for years and they _____ at the station.", ["hugged", "shaved", "put on make-up", "graduated"]),
  ("C", "por si", "Te lo traigo [[por si]] lo echabas de menos.", "in case", "because", "although", "unless"),
  ("C", "casilla", "Cada hora tenía su [[casilla]].", "box, slot", "alarm", "colour", "page"),
  ("F", "olvidado", "Volví al bar a por el paraguas _____.", ["hambriento", "celoso", "educado"],
   "I went back to the bar for the _____ umbrella.", ["forgotten", "hungry", "jealous", "polite"]),
  ("C", "bienvenida", "Era el comité de [[bienvenida]].", "welcome", "farewell", "birthday", "wedding"),
  ("C", "desconocido", "Era como la agenda de una [[desconocida]].", "stranger", "neighbour", "cousin", "colleague"),
  ("F", "rara", "Hoy está muy _____: no ha dicho ni una palabra.", ["cuadrada", "oxidada", "hervida"],
   "She's being very _____ today: she hasn't said a word.", ["strange", "square", "rusty", "boiled"]),
  ("C", "de sobra", "La esperó con tiempo [[de sobra]].", "to spare", "too little", "by the hour", "in the rain"),
  ("C", "de verdad", "Le dio las gracias [[de verdad]].", "truly", "jokingly", "coldly", "briefly"),
 ]},
"amanece-con-poniente": {
 "M": [("camión", "lorry"), ("cajón", "crate"), ("regalo", "gift"), ("descuido", "careless moment")],
 "E": [
  ("C", "tal y como", "Amaneció con poniente, [[tal y como]] estaba negociado.", "just as", "unlike", "even though", "before"),
  ("F", "recordó", "Antes de irse, me _____ que apagara la luz.", ["mordió", "peinó", "rascó"],
   "Before leaving, she _____ me to switch off the light.", ["reminded", "bit", "combed", "scratched"]),
  ("M",),
  ("C", "quedarse atrás", "Nadie [[se quedaba atrás]].", "to be left behind", "to arrive early", "to be in charge", "to feel sad"),
  ("C", "hacer falta", "No [[hacía falta]] decir adiós.", "to be necessary", "to be polite", "to be allowed", "to be possible"),
  ("F", "curó", "La herida tardó semanas, pero al final se _____.", ["duchó", "casó", "bañó"],
   "The wound took weeks, but in the end it _____.", ["healed", "showered", "got married", "bathed"]),
  ("C", "de visita", "[[De visita]], cargó una caja en los brazos.", "on a visit", "on duty", "on strike", "on her way out"),
  ("C", "temer", "[[Temía]] que el día sonara a funeral.", "to fear", "to hope", "to decide", "to promise"),
  ("F", "sudada", "Después de correr, llegó a casa _____ y con sed.", ["pelirroja", "bizca", "rubia"],
   "After running, she got home _____ and thirsty.", ["sweaty", "red-haired", "cross-eyed", "blonde"]),
  ("C", "oírse", "Lo cerró despacio, y el clic [[se oyó]] entero.", "to be heard", "to be seen", "to be broken", "to be lost"),
  ("C", "funeral", "Temía que el día sonara a [[funeral]].", "funeral", "party", "wedding", "holiday"),
  ("F", "mudarse", "Encontró trabajo en otra ciudad y tuvo que _____.", ["estirarse", "sonarse", "rascarse"],
   "She found a job in another city and had to _____.", ["move house", "stretch", "blow her nose", "scratch herself"]),
  ("C", "eco", "Sonó a bromas con [[eco]] en una escalera.", "echo", "music", "smoke", "dust"),
  ("C", "clic", "Cerró el candado, y el [[clic]] sonó entero.", "click", "bang", "scream", "ring"),
  ("F", "contenta", "Aprobó el examen y está muy _____.", ["agria", "rallada", "hueca"],
   "She passed the exam and she's very _____.", ["happy", "sour", "grated", "hollow"]),
  ("C", "informar", "En esta casa el que mira, carga, [[informó]] él.", "to inform", "to beg", "to deny", "to ask"),
  ("C", "en los brazos", "Cargó una caja [[en los brazos]].", "in her arms", "on her back", "on a trolley", "by the handle"),
 ]},
"me-lo-he-ganado": {
 "M": [("pintura", "paint"), ("clavo", "nail"), ("estribillo", "chorus"), ("aplauso", "applause")],
 "E": [
  ("C", "esta vez", "[[Esta vez]] no apuntó nada.", "this time", "every time", "next time", "last time"),
  ("F", "estrenó", "Para la boda, _____ unos zapatos nuevos.", ["enhebró", "abanicó", "rastrilló"],
   "For the wedding, she _____ a new pair of shoes.", ["wore for the first time", "threaded", "fanned", "raked"]),
  ("M",),
  ("C", "de memoria", "La copla ya se la sabía [[de memoria]].", "by heart", "by chance", "in writing", "in part"),
  ("C", "el que se pique", "Hay copla nueva; [[el que se pique]], que se aguante.", "whoever takes offence", "whoever arrives late", "whoever sings best", "whoever pays"),
  ("F", "subió", "Para ver el desfile, se _____ a una silla.", ["sonó", "desmayó", "empapó"],
   "To see the parade, he _____ onto a chair.", ["climbed", "blew his nose", "fainted", "got soaked"]),
  ("C", "ganarse", "Me lo [[he ganado]], entonces.", "to earn", "to lose", "to steal", "to borrow"),
  ("C", "hacerte esperar", "En esta casa había que [[hacerte esperar]].", "to make you wait", "to make you laugh", "to make you leave", "to make you pay"),
  ("F", "desdobló", "Sacó el mapa del bolsillo y lo _____ sobre la mesa.", ["tragó", "sopló", "lamió"],
   "He took the map out of his pocket and _____ it on the table.", ["unfolded", "swallowed", "blew", "licked"]),
  ("C", "retratar", "El primer verso ya la [[retrataba]].", "to portray", "to insult", "to forget", "to hide"),
  ("C", "resumen", "Esa diferencia le pareció el [[resumen]] del año.", "summary", "beginning", "secret", "mistake"),
  ("F", "servidos", "Los platos ya están _____; siéntate a comer.", ["dormidos", "casados", "peinados"],
   "The dishes are already _____; sit down and eat.", ["served", "asleep", "married", "combed"]),
  ("C", "diferencia", "A ella esa [[diferencia]] le pareció el resumen del año.", "difference", "silence", "danger", "weight"),
  ("C", "reconocerse", "Tardó un verso en [[reconocerse]].", "to recognise yourself", "to get dressed", "to calm down", "to sit down"),
  ("F", "contaba", "Cada noche le _____ un cuento para dormir.", ["freía", "barría", "cosía"],
   "Every night she _____ him a bedtime story.", ["told", "fried", "swept", "sewed"]),
  ("C", "luz", "El local nuevo estrenó [[luz]] y olor a pintura.", "light", "furniture", "music", "staff"),
  ("C", "pedir silencio", "Subido a una silla, [[pidió silencio]].", "to ask for quiet", "to ask for help", "to ask for a drink", "to ask for the bill"),
 ]},
}
