"""Los trozos que aparecieron al apretar el troceador al tope de 8 palabras.

Se anaden a los ficheros que ya existen; no se toca lo que ya estaba
traducido, porque esos trozos no han cambiado.
"""
import json
import pathlib

DIR = pathlib.Path("scripts/_pta2ctx")

NUEVOS = {
    "chove-sobre-a-excursao": {
        "chove três dias e para": "it rains three days and stops",
        "Hoje está feio": "Today it looks bad",
        "Renata decide não desistir": "Renata decides not to give up",
        "paga mais uma noite": "and pays for another night",
    },
    "a-caixa-que-nao-chegou": {
        "eu sei": "I know",
        "Renata escuta e repete em voz alta": "Renata listens and repeats it out loud",
        "Amanhã a caixa chega": "Will the box come tomorrow",
        "Não sei": "I do not know",
    },
    "um-livro-de-contos": {
        "Ler alto é mais fácil quando alguém corrige": "Reading aloud is easier when somebody corrects you",
        "Renata recusa mais uma vez": "Renata refuses once more",
        "e a senhora me diz onde eu erro": "and you tell me where I get it wrong",
        "Ela discute o preço": "She argues about the price",
    },
    "ninguem-sabe-do-exame": {
        "Você quer ensinar idioma": "Do you want to teach a language",
        "Eles saem": "They go out",
        "ensaiam a prova oral na escada": "and rehearse the oral test on the steps",
        "Não vou conseguir": "I am not going to manage it",
        "e aprender é o que você faz melhor": "and learning is what you do best",
        "Gilson é o único aluno dali": "Gilson is the only student there",
        "ela não conhece de sala": "she does not know from class",
        "mas conhece o rapaz o bastante para acreditar": "but she knows him well enough to believe it",
    },
    "o-frasco-mais-barato": {
        "ontem dormiu mal": "yesterday she slept badly",
        "hoje não vira a cabeça": "today she cannot turn her head",
        "uma mulher": "a woman",
        "está ali desde": "who has been there since",
        "a loja abriu": "the shop opened",
        "Onde dói": "Where does it hurt",
        "Renata procura a palavra": "Renata searches for the word",
        "e a saúde inteira dela": "and her whole health",
        "depende de uma cama": "depends on a bed",
        "ainda não viu": "she has not seen yet",
    },
    "o-colchao-vence": {
        "À uma da manhã a": "At one in the morning her",
        "barriga entra na conta": "belly joins in",
        "Ela não sabe se é": "She cannot tell whether it is",
        "o estômago ou o nervoso": "her stomach or her nerves",
        "Nilza sai de trás do balcão": "Nilza comes out from behind the counter",
        "explica devagar": "and explains slowly",
        "Falta pouco pro sol": "There is not long until the sun",
        "Renata volta": "Renata goes back",
        "faz o": "does what",
        "ouviu e sente o corpo pesar": "she was told and feels her body grow heavy",
    },
    "nilza-fecha-vinte-minutos": {
        "É pancada": "It is just a knock",
        "No pano há sangue seco": "There is dry blood on the cloth",
        "Vai que eu cuido do balcão": "Go, I will look after the counter",
        "Eu prefiro não fechar": "I would rather not close",
        "Eu fico no balcão e não vendo nada": "I will stay at the counter and sell nothing",
        "As duas discutem em voz baixa": "The two of them argue in low voices",
        "protegido por uma tala": "held in a splint",
        "e Renata serve um café fraco e ruim": "and Renata serves a weak, bad coffee",
        "as duas bebem": "that they both drink",
    },
    "a-panela-que-grudou": {
        "E o cogumelo": "And the mushroom",
        "mas serve": "but it will do",
        "E o milho": "And the corn",
        "O ar fica abafado": "The air turns stuffy",
        "ninguém encosta na panela": "and nobody touches the pan",
        "A regra vale ou não vale": "Does the rule hold or not",
    },
    "no-meio-do-rio": {
        "Desceu chuva a noite inteira lá de cima": "Rain came down all night from up there",
        "A água passa rápida pelo casco": "The water runs fast along the hull",
    },
    "antes-do-sol": {
        "Combinei com o rio": "I arranged it with the river",
        "Ela ri pela primeira vez em três dias": "She laughs for the first time in three days",
        "Só areia e vento": "Only sand and wind",
        "E você fica": "And do you stay",
    },
    "tres-guiches-abertos": {
        "Cleide vende passagens ali desde": "Cleide has sold tickets there since",
        "a estação abriu": "the station opened",
        "Mudou em maio": "It changed in May",
        "Renata não sabe o": "Renata does not know what",
        "fazer com um papel": "to do with a paper",
        "já não vale": "that is no longer valid",
        "ao meio-dia": "at midday",
        "Mas tem o último de hoje": "But there is the last one today",
        "Renata quer o de hoje": "Renata wants today's one",
        "pergunta quanto custa": "and asks how much it costs",
        "O ônibus sai da cidade": "The bus leaves the city",
        "entra na rodovia": "and joins the highway",
    },
    "o-homem-que-ronca-atras": {
        "O motorista liga a seta": "The driver puts the indicator on",
        "ninguém vem atrás": "and nobody is behind",
        "Ela se levanta duas vezes": "She stands up twice",
        "senta de novo": "and sits back down",
        "O homem se move sem acordar": "The man shifts without waking",
        "ela passa": "and she gets past",
        "A estrada é longa": "The road is long",
        "o ônibus vai lento": "and the bus goes slowly",
        "Depois a estrada abre": "After that the road opens up",
        "eu ganho meia hora": "and I gain half an hour",
        "A senhora viaja muito": "Do you travel a lot",
        "Faz dois meses": "For two months now",
        "E o senhor": "And you",
        "Faz dezoito anos": "Eighteen years now",
        "Renata dorme vinte minutos": "Renata sleeps twenty minutes",
        "acorda com a buzina": "and wakes to the horn",
    },
    "volto-pelo-caderno": {
        "Da senhora ou minha": "Yours or mine",
        "Ele aponta a motocicleta": "He points at the motorcycle",
        "mas ninguém mexeu": "but nobody touched anything",
        "Entra no primeiro por engano": "She gets into the first one by mistake",
        "Faz dois meses um rapaz": "Two months ago a young man",
        "escreveu ali a primeira palavra": "wrote the first word in it",
    },
    "quinze-folhas-e-barbante": {
        "Wilson lê o pedido do cliente": "Wilson reads the client's request",
        "por cima do ombro dela": "over her shoulder",
        "E o seu teclado está colado de café": "And your keyboard is sticky with coffee",
        "Imprime aqui": "Print it here",
        "Pesado assim não cabe em envelope": "This heavy it will not fit in an envelope",
        "Tem saco": "Have you got a bag",
        "que eu vendo por um real": "which I sell for one real",
        "Ele empresta a tesoura": "He lends her the scissors",
        "No correio a fila está aberta": "At the post office the queue is open",
        "até as cinco em ponto": "until five on the dot",
        "A caixinha do balcão diz": "The little sign on the counter says",
        "hoje não sai nada para fora do país": "nothing leaves the country today",
    },
    "o-carregador-queimou": {
        "e o carregador do notebook dela": "and her laptop charger",
        "parou de funcionar ontem à noite": "stopped working last night",
        "Wilson trabalha na loja de": "Wilson works in the shop of",
        "informática da rua do meio": "computers on the middle street",
        "e liga o computador dela": "and plugs her computer in",
        "na tomada da bancada": "at the socket on the counter",
        "mas custa o triplo": "but it costs three times as much",
        "Renata pediu outro pela internet": "Renata ordered another one online",
        "se a chuva deixar": "if the rain allows it",
        "Segunda é tarde demais": "Monday is too late",
    },
    "quatro-meses-nao-dois": {
        "Renata tem dez minutos": "Renata has ten minutes",
        "o emprego depende disso": "and her job depends on it",
        "você faz o dobro": "and you do twice the work",
        "Ou a gente cobra menos do cliente": "Or we charge the client less",
        "Renata faz uma pergunta": "Renata asks a question",
        "oferece uma terceira saída": "and offers a third way out",
        "Ninguém responde na hora": "Nobody answers straight away",
        "e o silêncio dura o": "and the silence lasts longer than",
        "ela não aguenta": "she can bear",
        "Pela primeira vez o real": "For the first time the real thing",
        "não era o dinheiro": "was not the money",
    },
    "ninguem-lava-nada-aqui": {
        "Na casa coletiva de Jericoacoara a": "In the shared house in Jericoacoara the",
        "cozinha é de todo mundo": "kitchen belongs to everybody",
        "Ela guarda os garfos e organiza o espaço": "She puts the forks away and sorts out the space",
        "A pia fica vazia": "The sink is left empty",
        "o cheiro sobe logo": "and the smell rises soon after",
    },
    "feijao-salgado-demais": {
        "prova a colher quando a": "she tastes the spoon when the",
        "mesa já está posta": "table is already laid",
        "Ela fala baixinho": "She says it quietly",
        "larga a mochila": "drops his backpack",
        "entra sem tirar o boné": "and comes in without taking off his cap",
        "A batata sai salgada": "The potato comes out salty",
        "o resto sai comível": "and the rest comes out edible",
        "Não estava gostoso": "It was not tasty",
    },
    "nada-aqui-serve": {
        "Tudo na mala está molhado": "Everything in the suitcase is wet",
        "da chuva do ônibus": "from the rain on the bus",
        "Faz três invernos que isso está aqui": "That has been here for three winters",
        "Quanto custa": "How much is it",
        "Cansa mais chegar com frio do": "Arriving cold wears you out more than",
        "viajar doze horas": "twelve hours of travelling",
    },
    "uma-lampada-so": {
        "Às seis Renata desce a": "At six Renata walks down on",
        "pé até a lavanderia": "foot to the laundry",
        "Neuza serve chá numa caneca": "Neuza serves tea in a mug",
        "macia de tanto uso": "worn soft with use",
        "suéter grosso por cima": "a thick jumper on top",
        "E o tapete em cima dos pés": "And the rug over your feet",
        "A senhora mora aqui há muito tempo": "Have you lived here long",
        "mas aqui eu sei onde tudo está": "but here I know where everything is",
        "Renata anota a receita do frio no caderno": "Renata writes the recipe for the cold in her notebook",
        "No escuro a janela amarela": "In the dark the yellow window",
        "deixa passar uma faixa roxa": "lets a purple strip through",
    },
    "a-ultima-pagina": {
        "Renata leva o suéter até": "Renata takes the jumper to",
        "a lavanderia de Neuza": "Neuza's laundry",
        "Renata olha a saia comprida": "Renata watches the long skirt",
        "passa lá fora": "going by outside",
        "A senhora escreveu tudo": "Did you write it all down",
        "Quase tudo": "Almost all of it",
        "que é melhor": "which is better",
        "Eu volto e visito a senhora": "I will come back and visit you",
        "Mas volta": "But come",
        "Elas brincam com isso um tempo": "They joke about it for a while",
        "Outra passa de tênis vermelhos com um balão": "Another goes past in red trainers with a balloon",
        "e ama esta rua como": "and she loves this street like",
        "quem já esteve aqui": "somebody who has been here before",
    },
}

n = 0
for slug, extra in NUEVOS.items():
    f = DIR / f"{slug}.json"
    d = json.load(open(f, encoding="utf-8"))
    d.update(extra)
    json.dump(d, open(f, "w", encoding="utf-8"), ensure_ascii=False, indent=2)
    n += len(extra)
print(f"trozos anadidos: {n}")
