# Trozo MINIMO con sentido, no la clausula entera: el catalogo va en 4 de mediana
# y 6 en el p90. `g` solo se pone cuando la historia usa OTRO sentido que el mapa
# global (enseñado = shown aqui, taught alli).
import json, re, io
EX={"celia","una","el","la","un","emilio","los","cuatro","dos","tres","uno","las","once","berta"}
S={
"celia-no-dice-que-si":[
 ("Celia no dice que sí","Celia does not say yes",{}),
 ("una traductora de Madrid","a translator from Madrid",{}),
 ("se ha mudado a Granada","has moved to Granada",{}),
 ("en el sur de España","in the south of Spain",{}),
 ("la habitación que le han enseñado","the room they have shown her",{"enseñado":"shown"}),
 ("en un cuarto sin ascensor","on a fourth floor with no lift",{}),
 ("sobre una tienda","above a shop",{}),
 ("el casero","the landlord",{}),
 ("la espera en el umbral","waits for her in the doorway",{}),
 ("de mes en mes","month by month",{}),
 ("el primero por adelantado","the first one in advance",{}),
 ("arriba se oye de todo","upstairs you hear all sorts",{}),
 ("ya lo irá viendo","you will see soon enough",{}),
 ("añade","he adds",{}),
 ("ha comprobado el armario","has checked the wardrobe",{}),
 ("no cierra a la primera","does not shut first time",{}),
 ("y sabe que","and knows that",{}),
 ("el colchón huele a nuevo","the mattress smells new",{}),
 ("aunque el interruptor no encienda nada","although the switch turns nothing on",{}),
 ("mueve un enchufe","moves a socket",{}),
 ("tarda en contestarle","takes his time answering her",{}),
 ("ella calla","she says nothing",{}),
 ("la calefacción va por horas","the heating runs on a timer",{}),
 ("en enero no subiría hasta aquí","in January it would not reach up here",{}),
 ("avisa","he warns",{}),
 ("si le faltara","if you were short of it",{}),
 ("en el mueble del pasillo","in the hall cupboard",{}),
 ("hay una estufa","there is a heater",{}),
 ("ofrece","he offers",{}),
 ("lo acepta","she takes it",{}),
 ("apunta la cifra en el billete","notes the figure on the banknote",{}),
 ("en la sala","in the living room",{}),
 ("una mancha blanda","a soft stain",{}),
 ("encima de la mesa","above the table",{}),
 ("la mitad que en Madrid","half what it is in Madrid",{}),
 ("y ella lo sabe","and she knows it",{}),
 ("cambiará la cerradura el jueves","she will change the lock on Thursday",{}),
 ("decide","she decides",{}),
 ("baja los cuatro pisos","goes down the four floors",{}),
 ("sin decir nada","without a word",{}),
],
"arriba-vive-alguien":[
 ("arriba vive alguien","somebody lives upstairs",{}),
 ("ha pegado una hoja en la puerta","has stuck a sheet on the door",{}),
 ("con cinta","with tape",{}),
 ("son once normas","there are eleven rules",{}),
 ("la lavadora se apunta","you write the washing machine down",{}),
 ("la lee entera","reads it right through",{}),
 ("poco a poco","little by little",{}),
 ("el reciclaje lo mira el portal","the stairwell watches the recycling",{}),
 ("no se escapa nadie","nobody gets away with it",{}),
 ("avisa Emilio","Emilio warns",{}),
 ("para la antena","for the aerial",{}),
 ("haría falta permiso de todos","it would take everyone's permission",{}),
 ("en serio","seriously",{}),
 ("añade","he adds",{}),
 ("ha colgado tres perchas","has hung three hangers",{}),
 ("estira una alfombra","spreads a rug",{}),
 ("que no tapa el suelo","that does not cover the floor",{}),
 ("la bombilla parpadea","the bulb flickers",{}),
 ("un cable cuelga mojado del techo","a wet cable hangs from the ceiling",{}),
 ("abre la ducha","she turns on the shower",{}),
 ("el agua suena hueca","the water sounds hollow",{}),
 ("dentro de la pared","inside the wall",{}),
 ("pasa el dedo por el polvo","runs his finger through the dust",{}),
 ("y calla","and says nothing",{}),
 ("si le faltara una manta","if you were short of a blanket",{}),
 ("arriba hay dos en el altillo","there are two up in the top cupboard",{}),
 ("ofrece","he offers",{}),
 ("el cepillo duro se lo presto","I will lend you the stiff brush",{}),
 ("aunque me lo devuelva sin falta","as long as you give it back without fail",{}),
 ("remata","he finishes",{}),
 ("lo acepta","she takes it",{}),
 ("va a dejarlo junto a la puerta","goes to leave it by the door",{}),
 ("a las once","at eleven",{}),
 ("alguien ha arrastrado algo arriba","somebody has dragged something upstairs",{}),
 ("de golpe","all at once",{}),
 ("no es ruido de obra","it is not the noise of building work",{}),
 ("vive ahí desde antes que ella","has lived there longer than she has",{}),
 ("de momento","for now",{}),
 ("apunta la hora","notes the time",{}),
 ("la herramienta que Emilio promete","the tool Emilio promises",{}),
],
"la-mayoria-decide-el-techo":[
 ("la mayoría decide el techo","the majority decides about the roof",{}),
 ("el anuncio de la reunión","the notice of the meeting",{}),
 ("lleva tres días en el portal","has been in the entrance hall three days",{}),
 ("y huele a cola","and it smells of glue",{}),
 ("la presidenta de la comunidad","the chairwoman of the residents",{}),
 ("ha bajado la primera","has come down first",{}),
 ("baja con el portátil","comes down with her laptop",{}),
 ("y una copia","and a copy",{}),
 ("el orden del día es corto","the agenda is short",{}),
 ("el techo y poco más","the roof and little else",{}),
 ("abre Berta","Berta opens",{}),
 ("saldrá o no saldrá por mayoría","it will pass or not, by majority",{}),
 ("no por quien grite","not by whoever shouts",{}),
 ("añade","she adds",{}),
 ("luego lo revisa todo","then she goes over it all",{}),
 ("en voz alta","out loud",{}),
 ("sin prisa","without hurrying",{}),
 ("ofrece pagar su parte","offers to pay her share",{}),
 ("la frase le sale corta","the sentence comes out short",{}),
 ("nadie contesta","nobody answers",{}),
 ("levanta la mano","raises his hand",{}),
 ("pide que conste su voto","asks for his vote to be recorded",{}),
 ("taparlo con plástico es inútil","covering it with plastic is useless",{}),
 ("ya lo hemos probado","we have already tried that",{}),
 ("corta Berta","Berta cuts in",{}),
 ("hay que firmar los tres","the three of us have to sign",{}),
 ("y de una vez","and once and for all",{}),
 ("para que la obra empiece en abril","so that the work starts in April",{}),
 ("remata","she finishes",{}),
 ("apunta la fecha","notes the date",{}),
 ("busca dónde va la firma","looks for where the signature goes",{}),
 ("al final llega el sello","in the end the stamp arrives",{}),
 ("les resume el acta a cada uno","sums up the minutes for each of them",{}),
 ("ya no depende de ella","no longer depends on her",{}),
 ("ni de Emilio por su cuenta","or on Emilio on his own",{}),
 ("sube los cuatro pisos","goes up the four floors",{}),
 ("más tranquila","easier in her mind",{}),
]}
for slug, filas in S.items():
    out={}
    for es,en,ov in filas:
        for w in re.findall(r'[^\W\d_]+', es.lower(), re.UNICODE):
            if w in EX or w in out: continue
            e={"es":es,"en":en}
            if w in ov: e["g"]=ov[w]
            out[w]=e
    io.open(f"scripts/_b1/g/{slug}.chunks.json","w",encoding="utf-8").write(json.dumps(out,ensure_ascii=False,indent=1))
    ln=[len(v["es"].split()) for v in out.values()]
    ln.sort()
    print(f"{slug:28} {len(out)} palabras · mediana {ln[len(ln)//2]} · max {ln[-1]}")
