/**
 * Replace currywurst-am-mehringdamm with two new A1 multi-character dialogue
 * stories in food-everyday-life topic, in the style of cafe-in-kreuzberg.
 *
 * Stories are pre-generated by sub-agents into JSON files at
 *   data/dialogue-stories/<slug>.json
 * This script:
 *   1. Validates each JSON against the new vocab pedagogical rules.
 *   2. Deletes currywurst-am-mehringdamm in the active German journey.
 *   3. Inserts both new stories as draft.
 *   4. Generates audio for each via ElevenLabs (Carl voice). Whisper QA may fail
 *      gracefully if OpenAI quota is exhausted; audio still uploads.
 *   5. Marks both as published.
 */

import { config } from "dotenv";
import { readFileSync } from "fs";
import path from "path";
import { PrismaClient } from "../src/generated/prisma";

config({ path: ".env.local" });
config({ path: ".env" });

const SLUG_TO_REPLACE = "currywurst-am-mehringdamm";
const TARGET_LANGUAGE = "german";
const TARGET_LEVEL = "a1";
const TARGET_TOPIC = "food-everyday-life";

const STORY_FILES = [
  { slug: "beim-baecker-am-hackeschen-markt", path: "data/dialogue-stories/beim-baecker-am-hackeschen-markt.json" },
  { slug: "tomaten-vom-wochenmarkt", path: "data/dialogue-stories/tomaten-vom-wochenmarkt.json" },
];

// === validators ===
const MULETILLAS: RegExp[] = [
  /^refers\s+to\b/i, /^describes?\b/i, /^used\s+(to|for|in|as|when)\b/i,
  /^means?\b/i, /^meaning\b/i, /^conveys?\b/i, /^speaks?\s+to\b/i,
  /^brings?\b/i, /^this\s+word\b/i, /^a\s+type\s+of\b/i, /^a\s+person\s+who\b/i,
  /^someone\s+who\b/i, /^something\s+that\b/i, /^the\s+(action|state|quality)\s+of\b/i,
];
const LEADING: RegExp[] = [
  /^[A-Za-z][A-Za-z'\-]*[;,:]/,
  /^[A-Za-z][A-Za-z'\-]*\s*\([^)]*\)\s*[;,:]/,
  /^(A|An|The|To)\s+[A-Za-z'\-]+[;,:]/i,
  /^(A|An|The|To)\s+[A-Za-z'\-]+\s*\([^)]*\)\s*[;,:]/i,
];
function wordCount(s: string) { return s.trim().split(/\s+/).filter(Boolean).length; }
function classifyDef(d: string): string[] {
  const r: string[] = [];
  if (MULETILLAS.some((re) => re.test(d.trim()))) r.push("muletilla");
  if (LEADING.some((re) => re.test(d.trim()))) r.push("leading-gloss");
  if (/—/.test(d)) r.push("em-dash");
  const w = wordCount(d);
  if (w > 16) r.push("too-long");
  if (w < 6) r.push("too-short");
  return r;
}

type StoryJSON = {
  title: string;
  synopsis: string;
  text: string;
  vocab: { word: string; surface?: string; definition: string; type?: string }[];
};

function loadAndValidate(filePath: string): StoryJSON {
  const data = JSON.parse(readFileSync(filePath, "utf8")) as StoryJSON;
  if (!data || typeof data !== "object") throw new Error(`Invalid JSON: ${filePath}`);
  if (typeof data.title !== "string" || typeof data.synopsis !== "string" || typeof data.text !== "string" || !Array.isArray(data.vocab)) {
    throw new Error(`Missing required fields in ${filePath}`);
  }
  const wc = wordCount(data.text);
  if (wc < 200 || wc > 320) console.warn(`  warning: ${filePath} text wordCount=${wc} outside [200, 320]`);
  const bad: string[] = [];
  for (const v of data.vocab) {
    const c = classifyDef(v.definition);
    if (c.length > 0) bad.push(`  ${v.word}: [${c.join(",")}] ${v.definition}`);
  }
  if (bad.length > 0) {
    console.error(`Validation FAILED for ${filePath}:`);
    bad.forEach((line) => console.error(line));
    throw new Error(`${bad.length} vocab defs failed validation`);
  }
  return data;
}

async function run() {
  const apply = process.argv.includes("--apply");
  const dryRun = process.argv.includes("--dry-run");
  if (!apply && !dryRun) {
    console.error("Pass --apply or --dry-run.");
    process.exit(1);
  }

  // Load + validate
  const stories = STORY_FILES.map((f) => ({ ...f, data: loadAndValidate(path.resolve(f.path)) }));
  for (const s of stories) {
    console.log(`Loaded ${s.slug}: ${s.data.vocab.length} vocab, ${wordCount(s.data.text)} words`);
  }

  const prisma = new PrismaClient();
  const journey = await prisma.journey.findFirst({
    where: { language: TARGET_LANGUAGE },
    orderBy: { createdAt: "desc" },
  });
  if (!journey) throw new Error("No German journey found");
  console.log(`\nActive German journey: ${journey.id} (variant=${journey.variant})`);

  // Delete currywurst
  const existing = await prisma.journeyStory.findFirst({
    where: { journeyId: journey.id, slug: SLUG_TO_REPLACE, level: TARGET_LEVEL },
  });
  if (existing) {
    console.log(`Found ${SLUG_TO_REPLACE} (id=${existing.id}, slotIndex=${existing.slotIndex})`);
    if (apply) {
      await prisma.journeyStory.delete({ where: { id: existing.id } });
      console.log(`  deleted`);
    } else {
      console.log(`  [dry-run] would delete`);
    }
  } else {
    console.warn(`No story with slug=${SLUG_TO_REPLACE} found in active journey`);
  }

  // Determine slot indexes
  const remainingFood = await prisma.journeyStory.findMany({
    where: { journeyId: journey.id, level: TARGET_LEVEL, topic: TARGET_TOPIC },
    select: { slotIndex: true },
    orderBy: { slotIndex: "asc" },
  });
  const usedSlots = new Set(remainingFood.map((s) => s.slotIndex));
  const newSlots: number[] = [];
  let slot = 0;
  for (let i = 0; i < stories.length; i += 1) {
    while (usedSlots.has(slot)) slot += 1;
    newSlots.push(slot);
    usedSlots.add(slot);
    slot += 1;
  }
  console.log(`Will use slotIndex: ${newSlots.join(", ")}`);

  if (!apply) {
    console.log(`\n[dry-run] complete; no DB changes, no audio generation`);
    await prisma.$disconnect();
    return;
  }

  // Insert + audio + publish
  const { generateAndUploadAudio } = await import("../src/lib/elevenlabs");
  for (let i = 0; i < stories.length; i += 1) {
    const { slug, data } = stories[i];
    const slotIndex = newSlots[i];
    console.log(`\n=== ${slug} (slot ${slotIndex}) ===`);

    const created = await prisma.journeyStory.create({
      data: {
        journeyId: journey.id,
        level: TARGET_LEVEL,
        topic: TARGET_TOPIC,
        slotIndex,
        status: "draft",
        title: data.title,
        slug,
        text: data.text,
        synopsis: data.synopsis,
        vocab: data.vocab as any,
        wordCount: wordCount(data.text),
        vocabCount: data.vocab.length,
      },
    });
    console.log(`  inserted draft id=${created.id}`);

    console.log(`  generating audio...`);
    const audio = await generateAndUploadAudio(data.text, data.title, journey.language, journey.variant);
    if (!audio) {
      console.warn(`  audio FAILED; story stays as draft`);
      await prisma.journeyStory.update({ where: { id: created.id }, data: { audioStatus: "failed" } });
      continue;
    }
    console.log(`  audio uploaded: ${audio.url}`);
    await prisma.journeyStory.update({
      where: { id: created.id },
      data: {
        audioUrl: audio.url,
        audioFilename: audio.filename,
        audioSegments: audio.audioSegments as any,
        audioStatus: "ready",
        audioQaStatus: audio.audioQa?.status ?? null,
        audioQaScore: audio.audioQa?.score ?? null,
        audioQaNotes: audio.audioQa?.notes?.join("\n") ?? null,
        status: "published",
      },
    });
    console.log(`  published`);
  }

  await prisma.$disconnect();
  console.log("\nDone.");
}

run().catch((err) => {
  console.error(err);
  process.exit(1);
});
