# -*- coding: utf-8 -*-
# palabra -> (tipo, definicion en ingles, 4-14 palabras)
DEFS = {}
DEFS.update({
"abajo": ("adverb", "below or downstairs, under something else"),
"abre": ("verb", "opens something, like a door or a shop"),
"abrir": ("verb", "to open something that is shut"),
"abro": ("verb", "I open it, first person of opening"),
"abrís": ("verb", "you open, the Argentine vos form"),
"acepta": ("verb", "agrees to something that is offered"),
"acerca": ("verb", "moves something closer to another person"),
"acomoda": ("verb", "settles someone or something into place"),
"acomodar": ("verb", "to arrange things into a better order"),
"acomodo": ("verb", "I make room for you, I fit you in"),
"acá": ("adverb", "here, in this place, the Argentine word"),
"adelante": ("adverb", "in front, at the front part"),
"adentro": ("adverb", "inside, in the interior of a place"),
"admite": ("verb", "admits something true that is hard to say"),
"afuera": ("adverb", "outside, out of the building"),
"agarro": ("verb", "I take that street, I go that way"),
"agrega": ("verb", "adds one more thing to what was said"),
"aguanta": ("verb", "holds up, puts up with something hard"),
"aguanto": ("verb", "I stand it, I put up with it"),
"agujero": ("noun", "a hole in a surface, letting things through"),
"ahora": ("adverb", "now, at this very moment"),
"ahí": ("adverb", "there, in that spot near you"),
"alcanza": ("verb", "is enough, covers what is needed"),
"algo": ("pronoun", "something, a thing without a name"),
"alguna": ("determiner", "some, one unnamed feminine thing"),
"algunos": ("determiner", "some of them, a few of many"),
"alquiler": ("noun", "the rent paid every month for a place"),
"ambo": ("noun", "a matching top and trousers worn at work"),
"anota": ("verb", "writes something down to remember it"),
"anotada": ("adjective", "written down, noted on paper"),
"anotado": ("adjective", "written down, booked in a list"),
"anotados": ("adjective", "written down, several of them booked"),
"anotamos": ("verb", "we write it down together"),
"anotar": ("verb", "to write something down in a notebook"),
"anoto": ("verb", "I write it down"),
"anotás": ("verb", "you write it down, Argentine vos form"),
"antes": ("adverb", "before, earlier than something else"),
"apaga": ("verb", "turns off a light or a machine"),
"aparece": ("verb", "shows up, becomes visible"),
"apoya": ("verb", "rests something on a surface"),
"aprieta": ("verb", "tightens or presses something hard"),
"aprieto": ("verb", "I tighten it, I press it"),
"apurada": ("adjective", "in a hurry, with no time"),
"apuro": ("noun", "a rush, being short of time"),
"arranca": ("verb", "starts up, gets going again"),
"arregla": ("verb", "fixes something that is broken"),
"arreglo": ("verb", "I sort it out, I fix it"),
"asiento": ("noun", "a seat, the part you sit on"),
"así": ("adverb", "like this, in this way"),
"atender": ("verb", "to serve a customer or answer a call"),
"atiende": ("verb", "serves a customer, takes care of them"),
"atrás": ("adverb", "behind, at the back"),
"aumento": ("noun", "a rise, more money charged than before"),
"auto": ("noun", "a car, the everyday Argentine word"),
"averiguamos": ("verb", "we find it out, we go and ask"),
"avisa": ("verb", "lets someone know, gives them warning"),
"aviso": ("verb", "I let you know, I warn you"),
"años": ("noun", "years, periods of twelve months"),
"baja": ("adjective", "low, pulled down, not raised"),
"balde": ("noun", "a bucket for carrying water"),
"banco": ("noun", "a bank, where money is paid in"),
"bancos": ("noun", "benches, long seats for several people"),
"bien": ("adverb", "well, in a good way"),
"billetera": ("noun", "a wallet for money and cards"),
"billetes": ("noun", "banknotes, the paper money"),
"birome": ("noun", "a ballpoint pen, the Argentine word"),
"bisagra": ("noun", "a hinge, the metal joint of a door"),
"boca": ("noun", "the mouth, the opening of the face"),
"boleta": ("noun", "a bill that has to be paid"),
"bolsillo": ("noun", "a pocket in clothing"),
"buena": ("adjective", "good, the nice one of a pair"),
"busca": ("verb", "looks for something that is missing"),
"buscamos": ("verb", "we look for them together"),
"cabezas": ("noun", "heads, here the customers to be cut"),
"cae": ("verb", "falls, drops to the ground"),
"caja": ("noun", "a box, here the box of tools"),
"cajero": ("noun", "the bank clerk who serves at the window"),
"cajón": ("noun", "a drawer in a table or counter"),
"calcula": ("verb", "works out a number in the head"),
"calientes": ("adjective", "hot, still warm from cooking"),
"callada": ("adjective", "quiet, not saying a word"),
"calladas": ("adjective", "quiet, two people saying nothing"),
"callate": ("verb", "keep it quiet, do not repeat it"),
"camisa": ("noun", "a shirt with buttons"),
"campera": ("noun", "a jacket, the Argentine word"),
"canilla": ("noun", "a water tap, the Argentine word"),
"carne": ("noun", "meat, the beef for the grill"),
"carpeta": ("noun", "a folder that holds papers"),
"casco": ("noun", "a helmet worn on a motorbike"),
"catorce": ("number", "fourteen, the number after thirteen"),
"celular": ("noun", "a mobile phone you carry"),
"cerrados": ("adjective", "closed, shut, not open"),
"champú": ("noun", "shampoo for washing hair"),
"chapa": ("noun", "a metal sheet used for roofs"),
"che": ("interjection", "hey, the Argentine way of calling someone"),
"chica": ("adjective", "small, the little one of two"),
"cierra": ("verb", "closes something, shuts it"),
"cierran": ("verb", "they close, the office shuts"),
"cinta": ("noun", "tape for sticking or fixing things"),
"clienta": ("noun", "a woman who comes as a customer"),
"clientas": ("noun", "women who come as customers"),
"cobro": ("verb", "I charge money for a job"),
"cocinero": ("noun", "a man who cooks in a kitchen"),
"cola": ("noun", "a queue of people waiting their turn"),
"colgada": ("adjective", "hanging, held from something above"),
})
DEFS.update({
"come": ("verb", "eats, takes food from the plate"),
"comenta": ("verb", "makes a remark about something"),
"comparamos": ("verb", "we compare two things side by side"),
"comé": ("verb", "eat, the Argentine vos command"),
"conmigo": ("pronoun", "with me, at my side"),
"contesta": ("verb", "answers, replies to what was said"),
"contra": ("preposition", "against, leaning on something"),
"copia": ("noun", "a copy of a signed paper"),
"corro": ("verb", "I run, I am rushing all day"),
"corta": ("verb", "cuts, here cuts hair with scissors"),
"cortas": ("adjective", "short, not long at all"),
"corte": ("noun", "a haircut, one job in the salon"),
"cortás": ("verb", "you cut, the Argentine vos form"),
"crema": ("noun", "a cream put on hair or skin"),
"cruza": ("verb", "crosses the street to the other side"),
"cuaderno": ("noun", "a notebook with pages for writing"),
"cuadra": ("noun", "a city block between two corners"),
"cuando": ("conjunction", "when, at the time that"),
"cuarenta": ("number", "forty, four times ten"),
"cuarto": ("noun", "a quarter, fifteen minutes of an hour"),
"cuatro": ("number", "four, the number after three"),
"cuchillo": ("noun", "a knife for cutting"),
"culpa": ("noun", "the blame or fault for something"),
"cuál": ("pronoun", "which one, asking to choose"),
"cuándo": ("adverb", "when, asking about the time"),
"cuánto": ("pronoun", "how much, asking about an amount"),
"dale": ("interjection", "go on, all right, the Argentine yes"),
"dame": ("verb", "give me, hand it over"),
"debe": ("verb", "owes money to somebody"),
"deberle": ("verb", "to owe something to another person"),
"debo": ("verb", "I owe, I have to pay"),
"decir": ("verb", "to say something out loud"),
"decírtelo": ("verb", "to say it to you"),
"deja": ("verb", "leaves something somewhere, drops it off"),
"dejámelo": ("verb", "leave it to me, let me do it"),
"dejás": ("verb", "you leave it, the Argentine vos form"),
"demora": ("noun", "a delay, time lost waiting"),
"depósito": ("noun", "money paid ahead as a guarantee"),
"derecha": ("adjective", "right, the side opposite the left"),
"derecho": ("adverb", "straight up, in a straight line"),
"desastre": ("noun", "a mess, something badly done"),
"descuentan": ("verb", "they take money off what you earn"),
"desde": ("preposition", "since, from a time or a place"),
"despacito": ("adverb", "nice and slowly, the Argentine softener"),
"despertador": ("noun", "an alarm clock that wakes you"),
"destornillador": ("noun", "a screwdriver for turning screws"),
"devolvémela": ("verb", "give it back to me"),
"devuelvo": ("verb", "I give it back to you"),
"dice": ("verb", "says, speaks the words"),
"diciembre": ("noun", "December, the last month of the year"),
"diez": ("number", "ten, the number after nine"),
"diferencia": ("noun", "the part still missing from a sum"),
"disculpa": ("verb", "says sorry for something"),
"distinto": ("adjective", "different, not the same as before"),
"doble": ("noun", "twice the usual amount of money"),
"doce": ("number", "twelve, the number after eleven"),
"dormí": ("verb", "sleep, the Argentine vos command"),
"dormís": ("verb", "you sleep, the Argentine vos form"),
"dos": ("number", "two, the number after one"),
"dudas": ("noun", "doubts, things you are not sure about"),
"duele": ("verb", "hurts, causes pain to somebody"),
"duerme": ("verb", "sleeps, falls asleep in the chair"),
"duermen": ("verb", "they sleep, they sit there unused"),
"dueño": ("noun", "the owner of the building"),
"dura": ("adjective", "hard, stiff, or firm in voice"),
"día": ("noun", "a day, from morning to night"),
"electricista": ("noun", "a person who fixes wires and power"),
"ella": ("pronoun", "she, that woman over there"),
"empieza": ("verb", "starts, begins at a set time"),
"encuentra": ("verb", "finds something, comes across it"),
"encuentro": ("verb", "I find it, I come across it"),
"enero": ("noun", "January, the first month of the year"),
"enfermera": ("noun", "a woman who cares for patients"),
"enjuaga": ("verb", "rinses something with water"),
"enojada": ("adjective", "angry, cross with someone"),
"entendés": ("verb", "you understand, the Argentine vos form"),
"entera": ("adjective", "whole, complete, nothing missing"),
"entiende": ("verb", "understands what is being said"),
"entiendo": ("verb", "I understand what you say"),
"entra": ("verb", "goes in, comes inside"),
"entran": ("verb", "they come in, they arrive"),
"entrando": ("verb", "coming in, getting inside"),
"escoba": ("noun", "a broom for sweeping the floor"),
"esconde": ("verb", "hides something out of sight"),
"escribís": ("verb", "you write, the Argentine vos form"),
"escrita": ("adjective", "written, put down on paper"),
"escucha": ("verb", "listens to what is said"),
"escucharlo": ("verb", "to hear it from someone"),
"escuchás": ("verb", "you listen, the Argentine vos form"),
"espalda": ("noun", "the back of the body"),
"espera": ("verb", "waits for someone or something"),
"esperan": ("verb", "they wait, sitting there"),
"espero": ("verb", "I wait, I stay until you can"),
"estoy": ("verb", "I am, how I feel right now"),
"está": ("verb", "is, in a place or a state"),
"están": ("verb", "they are, in a place or a state"),
"estás": ("verb", "you are, the Argentine vos form"),
"explica": ("verb", "makes something clear to another person"),
"falta": ("verb", "is missing, is not there"),
"faltan": ("verb", "are missing, are still needed"),
"favor": ("noun", "a favour, please when you ask"),
"fecha": ("noun", "the date, the day of the month"),
"ferretería": ("noun", "a shop selling tools and screws"),
"fiado": ("noun", "goods taken now and paid later"),
"fijo": ("adjective", "steady, not changing from month to month"),
"fin": ("noun", "the end, here the end of the week"),
"final": ("noun", "the end of something, the last part"),
"firma": ("noun", "a signature written on a paper"),
"firmado": ("adjective", "signed, with the name written on it"),
"firme": ("adjective", "firm, steady, not loose"),
})
DEFS.update({
"firmo": ("verb", "I sign, I put my name here"),
"fiás": ("verb", "you give credit, the Argentine vos form"),
"flequillo": ("noun", "the fringe of hair over the forehead"),
"floja": ("adjective", "loose, not tight or firm"),
"flojo": ("adjective", "weak or watery, with little strength"),
"frase": ("noun", "a sentence, a group of words"),
"frena": ("verb", "brakes, slows down to stop"),
"fríos": ("adjective", "cold, no longer warm"),
"fusible": ("noun", "a fuse that cuts the power"),
"gasta": ("verb", "wears down with use"),
"gastada": ("adjective", "worn out from too much use"),
"golpea": ("verb", "knocks or bangs on something"),
"goma": ("noun", "a tyre on a wheel"),
"gotera": ("noun", "a leak dripping water from above"),
"grita": ("verb", "shouts in a loud voice"),
"grito": ("noun", "a shout, a loud cry"),
"grité": ("verb", "I shouted at somebody"),
"guarda": ("verb", "puts something away, keeps it safe"),
"gusto": ("noun", "taste, or pleasure at meeting someone"),
"habla": ("verb", "speaks, talks to someone"),
"hace": ("verb", "does or makes something"),
"hacés": ("verb", "you do it, the Argentine vos form"),
"hago": ("verb", "I do it, I work that long"),
"hamaca": ("verb", "rocks from side to side"),
"hasta": ("preposition", "until, up to a time or place"),
"hecha": ("adjective", "made or done, here worn out"),
"hecho": ("adjective", "done, agreed and settled between two"),
"heladera": ("noun", "a fridge, the Argentine word"),
"hermano": ("noun", "a brother, a son of the same parents"),
"herramientas": ("noun", "tools for fixing and building"),
"hombro": ("noun", "the shoulder of the body"),
"hora": ("noun", "an hour, or the time of day"),
"horrible": ("adjective", "very bad, ugly to look at"),
"humo": ("noun", "smoke rising from a fire"),
"húmedos": ("adjective", "damp, still wet from washing"),
"insiste": ("verb", "keeps saying the same thing"),
"interés": ("noun", "extra money charged on a debt"),
"jueves": ("noun", "Thursday, the day after Wednesday"),
"junta": ("verb", "gathers or saves things together"),
"juntan": ("verb", "they gather or save it up"),
"juntar": ("verb", "to gather or sweep things together"),
"juntas": ("adjective", "together, the two of us"),
"juro": ("verb", "I swear it is true"),
"kiosco": ("noun", "a small corner shop for daily things"),
"lado": ("noun", "a side, one part of two"),
"lados": ("noun", "sides, both directions of a movement"),
"larga": ("adjective", "long, taking up much space"),
"lata": ("noun", "a tin can used to keep things"),
"lava": ("verb", "washes something with water"),
"lavo": ("verb", "I wash it for you"),
"lee": ("verb", "reads words on paper"),
"letra": ("noun", "handwriting, the shape of the letters"),
"levanta": ("verb", "lifts something up from the floor"),
"leídos": ("adjective", "read already, opened and seen"),
"libreta": ("noun", "a small book for notes and bookings"),
"limonero": ("noun", "a lemon tree in the yard"),
"limpia": ("adjective", "clean, with no dirt or debt"),
"linterna": ("noun", "a torch that gives light"),
"lisa": ("adjective", "smooth, with no grip left"),
"listo": ("adjective", "ready, done, sorted out"),
"listos": ("adjective", "ready, both of them prepared"),
"llama": ("verb", "calls someone by phone or by voice"),
"llega": ("verb", "arrives, gets to the place"),
"llegan": ("verb", "they arrive, or they add up"),
"llego": ("verb", "I get there, I make it in time"),
"llena": ("adjective", "full, with no space left"),
"lleva": ("verb", "takes someone or something along"),
"llevate": ("verb", "take it with you"),
"llevo": ("verb", "I take you, I give you a lift"),
"mal": ("adverb", "badly, in the wrong way"),
"maneja": ("verb", "drives a car, the Argentine word"),
"manera": ("noun", "a way of doing or saying something"),
"manos": ("noun", "hands, both of them"),
"marzo": ("noun", "March, the third month of the year"),
"mate": ("noun", "the shared herb drink of Argentina"),
"mates": ("noun", "several rounds of the shared herb drink"),
"media": ("adjective", "half, thirty minutes past the hour"),
"medialuna": ("noun", "a small sweet croissant eaten at breakfast"),
"medio": ("noun", "the middle, the centre of something"),
"mediodía": ("noun", "midday, twelve in the afternoon"),
"menos": ("adverb", "less, or minutes before the hour"),
"mensajes": ("noun", "text messages on a phone"),
"mes": ("noun", "a month of the year"),
"mesada": ("noun", "the kitchen counter, the Argentine word"),
"mesas": ("noun", "tables, here the tables of a bar"),
"metal": ("noun", "metal, the hard material of tools"),
"mil": ("number", "a thousand, ten hundreds"),
"minuto": ("noun", "a minute, sixty seconds"),
"minutos": ("noun", "minutes, several of them"),
"miro": ("verb", "I look, I keep an eye on it"),
"misma": ("adjective", "the same one, not another"),
"mojadas": ("adjective", "wet, dripping with water"),
"mojados": ("adjective", "wet, soaked through by the rain"),
"molesto": ("adjective", "annoyed, put out by something"),
"monto": ("noun", "the amount of money to be paid"),
"mostrame": ("verb", "show it to me"),
"moto": ("noun", "a motorbike used for deliveries"),
"moverse": ("verb", "to move from the spot"),
"mundo": ("noun", "the world, here everybody around"),
"más": ("adverb", "more, a greater amount"),
"mía": ("pronoun", "mine, belonging to me"),
"nada": ("pronoun", "nothing, not a thing"),
"nadie": ("pronoun", "nobody, not one person"),
"ninguno": ("pronoun", "neither of them, not one"),
"nombra": ("verb", "says the name of something"),
"nombres": ("noun", "names of people on a list"),
"nueve": ("number", "nine, the number after eight"),
"nuevos": ("adjective", "new, just arrived on the screen"),
"número": ("noun", "a number, here the one in a queue"),
"ocho": ("number", "eight, the number after seven"),
"ocupan": ("verb", "they take up the space"),
"oficina": ("noun", "an office where papers are signed"),
"once": ("number", "eleven, the number after ten"),
"otra": ("determiner", "another one, one more"),
"otro": ("determiner", "another, a different one"),
})
DEFS.update({
"paga": ("verb", "pays money for something"),
"pago": ("verb", "I pay for it"),
"palabra": ("noun", "a word, one piece of language"),
"papeles": ("noun", "papers, the documents of a contract"),
"paso": ("verb", "I go by, I stop at a place"),
"pelo": ("noun", "hair on a person's head"),
"peluquería": ("noun", "a hairdressing salon in the front room"),
"peor": ("adjective", "worse, in a poorer state than before"),
"perdoname": ("verb", "sorry, forgive me for this"),
"pesos": ("noun", "pesos, the money of Argentina"),
"pide": ("verb", "asks for something from another person"),
"pierde": ("verb", "loses something or somebody"),
"plata": ("noun", "money, the everyday Argentine word"),
"pocillo": ("noun", "a small cup for coffee"),
"poco": ("adverb", "little, not very much at all"),
"pone": ("verb", "puts something in a place"),
"pregunta": ("verb", "asks a question to somebody"),
"prende": ("verb", "switches on a light or a screen"),
"problema": ("noun", "a problem that needs solving"),
"promesa": ("noun", "a promise given to somebody"),
"promete": ("verb", "promises to do something"),
"propone": ("verb", "suggests a plan or a deal"),
"protesta": ("verb", "complains out loud about something"),
"prueba": ("verb", "tries something to see how it works"),
"próxima": ("adjective", "next, the one coming after this"),
"puesta": ("adjective", "put on, already applied"),
"queda": ("verb", "stays, is left in a place"),
"quedan": ("verb", "they stay, they are left there"),
"quedate": ("verb", "stay here, do not go"),
"quedo": ("verb", "I stay, I am left with"),
"qué": ("pronoun", "what, asking about a thing"),
"recibo": ("noun", "a receipt proving a payment"),
"recién": ("adverb", "only just now, not before"),
"reja": ("noun", "the iron gate at the street door"),
"renglón": ("noun", "a line of writing on a page"),
"repite": ("verb", "says the same thing again"),
"revisa": ("verb", "checks something carefully with the eyes"),
"ruidito": ("noun", "a small noise, the Argentine softener"),
"ríen": ("verb", "they laugh together at something"),
"sabe": ("verb", "knows something, has the answer"),
"sabés": ("verb", "you know, the Argentine vos form"),
"saca": ("verb", "takes something out of a place"),
"saco": ("verb", "I take it out, I get it off"),
"saluda": ("verb", "greets or says goodbye"),
"secador": ("noun", "a hairdryer for drying hair"),
"seis": ("number", "six, the number after five"),
"semana": ("noun", "a week of seven days"),
"serio": ("adjective", "serious, with no smile"),
"siempre": ("adverb", "always, every single time"),
"sienta": ("verb", "sits down in a chair"),
"siete": ("number", "seven, the number after six"),
"sigue": ("verb", "carries on, keeps going"),
"silla": ("noun", "a chair to sit on"),
"sin": ("preposition", "without, when something is lacking"),
"sirve": ("verb", "pours a drink, or is of use"),
"sobre": ("noun", "an envelope holding a letter"),
"sola": ("adjective", "alone, with nobody else"),
"sube": ("verb", "goes up, or raises something"),
"suelta": ("verb", "lets go of something"),
"suena": ("verb", "rings or makes a sound"),
"sábado": ("noun", "Saturday, the day after Friday"),
"techo": ("noun", "a roof over a building"),
"tengo": ("verb", "I have, I hold something"),
"tenés": ("verb", "you have, the Argentine vos form"),
"termina": ("verb", "finishes, comes to an end"),
"termo": ("noun", "the flask of hot water for mate"),
"tiene": ("verb", "has, holds or owns something"),
"tijera": ("noun", "scissors for cutting hair"),
"timbre": ("noun", "a doorbell at the gate"),
"toda": ("determiner", "all of it, the whole thing"),
"todavía": ("adverb", "still, up to now"),
"todo": ("pronoun", "everything, the whole lot"),
"tomá": ("verb", "here, take it, the Argentine command"),
"tranquila": ("adjective", "calm, easy, not worried"),
"tres": ("number", "three, the number after two"),
"turno": ("noun", "an appointment booked at a set time"),
"turnos": ("noun", "appointments booked through the day"),
"veces": ("noun", "times, repeated occasions of the same"),
"vecino": ("noun", "a neighbour living close by"),
"vengo": ("verb", "I come, I am here for something"),
"vení": ("verb", "come here, the Argentine vos command"),
"vereda": ("noun", "the pavement, the Argentine word"),
"vez": ("noun", "one time, one occasion"),
"viene": ("verb", "comes, arrives from somewhere"),
"viernes": ("noun", "Friday, the day after Thursday"),
"vive": ("verb", "lives in a place"),
"vos": ("pronoun", "you, the Argentine form instead of tú"),
"voy": ("verb", "I go, I am on my way"),
"vuelta": ("noun", "a turn or a way back"),
"vuelve": ("verb", "comes back, returns to the place"),
})
DEFS.update({
"caminando": ("verb", "walking away on foot"),
"entre": ("preposition", "between or among, in the middle of"),
"levantada": ("adjective", "raised, pulled up and open"),
"llave": ("noun", "a key that locks a gate"),
"ofrece": ("verb", "offers something to another person"),
"ojos": ("noun", "the eyes of a person"),
"olvido": ("verb", "I forget it, it slips away"),
"pagarte": ("verb", "to pay you what is owed"),
"parado": ("adjective", "standing up, on his feet"),
"parte": ("noun", "a part, one piece of a whole"),
"pasillo": ("noun", "a narrow hallway between rooms"),
"peine": ("noun", "a comb for tidying hair"),
"preguntás": ("verb", "you ask, the Argentine vos form"),
"repetís": ("verb", "you repeat, the Argentine vos form"),
"semanas": ("noun", "weeks, several periods of seven days"),
})
DEFS.update({
"pantalla": ("noun", "the screen of a phone"),
"parejo": ("adjective", "even, the same all over"),
"peluquera": ("noun", "a woman who cuts hair for a living"),
})
DEFS.update({
"negra": ("adjective", "black, the dark coloured one"),
"pedirte": ("verb", "to ask you for something"),
"poquito": ("noun", "a little bit, the Argentine softener"),
})
DEFS.update({
"mirarla": ("verb", "to look at her"),
"señor": ("noun", "a man, the polite word for him"),
})
DEFS.update({
"guardada": ("adjective", "put away, kept in its place"),
"lunes": ("noun", "Monday, the first day of the week"),
"mirarlo": ("verb", "to look at it"),
"seria": ("adjective", "serious, with no smile on her face"),
})
DEFS.update({
"escribano": ("noun", "a notary who stamps official papers"),
"toman": ("verb", "they drink, they share the mate"),
})
DEFS.update({"toma": ("verb", "drinks, or takes hold of something")})
DEFS.update({
"milanesas": ("noun", "breaded meat cutlets, everyday Argentine food"),
"pierdo": ("verb", "I lose her, I lose the booking"),
"presenta": ("verb", "introduces one person to another"),
"remis": ("noun", "a booked car with a driver, cheaper than a taxi"),
"rotisería": ("noun", "a shop selling hot cooked food to take away"),
"tiras": ("noun", "strips of grilled beef ribs from the parrilla"),
"yerba": ("noun", "the dried leaves used to brew mate"),
})
DEFS.update({"mucho": ("adverb", "much, a lot more than before")})
DEFS.update({"trae": ("verb", "brings something to a place")})
DEFS.update({
"papel": ("noun", "a sheet of paper, here the letter"),
"repetímelo": ("verb", "say it to me again, Argentine vos command"),
})
DEFS.update({
"barre": ("verb", "sweeps the floor with a broom"),
"enfría": ("verb", "goes cold, loses its heat"),
})
DEFS.update({"alta": ("adjective", "loud, said out loud")})
DEFS.update({
"atados": ("adjective", "tied back, held up with a band"),
"carga": ("verb", "fills the mate with fresh leaves"),
"después": ("adverb", "afterwards, later than that"),
"frías": ("adjective", "cold, no longer warm"),
"hacen": ("verb", "they make a noise together"),
"hay": ("verb", "there is, there are"),
"mojada": ("adjective", "wet, soaked by the rain"),
"pasame": ("verb", "pass it to me, Argentine vos command"),
"patea": ("verb", "kicks something by accident"),
"patina": ("verb", "skids on the wet street"),
"pedirle": ("verb", "to ask him or her for something"),
"pensás": ("verb", "you think, the Argentine vos form"),
"perderla": ("verb", "to lose it, to let it go"),
"perdón": ("noun", "sorry, an apology in one word"),
"pidas": ("verb", "you ask for, after a refusal"),
"pido": ("verb", "I ask for something"),
"pileta": ("noun", "the sink where the dishes are washed"),
"pinchada": ("adjective", "punctured, with a flat tyre"),
"piso": ("noun", "the floor of a room"),
"podés": ("verb", "you can, the Argentine vos form"),
"pongas": ("verb", "you put, after a request not to"),
"pongo": ("verb", "I put in, I pay my share"),
"portero": ("noun", "the caretaker of a building"),
"precio": ("noun", "the price charged for something"),
"preferís": ("verb", "you would rather, Argentine vos form"),
"preguntas": ("noun", "questions asked to somebody"),
"prepara": ("verb", "gets something ready to use"),
"prestame": ("verb", "lend it to me, Argentine vos command"),
"probala": ("verb", "try it out, Argentine vos command"),
"probamos": ("verb", "we give it a try"),
"puedas": ("verb", "you can, whenever it suits you"),
"puedo": ("verb", "I can, I am able to"),
"punta": ("noun", "the tip or point of a tool"),
"puntual": ("adjective", "on time, not a minute late"),
"quedarte": ("verb", "to stay without something you need"),
"quedaste": ("verb", "you ended up, here with a clean slate"),
"quejarse": ("verb", "to complain about something"),
"quema": ("verb", "burns, is spoiled by the fire"),
"querés": ("verb", "you want, the Argentine vos form"),
"quiero": ("verb", "I want it, I would like it"),
"quietos": ("adjective", "still, not moving at all"),
"razón": ("noun", "being right about something"),
"repente": ("noun", "suddenly, with no warning at all"),
"repetime": ("verb", "say it again to me, vos command"),
"resbala": ("verb", "slips off the surface"),
"respuesta": ("noun", "an answer to a question"),
"revisan": ("verb", "they look it over carefully"),
"roja": ("adjective", "red, the colour of the ink"),
"rueda": ("noun", "a wheel of the motorbike"),
"rulos": ("noun", "curls, the curly hair of somebody"),
"sacá": ("verb", "take it out, Argentine vos command"),
"salgo": ("verb", "I come out, I finish my shift"),
"salva": ("verb", "saves something from being spoiled"),
"sello": ("noun", "an official stamp on a paper"),
"sentadas": ("adjective", "seated, sitting down and waiting"),
"servida": ("adjective", "laid out, ready to eat"),
"siente": ("verb", "feels something on the body"),
"somos": ("verb", "we are, the two of us"),
"sostenela": ("verb", "hold it, Argentine vos command"),
"suben": ("verb", "they go up to a higher place"),
"subí": ("verb", "go up, Argentine vos command"),
"sábados": ("noun", "Saturdays, week after week"),
"tacha": ("verb", "crosses a line out with a pen"),
"tampoco": ("adverb", "neither, not that one either"),
"tanto": ("adverb", "so much, to that degree"),
"tornillo": ("noun", "a screw that holds two parts"),
"trabajo": ("noun", "a job, paid work"),
})
DEFS.update({
"alcanzan": ("verb", "reach, are enough for something"),
"apretada": ("adjective", "held tight, squeezed inside"),
"llame": ("verb", "calls, if somebody rings up"),
"nombre": ("noun", "a name written on a list"),
"poner": ("verb", "to put in, to pay a share"),
"siguen": ("verb", "they carry on without an answer"),
})
DEFS.update({
"abogado": ("noun", "a lawyer working for the owner"),
"agarra": ("verb", "grips, here anger takes hold of her"),
"agarrame": ("verb", "hold this for me, vos command"),
"agarrate": ("verb", "hold on tight, vos command"),
"agarrá": ("verb", "take it, grab it, vos command"),
"aguantás": ("verb", "you put up with it, vos form"),
"alcanzame": ("verb", "pass it to me, vos command"),
"alfajor": ("noun", "a filled biscuit, the Argentine snack"),
"alicate": ("noun", "pliers for gripping and cutting wire"),
"anotame": ("verb", "put me down on the list, vos command"),
"anotámelo": ("verb", "write it down for me, vos command"),
"arreglate": ("verb", "sort it out yourself, vos command"),
"atienden": ("verb", "they serve you at the counter"),
"ayer": ("adverb", "yesterday, the day before today"),
"baldosa": ("noun", "a floor tile of the yard"),
"bancame": ("verb", "wait for me a moment, vos command"),
"barro": ("noun", "mud left by the rain"),
"brasa": ("noun", "the hot coal under the grill"),
"broches": ("noun", "pegs that hold clothes on the line"),
"buenos": ("adjective", "good, the good pair of shoes"),
"busco": ("verb", "I look for something"),
"cantero": ("noun", "a small planted bed in the yard"),
"carbón": ("noun", "charcoal for the grill"),
"carilla": ("noun", "one side of a sheet of paper"),
"cartelito": ("noun", "a small sign stuck on a door"),
"cepillo": ("noun", "a hairbrush for the salon"),
"cierto": ("adjective", "true, that is right"),
"colorada": ("adjective", "red in the face, blushing"),
"compro": ("verb", "I buy it at the shop"),
"corré": ("verb", "move it aside, vos command"),
"cuelga": ("verb", "hangs something on a hook"),
"decime": ("verb", "tell me, vos command"),
"decímelo": ("verb", "tell it to me, vos command"),
"despierto": ("verb", "I wake you up"),
"detergente": ("noun", "washing-up liquid for the dishes"),
"deudas": ("noun", "debts owed by the neighbours"),
"digas": ("verb", "you say, whatever you name"),
"eléctrico": ("adjective", "electric, worked by electricity"),
"engancha": ("verb", "catches on something and tears"),
"ensalada": ("noun", "a salad served with the meat"),
"enterás": ("verb", "you find out, vos form"),
"escribime": ("verb", "write it for me, vos command"),
"escribo": ("verb", "I write it down"),
"escuchaste": ("verb", "did you hear, vos past form"),
"esperame": ("verb", "wait for me, vos command"),
"estuche": ("noun", "a case that holds the scissors"),
"explicame": ("verb", "explain it to me, vos command"),
"fechas": ("noun", "dates written next to the names"),
"felpudo": ("noun", "a doormat at the door"),
"fiambrería": ("noun", "a shop selling cold cuts and cheese"),
"fijate": ("verb", "have a look, vos command"),
"golosinas": ("noun", "sweets sold at the corner shop"),
"guardapolvo": ("noun", "a work coat worn over clothes"),
"guardo": ("verb", "I put it away"),
"hebilla": ("noun", "a clip that holds the hair"),
"largá": ("verb", "out with it, say it, vos command"),
"leo": ("verb", "I read it to myself"),
"levantado": ("adjective", "lifted up, held away from the head"),
"levanto": ("verb", "I lift it, I open the shutter"),
"maceta": ("noun", "a flowerpot in the yard"),
"mechón": ("noun", "a lock of hair"),
"moja": ("verb", "wets something with water"),
"pasa": ("verb", "happens, or goes past"),
"peiname": ("verb", "do my hair, vos command"),
"percha": ("noun", "a hanger for the wet clothes"),
"prendida": ("adjective", "switched on and playing"),
"probalas": ("verb", "try them, vos command"),
"propina": ("noun", "a tip left for the service"),
"quinta": ("adjective", "fifth in the order"),
"radio": ("noun", "a radio playing in the room"),
"ramo": ("noun", "a bunch of flowers"),
"rejilla": ("noun", "a cloth for wiping the floor"),
"repito": ("verb", "I say it again"),
"riega": ("verb", "waters the plants of the yard"),
"ríe": ("verb", "laughs at what was said"),
"saldar": ("verb", "to settle a debt in full"),
"seca": ("adjective", "dry, with no water left"),
"sellito": ("noun", "a small official stamp"),
"sentate": ("verb", "sit down, vos command"),
"sobrecito": ("noun", "a small envelope for the money"),
"soga": ("noun", "the washing line in the yard"),
"suelto": ("adjective", "loose, undone and hanging"),
"termino": ("verb", "I finish my shift"),
"tiembla": ("verb", "shakes, trembles with tiredness"),
"tintura": ("noun", "hair dye used in the salon"),
"tira": ("verb", "throws something into the bin"),
"tocame": ("verb", "touch it, feel it, vos command"),
"trabaja": ("verb", "works at a job"),
"traigo": ("verb", "I bring it back"),
"traje": ("verb", "I brought something with me"),
"treinta": ("number", "thirty, three times ten"),
"vamos": ("verb", "we go there together"),
"vas": ("verb", "you go, you are leaving"),
"vendedor": ("noun", "the man who serves in the shop"),
"veo": ("verb", "I see it from here"),
})
DEFS.update({
"anuncia": ("verb", "announces something on a sign"),
"lavandina": ("noun", "bleach used for cleaning floors"),
"veinte": ("number", "twenty, two times ten"),
})
DEFS.update({"queja": ("noun", "a complaint said out loud")})
DEFS.update({
"dan": ("verb", "they give it to you"),
"disculpá": ("verb", "sorry, forgive me, vos command"),
"enjuago": ("verb", "I rinse it with water"),
"leas": ("verb", "you read it, after a request"),
"peino": ("verb", "I do your hair"),
"preparo": ("verb", "I get it ready for you"),
"vuelto": ("noun", "the change given back after paying"),
})
DEFS.update({"ayudás": ("verb", "you help, the Argentine vos form")})
DEFS.update({"falda": ("noun", "the lap, where things rest when seated")})
DEFS.update({"olor": ("noun", "a smell in the air")})
DEFS.update({"duras": ("adjective", "hard, gone stale and cold")})
DEFS.update({
"usar": ("verb", "to use something for its job"),
"viajes": ("noun", "delivery runs on the motorbike"),
"volvés": ("verb", "you come back, the Argentine vos form"),
})
DEFS.update({
"tuerca": ("noun", "a nut that screws onto a bolt"),
"espejito": ("noun", "a small hand mirror in the salon"),
"revistas": ("noun", "magazines left for the customers"),
"vuelvo": ("verb", "I come back another day"),
"zapatilla": ("noun", "a trainer, a soft shoe"),
"zapatillas": ("noun", "trainers, the soft shoes for walking"),
"única": ("adjective", "the only one who does it"),
})
DEFS.update({"zapatos": ("noun", "the good shoes kept for errands")})
DEFS.update({"revista": ("noun", "a magazine to pass the wait")})
DEFS.update({"ranura": ("noun", "the slot on the head of a screw")})
DEFS.update({"pelos": ("noun", "cut hairs swept off the floor")})
DEFS.update({"piloto": ("noun", "a raincoat worn over the clothes")})
DEFS.update({
"monedas": ("noun", "coins, the small change of the day"),
"dobla": ("verb", "folds a paper in two"),
"suma": ("verb", "adds up the money"),
})
DEFS.update({
"jabón": ("noun", "soap used for washing"),
"ladra": ("verb", "barks, the dog makes noise"),
})
DEFS.update({
"candado": ("noun", "a padlock that closes a drawer"),
"caramelos": ("noun", "sweets sold at the counter"),
"tabla": ("noun", "a wooden board for cutting meat"),
})
DEFS.update({"blanco": ("adjective", "white, the colour of the soap")})
DEFS.update({"cebado": ("adjective", "freshly filled, ready to drink")})
DEFS.update({"devuelve": ("verb", "gives it back to the owner")})
DEFS.update({
"mostrador": ("noun", "the counter of the shop"),
"pedirme": ("verb", "to ask me for something"),
"puede": ("verb", "can wait, is able to"),
"vuelvas": ("verb", "you come back, after a refusal"),
"zumba": ("verb", "buzzes with a low sound"),
"ayudarte": ("verb", "to give you a hand"),
})
DEFS.update({
"gel": ("noun", "hair gel used in the salon"),
"ruleros": ("noun", "hair rollers used for curls"),
"clavos": ("noun", "nails sold at the hardware shop"),
"tornillos": ("noun", "screws drawn in the notebook"),
"chicles": ("noun", "chewing gum sold at the counter"),
"vitrina": ("noun", "the glass case of the shop"),
"diario": ("noun", "the daily newspaper"),
"baldea": ("verb", "washes the pavement with water"),
"cable": ("noun", "an electric wire"),
"tacho": ("noun", "a bin for the rubbish"),
"pava": ("noun", "the kettle that heats water for mate"),
"azucarera": ("noun", "the small jar that holds the sugar"),
"vasos": ("noun", "glasses for water or wine"),
"muñeca": ("noun", "the wrist of the hand"),
"codo": ("noun", "the elbow of the arm"),
"tiemblan": ("verb", "they shake with tiredness"),
})
DEFS.update({"dibujados": ("adjective", "drawn in pen on the page")})
DEFS.update({
"factura": ("noun", "a sweet pastry eaten with mate"),
"vacías": ("adjective", "empty, with nothing left inside"),
})
DEFS.update({
"remitente": ("noun", "the sender's name on an envelope"),
"despareja": ("adjective", "uneven, not written the same"),
"silba": ("verb", "whistles when the water is hot"),
})
DEFS.update({"billetes": ("noun", "paper money, the notes she counts at the end of the day")})
