import json
d=json.load(open("scripts/_deA1Friends/t1-texts.json"))
def V(t,w,s,df): return {"type":t,"word":w,"surface":s,"definition":df}
d[0]["vocab"]=[
V("noun","die Physiotherapeutin","Physiotherapeutin","A woman who helps people move after pain or injury."),
V("adverb","abends","abends","In the evening; every evening."),
V("noun","die Sprachnachricht","Sprachnachricht","A voice message; you record it on your phone."),
V("noun","die Freundin","Freundinnen","A female friend."),
V("verb","kennenlernen","kennengelernt","To meet someone for the first time."),
V("verb","stimmen","stimmt","To be true or correct."),
V("noun","der Haken","Haken","A tick; a small mark that shows something."),
V("noun","das Stockwerk","Stockwerk","A floor of a building."),
V("noun","der Straßenbahnfahrer","Straßenbahnfahrer","A man who drives a tram."),
V("noun","der Kapuzenpullover","Kapuzenpullover","A hoodie; a warm top with a hood."),
V("noun","der Müllbeutel","Müllbeutel","A rubbish bag; a bin bag."),
V("noun","die Wand","Wände","A wall; the side of a room."),
V("noun","die Lüge","Lüge","A lie; something that is not true."),
V("adjective","peinlich","peinlich","Embarrassing; it makes you feel awkward."),
V("noun","das Display","Display","The screen of a phone."),
V("noun","die Stufe","Stufe","A step on a staircase."),
V("verb","rot werden","wird rot","To blush; your face turns red."),
V("adverb","gegenüber","Gegenüber","Across from here; on the other side."),
V("adjective","dünn","dünn","Thin; not thick."),
V("noun","der Mund","Mund","The mouth."),
]
d[1]["vocab"]=[
V("verb","klopfen","klopft","To knock on a door."),
V("noun","der Zettel","Zettel","A small piece of paper."),
V("noun","die Handynummer","Handynummer","A mobile phone number."),
V("verb","abholen","hole ich dich ab","To pick someone up."),
V("verb","speichern","speichert","To save something on a phone or computer."),
V("noun","der Videoanruf","Videoanruf","A video call; you see the other person on a screen."),
V("noun","der Bildschirm","Bildschirm","A screen."),
V("adverb","gleichzeitig","gleichzeitig","At the same time."),
V("adjective","stumm","stumm","Silent; the phone makes no sound."),
V("verb","telefonieren","telefonieren","To talk on the phone."),
V("adverb","draußen","draußen","Outside; not in a building."),
V("expression","nächstes Mal","nächstes Mal","Next time."),
V("adjective","schade","Schade","What a pity; too bad."),
V("verb","sich ärgern","ärgert sich","To be annoyed or angry."),
V("noun","die Stirn","Stirn","The forehead; the top part of your face."),
V("verb","drücken","drückt","To press."),
V("adverb","vorbei","vorbei","Over; finished."),
V("verb","verpassen","verpasst","To miss something, like a call or a train."),
V("noun","das Gesicht","Gesichter","A face."),
V("expression","halb elf","halb elf","Half past ten."),
]
d[2]["vocab"]=[
V("noun","der Sonntagmorgen","Sonntagmorgen","Sunday morning."),
V("verb","löschen","löscht","To delete; to take away text."),
V("adjective","albern","albern","Silly; not serious."),
V("verb","wählen","wählt","To dial a phone number."),
V("verb","anrufen","ruft ihn einfach an","To call someone on the phone."),
V("noun","die Leitung","Leitung","The phone line."),
V("adjective","besetzt","besetzt","Busy; the phone line is in use."),
V("noun","der Versuch","Versuch","A try; an attempt."),
V("noun","die Mailbox","Mailbox","Voicemail; you leave a message there."),
V("adverb","gern","gern","Gladly; you like to do it."),
V("verb","zurückrufen","ruft zurück","To call someone back."),
V("noun","der Hintergrund","Hintergrund","The background; behind the main sound."),
V("verb","quietschen","quietscht","To squeak."),
V("expression","bei der Arbeit","bei der Arbeit","At work."),
V("verb","mitkommen","mitkommen","To come along with someone."),
V("verb","lächeln","lächelt","To smile."),
V("verb","anhören","hört sie nicht gleich an","To listen to something."),
V("adverb","gleich","gleich","Right away; soon."),
V("noun","der Wecker","Wecker","An alarm clock."),
V("verb","schalten","schaltet","To switch a device to a setting."),
]
json.dump(d,open("scripts/_deA1Friends/t1-data.json","w"),ensure_ascii=False,indent=1)
