# Pase de edicion 2026-09-13: textos completos de las 21 (trama, reparto y vocab intactos).
import json,re,sys
O,C="“","”"
def q(s,a=None):
    return O+s+C+(f", {a}" if a else "")
T={}
T[(1,0)]=[
 "Anna, eine Grafikerin aus Bremen, sitzt in einer alten Küche im Viertel. Ihre Hände sind kalt.",
 "Jan ist ein Koch und ihr Freund aus der Schulzeit. Er wohnt unten im Haus. Er bringt zwei Tassen Tee.",
 q("Willkommen zurück","sagt Jan."),
 "Anna hat eine Schachtel dabei. Die Schachtel ist voll mit Postkarten. Keine Karte hat eine Briefmarke.",
 q("Was ist das?","fragt Jan."),
 q("Meine Karten aus München. Alle für dich. Ich schicke sie nie","antwortet Anna."),
 "Jan nimmt zuerst die erste Karte. Er liest laut:",
 q("Lieber Jan, ich komme im Mai. Deine Anna."),
 q("Im Mai? Welcher Mai?","fragt er."),
 "Anna wird rot. Dieser Mai ist acht Jahre alt. Sie steckt die Hände in die Jacke.",
 q("Ich weiß. Es tut mir leid","flüstert sie."),
 "Jan trinkt still seinen Tee. Er öffnet eine Schublade. Die Karten liegen dann dort.",
 q("Die Karten bleiben hier bei mir","sagt Jan.")+" "+q("Und du bleibst auch, oder?"),
 "Anna atmet tief. Ihr Tee ist warm.",
]
T[(1,1)]=[
 "Zwölf Namen stehen auf einem alten Zettel. Der Zettel ist sehr alt. Anna kennt jeden Namen. Die Küche riecht nach Tee.",
 q("Das sind alle Freunde von früher","sagt Anna zu Jan."),
 "Anna will jedem Freund eine Postkarte schicken. Die Karte ist eine Einladung für Donnerstag.",
 q("Ich brauche die Adressen","bittet sie."),
 "Jan nimmt sein Handy. Er zeigt auf die Namen.",
 q("Er wohnt in Kiel. Sie wohnt in Hamburg. Er wohnt in Berlin","liest Jan."),
 "Anna macht einen Strich durch jeden Namen. Ein Strich, noch ein Strich.",
 q("Und hier?","fragt sie."),
 q("Hamburg. Der auch","antwortet Jan."),
 "Anna zählt. Vier Freunde wohnen noch in Bremen. Acht Karten sind zu viel.",
 "Anna faltet den Zettel langsam. Ihr Hals ist eng. Acht Karten landen im Müll.",
 q("Vier ist nicht schlecht","meint Jan."),
 q("Vier ist nicht zwölf","sagt Anna."),
 q("Und ich? Ich bin fünf","lacht Jan."),
 "Anna lächelt ein bisschen. Sie nimmt eine Karte mehr und schreibt Jans Namen darauf.",
]
T[(1,2)]=[
 "Die Post ist am Sonntag geschlossen. Anna hat fünf Karten und keine Briefmarke. Der Donnerstag kommt bald.",
 "Jan sucht in seiner Schublade. Er findet ein kleines Heft mit Briefmarken.",
 q("Die Marken sind alte Marken, aber gut","sagt er.")+" "+q("Fünf Stück. Genau fünf."),
 "Anna zieht noch eine Karte aus der Jacke.",
 q("Ich habe sechs Karten. Diese Karte ist für München, für meine alte Arbeit","erklärt sie."),
 q("Sechs Karten und fünf Marken?","ruft Jan."),
 "Anna legt zwei Karten nebeneinander.",
 q("München oder du","sagt sie leise."),
 "Anna zerreißt die Karte für München. Das tut weh. Die Stücke fallen in den Müll.",
 q("Die letzte Marke ist für dich","sagt Anna."),
 q("Ich wohne unten im Haus!","lacht Jan."),
 q("Egal. Du bekommst eine Karte","antwortet sie."),
 "Jan klebt die Marke auf seine Karte. Die Luft ist kalt. Der gelbe Briefkasten steht an der Ecke.",
 "Anna steckt dann die Karten in den Briefkasten. Jan legt den Arm um ihre Schulter.",
]
T[(2,0)]=[
 "Jans Kühlschrank ist voll mit Fotos. Anna, die neue Mieterin von oben, steht davor. Jan kocht heute für die Freunde.",
 "Die Tür öffnet sich. Jans Nachbarin Nele steht dort. Sie ist Fotografin und trägt eine runde Brille.",
 q("Hallo! Wer bist du?","ruft Nele."),
 q("Ich bin Anna. Ich wohne oben","antwortet Anna."),
 q("Anna aus München? Endlich!","sagt Nele."),
 "Nele umarmt Anna. Nele hilft Jan dann am Herd.",
 "Anna sucht ihr Gesicht auf den Fotos. Jan ist auf jedem Foto. Nele steht immer neben ihm. Anna ist auf keinem Foto.",
 "Ihr Bauch ist hart, denn Nele hat ihren Platz. Sie nimmt ein Foto vom Kühlschrank.",
 q("Das bin ich, mit Jan im Park","sagt Nele.")+" "+q("Du fehlst auf dem Foto."),
 q("Ich fehle auf allen Fotos","antwortet Anna leise."),
 q("Aber jetzt bist du hier. Ich mache gern ein Foto von dir","lächelt Nele."),
 "Anna hängt das Foto wieder an den Kühlschrank. Ihr Bauch ist noch ein bisschen hart.",
]
T[(2,1)]=[
 "Ein altes Foto liegt auf Jans Tisch. Anna und Jan sind darauf zwanzig Jahre alt.",
 q("Das bist du?","ruft Nele.")+" "+q("Die Brille ist so groß!"),
 "Anna trägt auf dem Foto eine große Brille. Ihre Haare sind lang und blond. Jan hat noch keinen Bart.",
 q("Ich weiß. Ich bin da zwanzig","antwortet Anna."),
 "Nele holt ihre Kamera.",
 q("Ich brauche ein Foto von dir. Für den Kühlschrank","sagt sie."),
 "Anna schaut auf das alte Foto. Anna auf dem Foto ist so jung. Ihr Gesicht wird heiß. Sie hat Falten um die Augen.",
 q("Nein, bitte nicht. Ich bin nicht mehr zwanzig","murmelt Anna."),
 q("Doch. Du bist sehr schön","sagt Nele."),
 "Nele macht zehn Fotos. Anna schließt jedes Mal die Augen.",
 "Jan steht in der Tür. Er trägt Annas alte Brille.",
 "Anna lacht laut. Nele macht schnell ein Foto.",
 q("Das Foto ist wunderbar","ruft Nele."),
 "Das neue Foto hängt dann am Kühlschrank. Das alte Foto liegt auf dem Tisch.",
]
T[(2,2)]=[
 "Der Rahmen ist aus Holz. Anna kauft ihn für Jan. Sie hat zwei Fotos in der Jacke.",
 "Anna sitzt auf der Treppe vor Jans Tür. Die Treppe ist kalt.",
 q("Welches Foto?","murmelt sie."),
 "Das erste Foto ist alt. Anna und Jan sind allein am Strand. Das zweite Foto ist neu. Nele steht zwischen Anna und Jan.",
 "Anna legt das alte Foto auf ihr Knie. Ihr Herz ist schwer.",
 q("Anna? Warum sitzt du hier?","fragt Jan."),
 q("Der Rahmen ist für dich. Aber ich habe zwei Fotos","antwortet Anna."),
 "Jan schaut lange auf das alte Foto.",
 q("Wir sind allein am Strand. Und so dünn!","lacht er."),
 q("Welches Foto willst du?","fragt Anna."),
 q("Ich? Du entscheidest","sagt Jan."),
 "Anna steckt das neue Foto in den Rahmen. Das alte Foto kommt in ihre Jacke.",
 q("Jetzt sind wir drei. Das ist besser","sagt Anna."),
 "Jan hängt den Rahmen neben den Kühlschrank. Die beiden stehen lange davor.",
]
T[(3,0)]=[
 "Donnerstag ist Spielabend in Jans Küche. Die Küche ist warm und laut. Sechs Freunde sitzen um den Tisch. Anna, die Grafikerin von oben, sitzt neben Jan.",
 "Felix, ein Mathelehrer aus dem Viertel, bringt ein neues Spiel. Er trägt ein graues T-Shirt. Er kennt alle Regeln.",
 q("Das Spiel ist ganz einfach","sagt Felix.")+" "+q("Jeder hat vier Figuren. Du würfelst und läufst."),
 q("Und die Punkte?","fragt Anna."),
 q("Die Punkte kommen später. Jetzt bist du dran","antwortet Felix."),
 "Anna würfelt eine Eins. Sie würfelt dann eine Zwei. Felix erklärt sehr schnell.",
 "Anna wirft den Würfel zu fest. Der Würfel fällt unter den Tisch.",
 q("Alle kennen die Regeln. Nur ich nicht","murmelt sie."),
 q("Früher spielen wir hier ein anderes Spiel","sagt Anna zu Felix."),
 q("Ich weiß. Jan spricht oft davon","antwortet er."),
 "Anna verliert. Sie ist die Letzte, und die Letzte spült.",
 "Anna steht müde an der Spüle. Felix bringt ihr die Gläser und lächelt.",
]
T[(3,1)]=[
 "Ein roter Würfel liegt in Annas Hand. Sie hat ihn seit der Schulzeit. Er bringt ihr immer Glück.",
 q("Mein Glückswürfel","flüstert Anna."),
 "Es ist spät und still. Jan und Anna sitzen allein in der Küche. Anna hört nur die Uhr.",
 q("Erklär mir die Regeln. Aber bitte langsam","bittet sie."),
 q("Gut. Eine Sechs ist gut. Mit einer Sechs startet deine Figur","sagt Jan."),
 "Jan stellt die Figuren auf das Brett. Anna würfelt mit ihrem roten Würfel. Sie würfelt drei Sechsen.",
 q("Drei Sechsen? Du bist wieder die Königin!","ruft Jan."),
 "Jan holt eine alte Kiste aus dem Schrank. Das Spiel von früher ist darin. Das Brett ist kaputt.",
 q("Wo sind die anderen drei Figuren?","fragt Anna."),
 q("Keine Ahnung. Das ist zu lang her","antwortet Jan."),
 "Annas Augen werden nass. Sie wischt die Augen schnell. Jan ist auch traurig.",
 "Jan wirft das alte Spiel in den Müll. Anna legt ihren roten Würfel in die neue Schachtel.",
]
T[(3,2)]=[
 "Die Gruppe spielt heute im Hof. Felix sitzt Anna gegenüber.",
 q("Heute gewinne ich","lacht Felix."),
 "Das Spiel ist fast zu Ende. Anna und Felix haben noch eine Figur. Alle schauen nervös auf das Brett.",
 q("Ich habe Angst. Mein Würfel muss helfen","flüstert Anna."),
 q("Du brauchst jetzt eine Vier","sagt Felix.")+" "+q("Nur eine Vier."),
 "Anna küsst ihren roten Würfel. Sie würfelt. Eine Vier, endlich!",
 q("Ich gewinne! Ich gewinne gegen Felix!","ruft Anna."),
 "Anna springt vom Stuhl. Der rote Würfel fliegt aus ihrer Hand. Er fällt durch das Gitter im Boden.",
 "Niemand kann den Würfel holen.",
 "Ihr Mund ist trocken, denn der Würfel ist seit der Schulzeit bei ihr. Sie legt die Hand auf das Gitter.",
 q("Das tut mir leid. Aber du gewinnst trotzdem","sagt Felix."),
 "Felix gibt ihr einen blauen Würfel.",
 q("Er ist nicht rot. Aber er ist für die Königin","meint er."),
 "Anna lacht stolz. Felix stellt den blauen Würfel neben ihr Glas.",
]
T[(4,0)]=[
 "Die Treppe im Haus ist dunkel. Anna ist eine Grafikerin und wohnt zur Probe oben. Sie steht vor einem alten Schrank. Der Schrank ist hoch und voll mit Büchern.",
 "Johanna ist eine Buchhändlerin aus dem zweiten Stock. Sie trägt einen Stapel Bücher im Arm und einen Stift hinter dem Ohr.",
 q("Suchst du etwas Bestimmtes?","fragt Johanna."),
 q("Ja. Einen dicken, grünen Roman","antwortet Anna."),
 "Die Bücher sind dick und dünn, neu und alt. Staub liegt auf den Büchern. Ein Zettel für Jan ist in dem Roman.",
 q("Grün? Das Buch ist leider nicht mehr hier","sagt Johanna."),
 q("Wo ist es?","flüstert Anna."),
 q("Jemand aus Hamburg liest es jetzt","antwortet Johanna."),
 "Anna seufzt und setzt sich auf die Stufe. Ihr Magen tut weh.",
 q("Der Zettel ist für Jan. Er ist wichtig","sagt Anna."),
 q("Keine Sorge. Ich sammle alle Zettel aus den Büchern","lächelt Johanna."),
 "Johanna rennt sofort in den zweiten Stock. Sie kommt mit einer Dose.",
]
T[(4,1)]=[
 "Viele kleine Zettel liegen in Johannas Dose. Johanna und Anna sitzen zusammen auf der Treppe. Johanna liest die Zettel laut.",
 q("Seite zwölf ist traurig. Danke für das Buch!","liest Johanna."),
 "Johanna lacht über jeden Zettel. Die Treppe ist kalt, aber die Zettel sind lustig.",
 q("Noch einer: Der Kaffee ist kalt, das Buch ist gut","sagt sie."),
 "Anna nimmt einen gelben Zettel. Die Schrift ist klein und schief. Die Schrift ist ihre Schrift.",
 q("Jan, lies Seite vierzig. Ich denke an dich. Anna","liest Anna leise."),
 "Jan findet den Zettel nie. Der Zettel wartet acht Jahre in einer Dose. Annas Kopf ist leer. Sie drückt den Zettel an ihr Herz.",
 q("Was steht auf Seite vierzig?","fragt Johanna."),
 q("Ich weiß es nicht mehr. Ich kenne nur den Titel","antwortet Anna."),
 q("Der Titel reicht. Ich besorge das Buch bald","sagt Johanna."),
 "Johanna schreibt den Titel in ihr Heft. Anna steckt den gelben Zettel in die Jacke.",
]
T[(4,2)]=[
 "Ein neues Buch ist da. Es ist grün, genau wie das alte. Johanna bringt es aus ihrer Buchhandlung. Das Buch riecht nach Papier.",
 "Anna klopft zweimal an Jans Tür. Der gelbe Zettel ist in ihrer Hand.",
 q("Anna? Ein Buch für mich?","fragt Jan."),
 q("Ein Buch und ein Zettel. Beide kommen zu spät","sagt Anna."),
 "Jan kocht gerade Tomatensuppe. Er liest den Zettel am Herd und öffnet das Buch auf Seite vierzig.",
 q("Lies du. Bitte","sagt Jan."),
 "Anna liest vorsichtig, Zeile für Zeile. Ihre Stimme zittert ein bisschen. Jan sitzt ganz ruhig neben ihr.",
 q("Zwei Freunde sitzen am Meer. Sie sprechen nicht. Sie sind trotzdem zusammen","liest Anna."),
 q("Wir sitzen nicht am Meer. Wir sitzen in meiner Küche","lacht Jan."),
 q("Die Küche ist auch schön","antwortet Anna."),
 "Jan stellt das grüne Buch in sein Regal. Anna sieht den Rahmen mit dem Foto daneben. Die beiden essen Suppe und sagen lange nichts. Jan ist froh.",
]
T[(5,0)]=[
 "Ihr altes Lied ist fünfzehn Jahre alt. Anna, die Sängerin von früher, singt es nie mehr. Sie trinkt heute Tee in Jans Küche. Der Tee ist warm.",
 "Jans Schulfreund Tim kommt mit zwei Trommelstöcken. Er ist Bankkaufmann, aber er spielt am Wochenende Schlagzeug. Jan ist gerade im Hof.",
 q("Jan hat am Samstag Geburtstag. Die Band spielt wieder, wie früher!","flüstert Tim."),
 q("Die Band? Wer spielt denn?","fragt Anna."),
 q("Ich spiele Schlagzeug. Ein Freund spielt Klavier. Und du singst","sagt Tim."),
 "Tim lacht oft. Anna nicht. Sie dreht nervös ihre Tasse. Die Stimme von Anna ist seit Jahren still.",
 q("Ich singe nicht mehr gern. Meine Stimme ist alt","sagt sie leise."),
 q("Deine Stimme ist nicht alt. Bitte, das ist wichtig. Für Jan","antwortet Tim."),
 "Die Tür öffnet sich. Jan kommt in die Küche. Tim versteckt die Stöcke hinter dem Rücken.",
 "Anna nickt plötzlich. Sie kann nicht Nein sagen. Tim lacht leise.",
]
T[(5,1)]=[
 "Es regnet, und der Keller ist kalt. Tims Schlagzeug steht zwischen den Fahrrädern. Anna hält den Text von früher.",
 q("Eins, zwei, drei, vier!","ruft Tim."),
 "Tims Stöcke schlagen auf die Trommel. Anna singt die erste Strophe. Die tiefen Töne sind nicht schlecht.",
 "Der Refrain kommt. Der Refrain ist sehr hoch. Annas Stimme bricht. Der Ton ist falsch und laut.",
 "Anna hält die Hände vor den Mund. Sie schämt sich. Tim hört alles.",
 q("Noch einmal. Ganz ruhig","sagt Tim."),
 "Anna trinkt einen Schluck Wasser. Sie singt noch einmal. Die Stimme bricht wieder.",
 q("Das Lied ist zu hoch für mich. Es geht nicht","sagt Anna."),
 q("Kein Problem. Wir schreiben bis Samstag ein neues Lied. Ein Lied für Jan, tief und einfach","antwortet Tim."),
 q("Und das alte Lied?","fragt Anna."),
 q("Das alte Lied bleibt im Keller","lacht Tim."),
 "Der alte Text kommt in ihre Tasche. Anna singt das alte Lied nie wieder.",
]
T[(5,2)]=[
 "Viele Kerzen brennen auf dem Kuchen. Die Küche ist voll, laut und warm. Jan hat heute Geburtstag. Er ist fünfunddreißig.",
 q("Alles Gute, Jan!","rufen die Freunde."),
 "Jemand macht das Licht dunkel. Die Musik beginnt. Tim sitzt am Schlagzeug. Ein Freund sitzt am Klavier.",
 "Anna hält das Mikrofon mit beiden Händen. Ihre Knie zittern ein bisschen.",
 q("Jan, dieses Lied ist neu. Es ist nur für dich","sagt Anna."),
 "Tim spielt leise. Anna singt tief und ruhig.",
 q("Eine Straße, ein Haus, eine Tür. Acht Jahre, und die Tür ist noch offen","singt sie."),
 "Tim spielt den letzten Schlag. Niemand spricht. Jan wischt sich mit dem Ärmel über die Augen.",
 q("Danke. Aber was ist mit dem alten Lied?","fragt Jan."),
 q("Das alte Lied gehört zu früher. Das neue Lied gehört zu jetzt","antwortet Anna."),
 "Alle klatschen und pfeifen.",
 "Der Freund am Klavier spielt noch einmal die Melodie. Anna singt jetzt ohne Angst, und Jan umarmt sie.",
]
T[(6,0)]=[
 "Ihr Rezept ist zwölf Jahre alt. Anna ist eine Grafikerin, aber sie kocht am Donnerstag für alle. Die Suppe ist billig und warm.",
 "Luisa, eine Köchin aus Jans Restaurant, steht am Herd. Sie trägt eine schwarze Schürze mit vielen Flecken. Drei riesige Töpfe sind schon da.",
 q("Wie viele Freunde kommen am Donnerstag?","fragt Luisa."),
 q("Zehn Leute. Mein Rezept ist nur für zwei","antwortet Anna."),
 q("Kein Problem. Wir rechnen einfach mal fünf","sagt Luisa."),
 "Luisa gibt Anna zuerst ein spitzes Messer. Anna schneidet Zwiebeln. Die Zwiebeln sind scharf, und ihre Augen tränen. Luisa probiert die Suppe mit einem großen Löffel.",
 q("Noch etwas Salz. Die Suppe ist zu mild","meint Luisa."),
 "Die Suppe riecht nach einer Stunde wie früher. Anna rührt ganz langsam.",
 q("Ich bin ein bisschen stolz","sagt Anna leise."),
 "Der Zettel mit dem Rezept rutscht in die Suppe.",
 q("Oh nein! Mein Rezept schwimmt!","ruft Anna."),
 q("Egal. Das Rezept ist jetzt in deinem Kopf","lacht Luisa."),
]
T[(6,1)]=[
 "Sein Lieblingstopf ist groß und alt. Anna kocht heute allein in Jans Küche.",
 "Das Telefon klingelt dreimal. Die Nummer ist aus München. Anna geht mit dem Telefon in den Flur.",
 q("Hallo?","fragt Anna."),
 "Ihre alte Chefin ist freundlich. Sie will Anna zurück in München.",
 q("Nach München? Ich weiß nicht. Ich brauche Zeit. Ich antworte später","murmelt Anna."),
 "Sie vergisst die Suppe. Es riecht nach Rauch. Jan steht in der Tür und hustet.",
 q("Anna! Der Topf!","ruft Jan."),
 "Anna rennt zum Herd. Die Suppe ist verbrannt und hart. Der Deckel ist heiß. Sie hält den Deckel vorsichtig in der linken Hand. Anna weint fast.",
 q("Es tut mir so leid. Das ist dein Lieblingstopf","flüstert Anna."),
 q("Wer ist am Telefon?","fragt Jan."),
 q("München. Meine alte Arbeit","antwortet Anna."),
 "Jan ist nicht böse. Er kratzt lange im Topf.",
 q("Der Topf ist kaputt. Kein Drama. Die Freunde kommen um acht","sagt Jan."),
 "Der Topf steht dann vor der Tür.",
]
T[(6,2)]=[
 "Drei kleine Töpfe stehen auf dem Herd. Drei kleine Töpfe stehen auf dem Tisch. Es riecht nach Karotten. Jeder im Haus bringt einen Topf.",
 "Luisa kommt mit zwei Tüten Gemüse.",
 q("Sechs Töpfe? Gut! Wir kochen sechs kleine Suppen","sagt Luisa."),
 q("Aber die Gäste kommen doch gleich","antwortet Anna."),
 q("Wir sind sehr schnell. Hier sind die Karotten","lacht Luisa."),
 "Anna schneidet. Luisa würzt mit Kräutern. Die Löffel klappern.",
 "Anna ist müde, aber froh. Der Abend ist nicht verloren. Sie deckt den Tisch mit zehn Tellern.",
 "Die Gäste kommen. Alle sind hungrig. Jan setzt sich zu den Nachbarn an den Tisch. Die Löffel passen nicht zusammen. Die Teller sind alle verschieden.",
 q("Das ist meine Suppe von früher. Aber in sechs Töpfen","sagt Anna."),
 "Jan isst zwei Teller und schmatzt.",
 q("Die Suppe ist lecker. Wie früher, nur besser","meint Jan."),
 "Alle sind satt und zufrieden. Luisa trinkt ein Glas Wein neben Anna. Die sechs Töpfe sind leer.",
]
T[(7,0)]=[
 "Eine Notiz klebt an Annas Tür. Anna, die Mieterin auf Probe, lehnt am Geländer und liest. Die Notiz ist höflich.",
 "Niklas ist der Hausbesitzer. Er wohnt im Erdgeschoss und trägt immer einen braunen Pullover. Er ist nett und freundlich, aber streng.",
 q("Liebe Anna, die Wohnung ist nur bis Freitag frei. Bitte gib mir eine Antwort. Niklas","liest Anna."),
 "Die Wohnung oben ist klein, aber gemütlich. Sie hat viel Licht. Anna mag den Blick in den Hof. Das Fenster ist offen.",
 "Niklas steht plötzlich neben ihr. Er räuspert sich.",
 q("Hallo Anna. Eine Frau aus Hamburg will die Wohnung leider auch","sagt Niklas."),
 q("Und ich? Ich brauche noch ein bisschen Zeit","antwortet Anna."),
 q("Ich warte bis Freitag. Der Freitag ist die Grenze","sagt er."),
 "Anna ist blass, denn München wartet auch bis Freitag. Sie knüllt die Notiz in der Faust.",
 q("Gut. Du bekommst am Freitag eine Antwort","sagt Anna."),
 "Niklas nickt. Seine Schuhe quietschen auf der Treppe.",
]
T[(7,1)]=[
 "Es ist schon dunkel. Anna steht mit einem Kuli vor Jans Kühlschrank. Sie macht eine Liste mit zwei Spalten.",
 "Jan, der Koch, kommt in die Küche und gähnt. Der Kühlschrank summt.",
 q("Was ist das für eine Liste?","fragt Jan."),
 q("Für Freitag. München oder Bremen","antwortet Anna."),
 "München steht links. Bremen steht rechts. Anna schreibt unter München: mehr Geld, großes Büro. Sie schreibt unter Bremen: Jan, Freunde, Musik.",
 q("Geld, Büro. Jan, Freunde, Musik","murmelt Anna."),
 q("Mein Name steht hier. Ich will nicht dein Grund sein. Du entscheidest für dich","sagt Jan."),
 "Jan macht einen Strich durch seinen Namen.",
 "Anna telefoniert dann mit München. Sie bittet um eine Woche mehr. Die Chefin sagt sofort Nein.",
 "Anna kaut auf dem Kuli. Beide Spalten sind fast gleich lang.",
 q("Ich bin ratlos. Und jetzt?","flüstert sie."),
 q("Jetzt schläfst du. Die Antwort kommt morgen","sagt Jan."),
 "Jan geht leise in den Hof. Die Spalte für Bremen ist jetzt kürzer.",
]
T[(7,2)]=[
 "Ihre Hand ist ruhig. Anna unterschreibt den Vertrag mit blauer Tinte. Niklas schüttelt ihr die Hand. Er ist zufrieden.",
 q("So. Das ist mein Name","sagt Anna."),
 "Niklas gibt ihr zwei Schlüssel. Die Schlüssel sind kalt. Einer ist für den Keller.",
 "Anna tippt an ihre Chefin: Nein, danke. Sie schluckt schwer.",
 "Jan wartet unten mit Sekt. Die Gläser klirren.",
 q("Und? Was sagt der Vertrag?","fragt Jan."),
 q("Zwei Jahre. Mindestens zwei Jahre","antwortet Anna."),
 q("Und München? Bist du sicher?","fragt er."),
 q("München sagt Tschüss. Das Geld auch","lacht Anna."),
 q("Dann Prost!","ruft Jan."),
 "Jan öffnet seine Schublade. Die erste Postkarte liegt noch dort. Die Ecken sind krumm.",
 q("Lieber Jan, ich komme im Mai. Deine Anna","liest Jan."),
 "Anna schreibt einen neuen Satz darunter.",
 q("Ich bleibe","liest Jan.")+" "+q("Das ist der beste Satz auf der Karte."),
 "Jan klebt die Karte mit einem Magneten an den Kühlschrank. Annas Name steht jetzt in der Spalte für Bremen.",
]
# volcar en texts.json conservando titulos
for t in range(1,8):
    p=f"scripts/_deA0Friends/t{t}-texts.json"; ds=json.load(open(p))
    for d in ds: d["text"]="\n\n".join(T[(t,d["slotIndex"])])
    json.dump(ds,open(p,"w"),ensure_ascii=False,indent=1)
# informe
data={}
for t in range(1,8):
    for d in json.load(open(f"scripts/_deA0Friends/t{t}-data.json")): data[(t,d["slotIndex"])]=d
for (t,s),paras in T.items():
    txt="\n\n".join(paras); w=len(re.findall(r"\w+",txt)); qw=sum(len(re.findall(r"\w+",m)) for m in re.findall(O+"([^"+C+"]*)"+C,txt))
    toks=set(re.findall(r"[^\W\d_]+",txt.lower()))
    miss=[v["surface"] for v in data[(t,s)]["vocab"] if v["surface"].lower() not in toks]
    flag=("" if 128<=w<=155 else " PALABRAS") + ("" if 26<=100*qw/w<=34 else " CITADO") + (f" FALTA:{miss}" if miss else "")
    print(f"{t}.{s} {w} {100*qw/w:.0f}%{flag}")
