import json
d=json.load(open("scripts/_deA0Friends/t5-texts.json"))
V=lambda t,w,s,df: {"type":t,"word":w,"surface":s,"definition":df}
d[0]["synopsis"]="Tim, an old school friend of Jan, has a plan for Jan's birthday: the band from school plays again. Anna was the singer, and now she is afraid."
d[0]["vocab"]=[
 V("noun","das Lied","Lied","A song; music with words that you sing."),
 V("number","fünfzehn","fünfzehn","Fifteen; the number after fourteen."),
 V("noun","die Sängerin","Sängerin","A female singer; she sings, often in a band."),
 V("verb","trinken","trinkt","To drink; to take water, tea or coffee."),
 V("noun","der Schulfreund","Schulfreund","A school friend; a friend from your school years."),
 V("noun","der Trommelstock","Trommelstöcken","A drumstick; a stick you hit a drum with."),
 V("noun","der Bankkaufmann","Bankkaufmann","A bank clerk; a man who works in a bank."),
 V("noun","das Schlagzeug","Schlagzeug","A drum kit; many drums played by one person."),
 V("noun","der Geburtstag","Geburtstag","A birthday; the day you were born, every year."),
 V("verb","flüstern","flüstert","To whisper; to speak very quietly."),
 V("pronoun","wer","Wer","Who; the word to ask about a person."),
 V("noun","das Klavier","Klavier","A piano; a big instrument with black and white keys."),
 V("verb","singen","singst","To sing; to make music with your voice."),
 V("adverb","plötzlich","plötzlich","Suddenly; very fast and without warning."),
 V("adjective","still","still","Silent; quiet, with no sound."),
 V("adjective","nervös","nervös","Nervous; a little afraid and not calm."),
 V("verb","drehen","dreht","To turn something round and round."),
 V("preposition","hinter","hinter","Behind; at the back of something."),
 V("noun","der Rücken","Rücken","The back; the part of your body behind you."),
 V("verb","nicken","nickt","To nod; to move your head up and down for yes."),
]
d[1]["synopsis"]="The band practises in the cold cellar. The old song starts well, but the chorus is too high now, and Anna's voice breaks."
d[1]["vocab"]=[
 V("verb","regnen","regnet","To rain; water falls from the sky."),
 V("noun","der Keller","Keller","A cellar; the room under a house."),
 V("verb","schlagen","schlagen","To hit; here, to beat a drum."),
 V("noun","die Trommel","Trommel","A drum; you hit it to make music."),
 V("noun","die Strophe","Strophe","A verse; one part of a song."),
 V("adjective","tief","tiefen","Low; a deep sound, not high."),
 V("noun","der Ton","Töne","A note; one sound in music."),
 V("noun","der Refrain","Refrain","A chorus; the part of a song that comes again."),
 V("adverb","sehr","sehr","Very; a lot, more than normal."),
 V("adjective","hoch","hoch","High; a sound far up, not low."),
 V("verb","brechen","bricht","To break; here, the voice suddenly stops working."),
 V("adjective","falsch","falsch","Wrong; not right, out of tune."),
 V("verb","schämen","schämt","To be ashamed; sich schämen means to feel bad."),
 V("preposition","vor","vor","In front of; before something."),
 V("adverb","ganz","Ganz","Quite; completely, very much so."),
 V("adverb","einmal","einmal","Once; noch einmal means one more time."),
 V("noun","der Schluck","Schluck","A sip; a small amount of a drink."),
 V("noun","das Wasser","Wasser","Water; the clear drink from the tap."),
 V("pronoun","kein","Kein","No; not any, not one."),
 V("preposition","bis","bis","Until; up to a certain time."),
]
d[2]["synopsis"]="It is Jan's birthday, and the kitchen is full. Anna holds the microphone with both hands and sings a new song, only for Jan."
d[2]["vocab"]=[
 V("verb","brennen","brennen","To burn; candles give light and heat."),
 V("number","fünfunddreißig","fünfunddreißig","Thirty-five; the number after thirty-four."),
 V("pronoun","jemand","Jemand","Somebody; a person, but you do not say who."),
 V("verb","beginnen","beginnt","To begin; to start."),
 V("noun","das Mikrofon","Mikrofon","A microphone; you sing into it to be louder."),
 V("preposition","mit","mit","With; using something in your hands."),
 V("pronoun","dieser","dieses","This; the one here."),
 V("adverb","nur","nur","Only; just this and nothing else."),
 V("verb","spielen","spielt","To play music on an instrument."),
 V("noun","der Schlag","Schlag","A beat; one hit on a drum."),
 V("verb","wischen","wischt","To wipe; to move a cloth over something."),
 V("noun","der Ärmel","Ärmel","A sleeve; the part of a shirt around your arm."),
 V("pronoun","was","was","What; the word to ask about a thing."),
 V("preposition","zu","zu","To; here, it belongs to that time."),
 V("pronoun","alle","Alle","Everyone; all the people."),
 V("verb","klatschen","klatschen","To clap; to hit your hands together."),
 V("verb","pfeifen","pfeifen","To whistle; to make a high sound with your lips."),
 V("noun","die Melodie","Melodie","A tune; the music line of a song."),
 V("preposition","ohne","ohne","Without; not having something."),
 V("noun","die Straße","Straße","A street; a road in a town with houses."),
 V("adjective","offen","offen","Open; not closed, so you can come in."),
]
json.dump(d,open("scripts/_deA0Friends/t5-data.json","w"),ensure_ascii=False,indent=1)
